apiVersion: v1
kind: Service
metadata:
  name: vllm-api
  namespace: vllm
  annotations:
    lbipam.cilium.io/sharing-key: "lan-shared"
    lbipam.cilium.io/sharing-cross-namespace: "*"
    lbipam.cilium.io/ips: "192.168.1.120"
spec:
  type: LoadBalancer
  selector:
    app: vllm
  ports:
    - name: http
      port: 8000
      protocol: TCP
