apiVersion: v1
kind: Secret
metadata:
    name: minecraft-makoto-secret
    namespace: minecraft
type: Opaque
stringData:
    RCON_PASSWORD: ENC[AES256_GCM,data:ZYeH8H6E3P/ruMOux4fYaAGga9A+wswI/JG98QrszTI=,iv:flNapwUUz+ouVUYar9t6Yz6dEiCfzeJFzNuaTeCoLIg=,tag:3HCswj3//UOo0K02o4beQg==,type:str]
    DISCORD_WEBHOOK_URL: ""
    SERVER_ADDRESS: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBOVBZQUxI
            TC9hUVJ3T2dEdlhYOUJQb0xQc3JEOEZKbjBxZUFld3UvU2FPQgo4eEFiaURyNCtM
            VmFXbU5vRk92TW93NWtPUEZHWmkvVjE1azEwVjhoelZRCi0tLSAyUCtyVkVyUXF5
            VTJKSGV1YkJzTnJTQm0wY2hqS2Y2N2UwR0JhZnpGQk9VCg1Vfjt1xDZ1qChDkQsQ
            N8nyQz9yJAEFBiTdMAisqb1xgIUhiYN3yLNuHhPCC8q8ZJF4gJeDjf1tgvxLkcPc
            DVY=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0U1lSYUVwQXozT3BoWU4x
            Y1hlRDN1TER6bDNhdlkxdWJ1SGxHNFhqQlZvCmlNMjdBVW1CbWxXNnNkakZrYnFD
            djE5WjRqbVc5K3VSVFpSYnh0NS8wUk0KLS0tIEJIRm1rcXVGQjYvNHNwa0VVSWxF
            VVR1NUZYQmsrQzQwUWNyWWRXdTREQncKTEXsF9JLFa8yjgHRtk2vLmSAnTfuLb35
            Cn1pvDgvmVZqLvN6V/dgOt8jBGTLOrnb94YAIRN1Wq4tXdUmLmnTvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T03:48:17Z"
    mac: ENC[AES256_GCM,data:zMbdKnCbL0hrOEKODkVlYvTf1/1HZQhAyvb8FPQ8S+qaZqxL7OsgalEVaG7uD7kVGTlNyQOm6Izcv7E9qcLare8UsWOEs0CXvghrGjDSjRabG85kB6LYnrdI2BZVPX0LETpj7jCFx5Tznur6CTsDOB21UvEpVv49HJx7qMTezso=,iv:BFv8CIQYTdhf3xx8juitxvlbkspVFl4BK+HB7jIJMmM=,tag:1wufgqTjQXu1wUZNnuF0iA==,type:str]
    version: 3.13.3
