apiVersion: v1
kind: Secret
metadata:
    name: minecraft-secret
    namespace: minecraft
type: Opaque
stringData:
    RCON_PASSWORD: ENC[AES256_GCM,data:MCT1AFF5y5KExhHOdj5vQfha7mtF+xZx5qiiYrPDoTc=,iv:GsICYuISHKid5yu4QJfKe087JoxOFa3lHv/aX0pbcrs=,tag:PK86Hn6vCLgmkYYHyTwleA==,type:str]
sops:
    age:
        - recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBcXpQYW81
            SmRNUFpuSVErQVNUZlZ2T2I5SHpvd0NWZXVYK3lhMzVLd09ZbwpKWHZ5dzdJTmJk
            SmhqUFA0ODVUbnVheksweGI1Und4V2ZFOFpwWVloRGVNCi0tLSB1UUoxY05qc1Ny
            VTlYV21oVWtCQXZ4T1liM04zUDlCU0NOZFhnMm4yY0dvCjDJRUgfNvGyXZ4UwcNX
            7N4JTgFvvh4zFGScIgdUivOlcIedjDhxPEobPF8VTd4dEPtpIfEv+FN31B5lzR3F
            s5c=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1K2I0UEYrbE9KMk5VbG1L
            OXNKd2IwNWZWZW1WSDQweHFxRE9tREFMQWdBCkR3Z05RdVVXU1hEOG41VFRyTkkw
            T052SDB1MTBwRUZOVXlSdVY0Rm53c0kKLS0tIE5ROTNDQnFnbDJaVVNYd0pJZkxu
            OVZ4dCtWVGIvbHpKSmRuYVlRRS9TcnMKdPcMSfxlIJBk27pff+GR4ra/pcgtHIe/
            nRLTH+qRPcrUTFIenWryH6PsbQm49mdUFaDAvEmHZmkIS6pelAs8nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T09:52:31Z"
    mac: ENC[AES256_GCM,data:6vW917gi2OoWkJqE6SEiMXj9z0kojJMEKRz7oUsgTwaYkRry/Ehz11RE4cJoc+twTobAt7OzBkUuCqJLZZCRsckQVejnyf5PqP0wY0HNNu5JyfMy80SP6AatIWqbkwN7jpxxzZdMQFQ9ovwAlC+Df8fS04OOWTpvw29Bl0prc8g=,iv:X19cAmAbAmZVNNIqmfPhtCQqd7NR+Fpp56TehoJaY4g=,tag:8l/c7CFIZfBkae4ci3pqSQ==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsZones)$
    version: 3.12.1
