apiVersion: v1
kind: Secret
metadata:
    name: minecraft-makoto-secret
    namespace: minecraft
type: Opaque
stringData:
    RCON_PASSWORD: ENC[AES256_GCM,data:ICS4mlNvkYwGQKCcm5QvISAbBFy3Rlz7ZFxKPEVNhDA=,iv:woRLXf4/2ZzISfVAnSi9IX5j87MAUEuUNRa+x1T7gJk=,tag:Xh/xWOVcQyrBpg/ZJtj1Cg==,type:str]
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:jVW/6RfZwwAc15OaPEOSJN8Lw2Jfwnr/U5jRF6ArHi8h0VkRiULHZ0wbocPeGQ9v9wuh3uGzUtnLLCXvmDz+qqw0jpPwt+N8bas8Hce1T2DdmmxNhlkmxT8qFXPsqkZ4ElVxrg1cryjKVbof8AXE7qya1I15nGM95y6stQ==,iv:D1JHWArTeAS4p9m9pDg8g3xfifZIkXsmepZsY2AW+JM=,tag:C5fSy5PL2brEX9JPxJ+Lnw==,type:str]
    SERVER_ADDRESS: ENC[AES256_GCM,data:jJMhvCMc7Vl+qgALYmCxYfkWVsOiWrbJSg==,iv:vk61HrkrS6EeDQ5Kgq7no4tyL1TFQRvPJqnaY0pGKYY=,tag:T+jBTgqZ1RJ/RgILYcz10A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBb0VWM1dy
            L2tOMjM2TituM3ozZG92TW1WL0RGTC93K1hIeVgyRDBSeExzSwphc2dTZ1FaNmlT
            Q1pGWkRPbThNSzZjdEFLMFJxbDdiQmNuV0haYXhQSkxFCi0tLSAzUWt0Uy83a2Yz
            emZFQUJjOVYrUmtqUHF0RExjWWxBVmk5VlpvS3AxSXBJCilSpmbD3JSvTO/uuUhi
            KBX+zyxUThIDDtVXim8w4RxYNJTbTCa4et1FbPaVz4ixIV9aJgdeFsGUKHDEyoso
            y3M=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNU0wQjlyVCtPZ2NleEpR
            NjRKYkVjYnlidU9QcDhPeW55R2Exc0NEdkRNCmJmVjNnZkZQR09OdFhjOFgxSGpM
            Y0tnWGZ0Um5oWXd1d1Z3emxVbERHdk0KLS0tIE1jMmdYRGlYZlExSWdESEErMjJz
            Rk1IaERNdzBWV1daS3J4NEtrYnhReEEK18//Upz7KY6pasbqitKkf2PS5vrvmM2e
            0umyFfetZn0PXCfeg8fTEaXU7x12U1kwtECaJYGR0X3soA/H/7rpag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T04:53:33Z"
    mac: ENC[AES256_GCM,data:F0meBkr5v8mBdHSGl375pgq6D9pO/fSdjL5lqJxQ7VPu+vg03QYlSd7nJ/pPStcDhXZTP0iSkJW/risF3TKClMliHFIuYiDkpXXQFld4kJr7fnByXMbdQpGl7IDXnN9TS0bLJD5Fjf2rfDqMGfaamRKyl2E5QYsSWXEuDbZ49lc=,iv:7M4PuzhUAyqH4S+o9W6rSf94BcnOS0QIMEJXzq9YyOI=,tag:zfvJI3565RZSsGfXrVtwnA==,type:str]
    version: 3.13.3
