apiVersion: v1
kind: Secret
metadata:
    name: minecraft-secret
    namespace: minecraft
type: Opaque
stringData:
    RCON_PASSWORD: ENC[AES256_GCM,data:j2NR+MPnAY3zKI0hkemkzE+i7VYfcUqucUcs1/mi/Gw=,iv:ywCNpeSYcl7FZuMXWxRgYi2hjoFNP71IwZ9WR6JnVjQ=,tag:oHI+EGBixq3D1ivgHi+jsg==,type:str]
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:8FtWfzB7somAsqoI+gQstR4JSiQGX24d4Ny86cH0mFmLrL6tEYLjMohsJcZ1pu0nf0olXWOvO3yuTl7YTK+tct8Ogc7X4xpDNk+gCZBtNZQnlOOcezCXhWmWZtp1oAegGD8Xg8SZJmM0Z2eTpavjsgt9i6msDFCQgLd4Hg==,iv:oRhL7C58Y7UfgPPktv3ptB3XOX7iskvz7wKS3xFbG1U=,tag:X2sxvRzSCH6CZX+UnROS1w==,type:str]
    SERVER_ADDRESS: ENC[AES256_GCM,data:k0rK7yMfA1USTOMqK1tjIzC5Pg==,iv:EvJyTR1DCxCl78pkIh8qF5gqdiBysmnFO8413JrqA9k=,tag:0ovAyzcnS7BbCXGVdwEqAg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBejdTdFVs
            M1lMcDN0MnhiWHcvRyswWmhOeGxsVlhoOWxaUzM0QmIrMDcwaAppaUhIZWpLV3Yr
            ZTB4Y3FjNDYrcXBEcnF6SXNuTVRYTXlwaldpbGZQRFNvCi0tLSBuMS9SQUxUV0ta
            VysyTHpUVDUvc1BiOC9EMEtTalBmNThGN0h0SEhQWTBRCp8JhTJ+zFZbGmn8/4Y9
            HzacEuaP4FDuOsEy66PWN0XTOkjXF0bpomZms85fwse1LFssSHqj33LglyVwElwS
            CUE=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTUZUdHFUdUpBbjVGcERi
            V3QvYW1vRUdDenJxdXA4OXF3LzVhMDgvNzFJClVIWmROK3ExNW9sNWlSTnRoV08x
            QU1WZG9ULzR0cGxqQlpCMWtwaXJLSmcKLS0tIEkvaFNOT2dtbnh3ZmhFZDZxMFcy
            OVhYaDVGUjB2anB6YWFZcVJDTURveGcK0ET3d+xfx963rjEDXzwlWq2HcgBPJLjc
            7qVcZnHQroA2lCcXx51C4whtSSYJ47leh1vOkydIJM8+nAe8mWPUAg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T22:47:48Z"
    mac: ENC[AES256_GCM,data:fjhcPlDCIkCNQSc4VHB0u7xI9UkKnY+n70GWGk9+p7ED61BO4LZsjAivm9DGZAovSBNN5PfLBtTtyXduYWZpiifC49PqUzRLtmJPdXJzRdylGIUSrkUWuiPCdcBLZKtsDBQYDgOCq8P1pWZWY/J//u6GCDFCvnV3O+x4vAEwLUE=,iv:s6KDVzsVGKIXwvrznFNZbwcI/7ooRAzhW8BaSWgutKw=,tag:f5P+HIuTjbkLhJQiZ4QpZQ==,type:str]
    version: 3.13.3
