apiVersion: v1
kind: Secret
metadata:
    name: minecraft-makoto-secret
    namespace: minecraft
type: Opaque
stringData:
    RCON_PASSWORD: ENC[AES256_GCM,data:1vakoJjHXRixaTDWJ22qx9/uj1h89xeGIz7005/1yuU=,iv:tAUSpxpYQrgzmjF2gWzROCT3XfKvfQy5lMGRZSnb/tM=,tag:Yx3SYa2nIvhJgkN52iEXCw==,type:str]
    DISCORD_WEBHOOK_URL: ""
    SERVER_ADDRESS: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBeHVoT2E1
            VXZ2TUhBcnMzSU1BeFN1QkNSVVYvYngvNThJaS9pY09wYnh2awpaTis1RDdvZVFF
            WHB1MTFlQ3pLdVRjQ2NsOXZOQUl3dzRDNUcxaWZaZDZFCi0tLSBBcENOKzNOdm9I
            dWdZY2hIbU5mM1pKNkFHT2N3eFRKQnM0ckJiaGc0Z040CrJkAk7hVDQJTFnEh4AB
            6UC3U5k8AAIn0ojBDZEliRWWJWO5iMH0O4I8pltHc+pmM/VNZd8MrN3HjJlocLZo
            fvU=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUeU04YTJBT2FIZVBGNnlF
            VWErVVViRDB5dVRJMVEza1Q5eVBmbGhDKzNrCitjWFVPWlNrR3NlaDcvSVlsZGcz
            KzgzbWpPMjd5NVR1aEZWb1F1TXBzdVkKLS0tIFhEcTZxRnREaXdlcDhzRndLQlIv
            bFplOXdidCtsSHNCQWlHSldQWThEYmcKez/mKeBSNZy0J5enXcF3cmcIYuiyEC+m
            XI8YNhPpQnK0E2JRMmBZ1r35hacq7JT06dO08O4GI8ypskqapsAi5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T04:08:35Z"
    mac: ENC[AES256_GCM,data:KX6olFR43xNpHOW66Kp4sKvD+GMP3RTIRg4cLbTnmrmkv2IYmUhlk+t9yGco+ZYV2EYMmA434+Wwsf/yjxaGpqSftIUWEcAsaamZGwYYeoV/wcb5USBzMahEdJwszHX/As/vkHe32PoRLfCEHARrSEwmKBBG9IjQu21+WcLLh6I=,iv:zR1KmVb7wFpS6eGqj8/LvQZzUqJdCSlqBvgZCQYHark=,tag:2zO1FSrPjccob3azoZJ1vA==,type:str]
    version: 3.13.3
