apiVersion: v1
kind: Secret
metadata:
    name: minecraft-secret
    namespace: minecraft
type: Opaque
stringData:
    RCON_PASSWORD: ENC[AES256_GCM,data:MwL9bTreOmow1BzqsdgfUSZFqYM8wiiiCmARNp88Ud0=,iv:MaCPIJJAWM+Uoy1cwnlLunZs7xkPngA9XLAMsC5Nhqk=,tag:8y1xiS0YfzHp45QYcOglNQ==,type:str]
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:EdKnCJ+FYS+B+vL2pZJJPZeFLu8v0KZ5WLEuap1dahMSWlTjl7YZZKc91vzMft76PVYhFkLfIqbAly7vGzvKT8g2E7v13cqODpj3WReOBZoTTYUHprxHHvRPXXgOwYXM7RRZru7zIrxbOplpUDOTO3VuhXgiCjJoSpvS6w==,iv:5xLdQHqG2mCt/pabEEJ5r9GlrQyf5oMimzzVkLkec5w=,tag:tUuoaLS89JwFZWdmFzEkKA==,type:str]
    SERVER_ADDRESS: ENC[AES256_GCM,data:4Cf23K+M4eVp5oCh7StbLFL1bw==,iv:GfI3PuC3HmZi+2mWz/gGPdiTrfTuo0gkIySozwqgNVk=,tag:EkjCKKesreDVXV68wkirOg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBcko3QWJJ
            UVFiOVJ6SmswYXdROUQyc2pxZ3JRdDR1OFEzUkRNMUJQcmd1SwozVGxQU2p6UWlv
            RitTV2pESkQyQlFlc0poQU5wUXJZOXhwZXBkbW0zRWRzCi0tLSA1ZUxkeU5hcXlI
            eU1KalJuZW9BbzRJUytpMXdzT21QL3lra29ENTNEZlJjCm1j4VLGCoi4D8DGfMjf
            66E5FW9JJhb1o17BdO9+BnYOKr5tckBU3i5G/TtSQJsqla1D8TKqh4PGf7MNWHmg
            OvU=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSzFYVW5YWHNtYXhXaXBP
            MWF4emE5SWVTRTltS0VIOWRDZDZaNThZNjA4CjV5TVRZZWMyRkNNSkNSNEFPek8y
            Wjd4eFdYNWsreTl2a1BoNDhKVlExeEEKLS0tIE9LSEpaaXl6MHFmY1d2M0d0UUhL
            WmozQkJoZHZtb1IrdlRnYXd5ZVdhdGcK+6JrvcS9GAKBdNvY7tboDant0ROMcIo+
            WNV6sEWOoj6/osw7WJdxc/dXTRYaD1/+AXhMeiAIcNWNABREzJUvbw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T04:29:36Z"
    mac: ENC[AES256_GCM,data:jMM/+kni5Mkd+xtTEF6s90t2TIsvGkGqlwP8Ci7G6ENWOaVif6Z0kwpSHR0xrc/+2Q9OF1uRw5boT2Wq2gLe8nd0bWZcwUuPhWMYwX7apLnGLmCKV1KqG0C9uc7a4XuuJFK60MMvgLf8HuswmdRAFX+s48IdgLNmho3xyVPj3UQ=,iv:BzTcpE1ZZRU95ncgCr8ROsLya1i+mFW6eK3O/i7mtQw=,tag:9R+yxfz4IRH0Il4WmJoiCQ==,type:str]
    version: 3.13.3
