apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: plex
  namespace: plex
spec:
  endpointSelector:
    matchLabels:
      app: plex
  ingress:
    - fromEntities: [world, remote-node, health]
      toPorts:
        - ports:
            - { port: "32400", protocol: TCP }
            - { port: "32469", protocol: TCP }
            - { port: "3005", protocol: TCP }
            - { port: "1900", protocol: UDP }
            - { port: "32410", protocol: UDP }
            - { port: "32412", protocol: UDP }
            - { port: "32413", protocol: UDP }
            - { port: "32414", protocol: UDP }
  egress:
    - toFQDNs:
        - matchName: "plex.tv"
        - matchPattern: "*.plex.tv"
        - matchPattern: "*.plex.direct"
        - matchPattern: "*.plex.bz"
        - matchName: "plexapp.com"
        - matchPattern: "*.plexapp.com"
      toPorts:
        - ports: [{ port: "443", protocol: TCP }]
    - toEntities: [world]
      toPorts:
        - ports: [{ port: "1900", protocol: UDP }]
