apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media-dxp6800
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-media
  mountOptions:
    - ro
  nfs:
    path: /mnt/primary/videos
    server: 192.168.1.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media
  namespace: plex
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: nfs-media
  volumeName: plex-media-dxp6800
  resources:
    requests:
      storage: 1Mi

