apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media-dxp6800
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-media
  mountOptions:
    - ro
  nfs:
    server: 192.168.1.2
    path: /mnt/primary/videos

