apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plex
  namespace: plex
spec:
  serviceName: plex
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - fluxeon
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: plex
          image: plexinc/pms-docker:latest
          imagePullPolicy: Always 
          securityContext:
            privileged: true
          ports:
            - name: plex
              protocol: TCP
              containerPort: 32400
            - name: dlna-udp
              protocol: UDP
              containerPort: 1900
            - name: dlna-tcp
              protocol: TCP
              containerPort: 32469
            - name: companion
              protocol: TCP
              containerPort: 3005
            - name: gdm-1
              protocol: UDP
              containerPort: 32410
            - name: gdm-2
              protocol: UDP
              containerPort: 32412
            - name: gdm-3
              protocol: UDP
              containerPort: 32413
            - name: gdm-4
              protocol: UDP
              containerPort: 32414
          env:
            - name: TZ
              value: "America/Chicago"
            - name: PLEX_UID
              value: "0"
            - name: PLEX_GID
              value: "0"
            - name: LIBVA_DRIVER_NAME
              value: "radeonsi"
            - name: AMD_VULKAN_ICD
              value: "RADV"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /media
              readOnly: true
            - name: transcode
              mountPath: /transcode
            - name: dri
              mountPath: /dev/dri
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
            limits:
              memory: "8Gi"
              cpu: "4000m"
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /identity
              port: 32400
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /identity
              port: 32400
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 5
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: plex-config
        - name: media
          persistentVolumeClaim:
            claimName: plex-media
        - name: transcode
          hostPath:
            path: /var/lib/plex-transcode
            type: DirectoryOrCreate
        - name: dri
          hostPath:
            path: /dev/dri
            type: Directory
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain

