apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: seaweedfs
  namespace: seaweedfs
spec:
  endpointSelector:
    matchLabels:
      app: seaweedfs
  ingress:
    - fromEntities: [world, remote-node]
      toPorts:
        - ports:
            - { port: "8333", protocol: TCP }
    - fromEndpoints:
        - matchLabels:
            app: seaweedfs
      toPorts:
        - ports:
            - { port: "8333", protocol: TCP }
            - { port: "8888", protocol: TCP }
            - { port: "9333", protocol: TCP }
