apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-ip-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.64-192.168.1.127
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-layer2-lan-advertisement
  namespace: metallb-system
spec:
  interfaces:
  - eth0
