apiVersion: v1
kind: Service
metadata:
  name: authentik
  namespace: authentik
  annotations:
    lbipam.cilium.io/sharing-key: "lan-shared"
    lbipam.cilium.io/sharing-cross-namespace: "*"
    lbipam.cilium.io/ips: "192.168.1.120"
spec:
  type: LoadBalancer
  selector:
    app: authentik
    component: server
  ports:
    - name: http
      port: 9000
      protocol: TCP
    - name: https
      port: 9443
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: authentik-worker
  namespace: authentik
spec:
  clusterIP: None
  selector:
    app: authentik
    component: worker
---
apiVersion: v1
kind: Service
metadata:
  name: authentik-ldap
  namespace: authentik
spec:
  type: ClusterIP
  selector:
    app: authentik-ldap
  ports:
    - name: ldap
      port: 389
      targetPort: 3389
      protocol: TCP
    - name: ldaps
      port: 636
      targetPort: 6636
      protocol: TCP

