apiVersion: v1
kind: Service
metadata:
  name: authentik
  namespace: authentik
  annotations:
    lbipam.cilium.io/sharing-key: "lan-shared"
    lbipam.cilium.io/sharing-cross-namespace: "*"
    lbipam.cilium.io/ips: "192.168.1.120"
spec:
  selector:
    app: authentik
    component: server
  type: LoadBalancer
  ports:
    - name: http
      port: 9000
      targetPort: 9000
    - name: https
      port: 9443
      targetPort: 9443


