apiVersion: v1
kind: Secret
metadata:
    name: makotogotchi-secret
    namespace: makotogotchi
type: Opaque
stringData:
    MONGODB_URI: ENC[AES256_GCM,data:YBZdhoGxP5KCBCHRhm6TyVT5Yp/R0eQ+ZEhpaffoxMvGiVM/iDa0k70KCnyrFYiB+1Dx8kaO80GQK0dLpTiULrohLtbhzHUh0pYMGq3tQhojlqQN/V1NSpiU7tAqz/Op2OdCAxJSYhJZdPg6/vVaeJZXeie9ouE7te93dPxcIeQi3cYX,iv:wV0K+Gw2AweZOzYx/hr7kE98DWGJCZtjj04XX/W2Qj0=,tag:ktaIKwKKYm/rkslNF2rRJQ==,type:str]
    MONGODB_DB: ENC[AES256_GCM,data:HtmIOgCI25ucfHJU,iv:kitrU5nfVzeeGxAppoxJXrk277NqVP5CgyVUVdc8tUs=,tag:uEr6Q5aERoFHrAA4QTBf7w==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:DJZCdn73XMehSlHWaDW03rmL/3rpu5JZQxpTJr7AP2XTeNeRbwynVwm385CjMQXM3lHvM65P05BKbw19VtM3vxK13IZpt9S/YA==,iv:PYMB/x5lWCXGfvO7I6EB/9biOSWSpKdGgF931ySFGdI=,tag:PDRWgAS+SQHx9BETx/gm1w==,type:str]
    CARETAKER_SECRET: ENC[AES256_GCM,data:AejcEEktNGzwlQLqO/OIwA0ZIajT3uvUvNuXwEN1fLg6Q8Z8MuJxYCQ6EFV+l4nChSh4P0L7OeFNORxXr6guhQ==,iv:vUEnUiX/xqs/iFZGViQF5pF0bblIop4L+P5X+7gKqew=,tag:Be5kB1OOS5cYPGmb0g9BBg==,type:str]
    VAPID_PUBLIC_KEY: ENC[AES256_GCM,data:QjuTbKAA5nEQE0wy87SOYeWtB1MaMcA5CWpPdPqrKJ/C1hxvAatyB8UKpkokyHRYf0brjkLY9wyNtKZrS1lhVbZAil8v7KheuO2SFF6nALJLrkLZCu46,iv:otyZMl40R+oo2O7T4ZN+N0N2TDBBKi9l4MgNKwj7HoY=,tag:Q22lb9aodvcxs724gEw1AA==,type:str]
    VAPID_PRIVATE_KEY: ENC[AES256_GCM,data:UVy19yEoVX48KnxbwDQ4677FXj2Su/rICds763a9Y4eINqE6OO7mpBXWJg==,iv:24Rqlc8TZ30nIkaaWv5pCe3dR03rmRM7JusA3Nzteoo=,tag:IZWShIyuOmIrW9jEz+l4dw==,type:str]
    VAPID_SUBJECT: ENC[AES256_GCM,data:V233xNugnkC/S7+JIU2rBPhUtqO/T2pgofP2,iv:i4BTCOl0vKZiSZgrAtPlF1t6tlJtFFLzePyL0wh/ZHQ=,tag:iXe12ufpOvC4jrG58qiSRw==,type:str]
    PET_TIMEZONE: ENC[AES256_GCM,data:DWEtm74nNIv6RRb+iz7f,iv:tpJEOvxSQlXwde4LdjVD4OYmkZhTPLFUccrDjZ71Kxc=,tag:GwYeAQFBQUplKrTySGNBHQ==,type:str]
    NEXT_TELEMETRY_DISABLED: ENC[AES256_GCM,data:Aw==,iv:1IMO71MGptcQScjVjwHZIzQgRkHGoCSl1mQ2uP/KofE=,tag:zuyv/lyiZo8e3K/bepGUtA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBcWI4aVlM
            WDVUSVJ2Skg5cmw4NUdOOGdlVTFKeVNyUElDVnl0TzJCdDFjagpBa2Rnd1NHSlpW
            MjUvUERZd2JjNlp4WEpvYnJoWkt3YUxXcFJzVTVSSzRzCi0tLSBYWW15SmRBOVJE
            MnU3UzNteGwvSzA4d1REbWVzaXRleE94ZnBKSUxHZFBzCgtXYVBQj3+N/PwmB+qN
            Mw87W7bAfgpiOHZZOktrNRifTJlr9TCzDBNl95P05aIgTn3tC/k3NIvNz+rIV/ze
            Gbc=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYVlrQUZiVWFJektHbDIv
            K0xmYk44ZXpoOXB1dm55N0tBbGVOQklJaFJrCm0reE83UTl0a1Fyc2tVemJXOTgw
            UFM2emNGUG9aSXI5Tk5TTW9abWszek0KLS0tIEJqNzh0UjJiVnBPRzNFRDR5KzY3
            NEZUTnZnaWhkZW5ON3VNdHJyRFFXTzQKxbbpdH8cCk5jtbHu4AL75OWHgyjXu5OO
            wubfKzGM2EI8m4zqfCE0H8AcmWBrHgMYCTzq+NdQMgay+pUEpEqXiQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T17:49:38Z"
    mac: ENC[AES256_GCM,data:DXbPVjSH6PSSqsaz6apN1N6R+F7rMn3/3NQ/RzXQh9E7rt1dzeLtpx68L4LraoRhF08GVhaktCfO9Blon7qZOo9GrPxNi6GVhdyU0xNgxc9z3ju0t1w24pEKgFFnXFycVoIlAE447lmzqXgrM8nSOL6/wQttGk03t1EkcBE72dQ=,iv:dw/oQceb7a0vHSj12u2au8QNP2rVTIost1NB10VefMA=,tag:LS9CoFGlj+GHLsgX4b1SaQ==,type:str]
    version: 3.13.3
