apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media
  namespace: jellyfin
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: nfs-media
  volumeName: jellyfin-media-dxp6800
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: iscsi-persistent-fs6712x
  resources:
    requests:
      storage: 64Gi
