apiVersion: v1
kind: Namespace
metadata:
  name: cerbos
  labels:
    name: cerbos
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline