apiVersion: v1
kind: Secret
metadata:
    name: tailscale-authkey
    namespace: tailscale
type: Opaque
stringData:
    authkey: ENC[AES256_GCM,data:ot1o9UmThL0oBMUv/DQcgqnizeFIBwlgyx7OvPINpvtSbNU0cEJLovHYVeNYl/pYkw8k4gEvjYAbFOi3tRfT5MZtqzw4dc1mtzGlkQlev3p4mmUV0AF3NQ==,iv:fFnJjfUJ91+BS6EdsXDkoQOJKWVcdr4LdcIVBhX58b4=,tag:6MYMhK1roZHk1l0Z4n7+pg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBbEFrelVL
            TE5iMHZmTGorbHBrdThmQU9mUG5UYmxDQ095aVF4SVQwVGhUdgpsU1J1bDFaMmox
            bHRLWUVsU1loK1U5WGd4WHZqZllOa0FqeE9vTXhrMjI4Ci0tLSBJcW1WSS84OXNQ
            bENhNkJOeWs5OWdCRFl3Q3hhaVlEWFQxaHRNSlkxeXo0Cgh4p3+9NkNYPGucF9/Z
            sEtrtMTc8hPWb76AHXMiLzRwBdo9BPE30V76bxdyZ1TyO72HgLDZlD4agB3BxSZ4
            akw=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUEpuS0hnSkhXTlhxWXMz
            WjYyQ0NJQjlpbTZOcW9nVGorSG4wSERwcVZZCmtNMmtaSTZoZ2tlYXd5SnRzU1lh
            NkJMM1RremRRUy90TnQzS2hHRkNtZUUKLS0tIHhraWIxekF2cUlMc1pHby9DNGdt
            bzRreGZ3VWlVN2hFaVBQM2c5OU55Q3MK8GGuCGHynHdT/ntQ9dtX8hoqxNH0Oy0v
            6nKW0ZioLhdY6wSjVA9idK29GTU1rspFuq9LKUvKFoCeyhj6J8qpaQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T00:13:33Z"
    mac: ENC[AES256_GCM,data:ynVhthz0+2HKHuCSat2eI6u5+6dStRPy5xODWtodx/YR9oi4lJvtQTGZY4TEtoyuDGAju8JapRUb01rcXtUTfUT117N4UiI2eudO0oBkSWPdf1XgxVidh69eoqj936ilBuQamHnJUkxjokMkkGv8Jdt3UpPDUE9WNG4G1tEWWPk=,iv:dNF3brUP3BgCSgI8UcHBI9S30jTnSV/AsPCt3zeJqO0=,tag:/pDY5mSlrNWedXQoJhXChA==,type:str]
    version: 3.13.1
