apiVersion: v1
kind: Secret
metadata:
    name: tailscale-authkey
    namespace: tailscale
type: Opaque
stringData:
    authkey: ENC[AES256_GCM,data:z3b9Bq/3SW7sS3uKQXa4E1hqh3hfD1mEJhXs3R6m8O9OJaQaMaWNfmNEpzNCGrmtulHOlb5hSuKhJ9DX3+NBjjFLLzhnq3zz1Q572oGFXK+81/NBUytXLw==,iv:tYe0ndTa2SSHoi46IUNfvloESixCZOeBiCYhNf8gwX8=,tag:kMinB9xExrfIydTPvIs/aQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBN0k2ZFNV
            WHVqek56K3lJc01LTWUycENIOUI3WlFJUDJsNjFLS0IweWNNTwpwSFN5eWNyeU1C
            R0tvd3VQSW9LYlRyZCsxOGdhcEZid2x3clM0RjhYcTFvCi0tLSBLVXpmdG9POStH
            cER2a2FhL1JBL21wa1ZJNWdJVXZPcXV1ckRRbGY5VThrCpdXNvxv1QOhjzyE+M7H
            /ABMOJMer/19Ynm8UbMlhkh6nq6cU8cZk3EFOC4Z3c6PqIF9K0NwmMEqUL3Gzc63
            amc=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtWGlpcjlWY1A4REw2L0p1
            bmpzRXRFTG9STHVhcEJacTA5ZTR2U0Q0Z3dzCnEvWWVvYlYySUFTUktxSjBBREJW
            LzJVY01JMnJvNGEzbDFXU0UwUjJMVkkKLS0tIFhDb0ZpTDMzMVJoK29hcDdUa3B4
            dnI0dHlaV0dLUFZuQkxMc1NrWnZUYWMKlhXGilbC7A4Ib1db2SYoRRHgzbdkRGS3
            Xe0zfean2cEXt1VMzJvwuQQsPzih5DQQIflNDdC9oiv4X4nFWxqILA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T04:22:48Z"
    mac: ENC[AES256_GCM,data:2Z87d8ZX4MCBS9NVY7zj59IKtJav9KJZVyl3dqYrDduidwrNfPubTSlDJDnlB1nYVnFjGXLbDgv1T3iYge2G/8bxThDCNW3wQTPEeSuVG/r2Equ2GZWfnIPuUgLvZ7Egg4vCFpvgphdLmA7SxD6ObjDa/jnCbeLp0UsnTcdnB3A=,iv:WUJD4Jfd6GmEQX6NusolCsz0IDHB7RDlPdmvHdv83s4=,tag:OhNU90Tye7JsLlSWJHekLg==,type:str]
    version: 3.13.1
