apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openclaw
  namespace: openclaw
spec:
  serviceName: openclaw
  replicas: 1
  selector:
    matchLabels:
      app: openclaw
  template:
    metadata:
      labels:
        app: openclaw
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - fluxeon
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: copy-config
        image: busybox:1.36
        command: ['sh', '-c', 'cp /config-secret/openclaw.json /config/openclaw.json && chown 1000:1000 /config/openclaw.json']
        volumeMounts:
        - name: config-secret
          mountPath: /config-secret
        - name: config
          mountPath: /config
      containers:
      - name: openclaw
        image: ghcr.io/openclaw/openclaw:main
        imagePullPolicy: Always
        command: ["node"]
        args:
        - dist/index.js
        - gateway
        - --port
        - "18791"
        - --verbose
        - --allow-unconfigured
        ports:
        - name: http
          containerPort: 18791
          protocol: TCP
        envFrom:
        - secretRef:
            name: openclaw-secret
        env:
        - name: TZ
          value: "America/Chicago"
        - name: NODE_ENV
          value: "production"
        volumeMounts:
        - name: config
          mountPath: /home/node/.openclaw
        - name: workspace
          mountPath: /home/node/clawd
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 4Gi
        livenessProbe:
          exec:
            command:
            - wget
            - --spider
            - -q
            - http://127.0.0.1:18791/
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - wget
            - --spider
            - -q
            - http://127.0.0.1:18791/
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: config-secret
        secret:
          secretName: openclaw-secret
          items:
          - key: openclaw.json
            path: openclaw.json
      - name: config
        emptyDir: {}
      - name: workspace
        persistentVolumeClaim:
          claimName: openclaw-workspace
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: belugabot
  namespace: openclaw
spec:
  serviceName: belugabot
  replicas: 1
  selector:
    matchLabels:
      app: belugabot
  template:
    metadata:
      labels:
        app: belugabot
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - fluxeon
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: copy-config
        image: busybox:1.36
        command: ['sh', '-c', 'cp /config-secret/openclaw.json /config/openclaw.json && chown 1000:1000 /config/openclaw.json']
        volumeMounts:
        - name: config-secret
          mountPath: /config-secret
        - name: config
          mountPath: /config
      containers:
      - name: belugabot
        image: ghcr.io/openclaw/openclaw:main
        imagePullPolicy: Always
        command: ["node"]
        args:
        - dist/index.js
        - gateway
        - --port
        - "18792"
        - --verbose
        - --allow-unconfigured
        ports:
        - name: http
          containerPort: 18792
          protocol: TCP
        envFrom:
        - secretRef:
            name: belugabot-secret
        env:
        - name: TZ
          value: "America/Chicago"
        - name: NODE_ENV
          value: "production"
        volumeMounts:
        - name: config
          mountPath: /home/node/.openclaw
        - name: workspace
          mountPath: /home/node/clawd
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 4Gi
        livenessProbe:
          exec:
            command:
            - wget
            - --spider
            - -q
            - http://127.0.0.1:18792/
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - wget
            - --spider
            - -q
            - http://127.0.0.1:18792/
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: config-secret
        secret:
          secretName: belugabot-secret
          items:
          - key: openclaw.json
            path: openclaw.json
      - name: config
        emptyDir: {}
      - name: workspace
        persistentVolumeClaim:
          claimName: belugabot-workspace
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
