apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
    namespace: minio
type: Opaque
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:VpSEeh3I94aA,iv:rSYS8WU7oJoTy3fNFCRH1neEbUCa3PuEhsGatlM3u0I=,tag:+87bsjVduBWfvjMN0wIkzA==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:m2oFjm+kxHjkVJgY92OInyZzj6w378/Q9la9jZIng9cHIUPHru2Hk14ffik=,iv:k84B6bgCTlPErdTEwMpuUOwNVbDEaucc1uXuUBGO+a4=,tag:kB6OMRJjOty2dFNJj5P5qA==,type:str]
sops:
    age:
        - recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBdjM5cENo
            b3kyK3orc1h2WWxHcDNQUmw3dWF4KzluRWhwK3djY0luc3hHcwp0MFRrWktEN3Jy
            S3BTYkMzWWgxYk9qM2xaOFpITXNHQlhkYnlXM1UyK05jCi0tLSBXOUJKRDJKTFFY
            T0NnekRkQXl2K04yNFdoTkxBbm5IUnBXV2tBeE9jZ1hRCiAii2jn9uj5ZJocvgBY
            CXNIG0eVqKJm56IhNwjJ0V61Nad+T/TWPrtByg9qp8ZU1XMxLR+gbvXv+FFYvbhT
            AHk=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKT1ZldVlSVlBvUDM3TzMy
            TTU1MktpakxEUDJBTndITWZXSDRGM2dyQVRrClR3bmYxTXc2alRrc1JvM21WZ0dO
            Q01GaVJ6YXBCVHRhSGliWEQ4WlM2MlUKLS0tIHpaM3p1dWFyMHI1NnZNZ01DQXpx
            eTVaY2hlaXdlUnhKd3JiRW1Zb2V5ZVUKamxrcSWEO/Z0If6n8LAsK+F4Ow6Nf4bQ
            BXAgEwjkvE+sS2EvJEPx/R8hCNZVz3RyAzzcaZ7rAnitA46gBuk2Yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T01:35:08Z"
    mac: ENC[AES256_GCM,data:3iKm5Xk20mxrmKeKR3EqxeI0yv8dGHusTLPuHC7N8uKzJlWgOH9Zz+rGEzB9pP5bVINqKgSU1AfSJmfb6DAW4lnK47JSYriexiPkmyuVDm8qMYrFq++ZTCnbG1+ONyG1PR0wKx9R0nRkG9Zq9TcDTTErQLra0mhed2kF+h+P2nc=,iv:Axl5MO50RzMkNdkU3hw2FanKdkZxHs7R1lvX12ZQ1HM=,tag:dtZatLHbT3xUTexAztbToQ==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsZones)$
    version: 3.11.0
