apiVersion: v1
kind: Secret
metadata:
    name: gotify-admin
    namespace: gotify
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:iTeJs/XyfsJJ,iv:Ix9NrtYUNHuZtpmMRzSi4cS/8ffi0nIUotl9medKsB0=,tag:GuGtnQEdtQxbA4pbbF6Oxg==,type:str]
    password: ENC[AES256_GCM,data:7ETf24XmpqPZcAdwPwePZfFa2TBLb3nwaPEUvtg=,iv:pSkY8FGV63Llm2R/sgBTAz9ByzAnGHMJLa5Y+/Ej058=,tag:JLhqEpGz5aRfVqI1+4LoEA==,type:str]
sops:
    age:
        - recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBNWdUeDY0
            c3Vxb1ZCWnY0QThGM0taOVV5WENZMDVzOE1kTUVTQy9xWGgwdwphUGhteWtKL3Y2
            aVJNYnAyVitkaU9FRmM2cERCajFxR2lEWnBJVk9TNlF3Ci0tLSBHRHFnV0lEeXBZ
            V200am9OdkZ5UHEvL2pIUVJ3QU40WjdBTkdKZ09xazNvCixDy2Mlff/x8RHIow0Z
            V+OshI5FSQXqMgdUc6VfjiBw90meoo94FDDUKwBfhXMjHpeZh6/9/hH8a0E+JgR6
            fJQ=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxVmpERXoyM3BXTHFEQ1JC
            VnRPcUNPZ1FzUWxqaHRIUDNveUR1amo5V2lZCnZJUHFHR21QZVIxMjJScGNSNjc3
            QXB2WkxybDNSVmtuam53Q1RRaVEzSWcKLS0tIHcyUnp2Tll0V3hVZzVBTUR1dDEr
            YnJ3MzQ5OGpTNXdvY1ArbWh6L3h1SU0Kn8NXlX3EvmiCx8pyKXNRCF3/FRIariaS
            onoq/XMwtslcsC3G4xIyecc4v3JICEA/vPbea5o7Q1mn2458C16eFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T12:32:41Z"
    mac: ENC[AES256_GCM,data:WmYiuFsjLNH+C0IEVBasIyfp1Xd6PDKU6BvHl/dqdC3IWOGK8pJFhND2JPM/yFcFKOtbHrZyvpJrjxYseZoVX0EbejDxhmaplkeiWKF9KkV+jtLn19RofPq4t93kZkgUWpxMENekFXqitQurBg6tf8Ds13B+TpbA3V6wjo6IwnQ=,iv:cbKa0zLRDx3n54Hp4NSv2lBwCLzMPItPT0aif1kg4uk=,tag:5V5Gvdox9K+7j6qB7mNJZQ==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsZones)$
    version: 3.11.0
