apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: postgres
  namespace: postgres
spec:
  endpointSelector:
    matchLabels:
      app: postgres
  ingress:
    - fromEntities: [world, remote-node, health]
      toPorts:
        - ports: [{ port: "5432", protocol: TCP }]
    - fromEndpoints:
        - matchLabels:
            app: authentik
            k8s:io.kubernetes.pod.namespace: authentik
      toPorts:
        - ports: [{ port: "5432", protocol: TCP }]
