apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: postgres
  namespace: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  podMetricsEndpoints:
    - port: metrics
