apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emby-media
  namespace: emby
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: nfs-media
  volumeName: emby-media-dxp6800
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emby-config
  namespace: emby
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: iscsi-persistent-fs6712x
  resources:
    requests:
      storage: 64Gi
