apiVersion: v1
kind: Service
metadata:
  name: emby
  namespace: emby
  annotations:
    lbipam.cilium.io/ips: "192.168.1.122"
spec:
  type: LoadBalancer
  selector:
    app: emby
  ports:
    - name: http
      port: 8096
      protocol: TCP
    - name: https
      port: 8920
      protocol: TCP
    - name: discovery
      port: 7359
      protocol: UDP
    - name: dlna
      port: 1900
      protocol: UDP
