apiVersion: v1
kind: Secret
metadata:
    name: sera-secret
    namespace: sera
type: Opaque
stringData:
    PORT: ENC[AES256_GCM,data:QCI90Q==,iv:JL8B9yhqtRLd2jKnqoo4BMNCSdDJbsY8LAlirHm1sVw=,tag:H9+64EJtZJI+3Z3GnpzuHA==,type:str]
    CORS_ORIGIN: ENC[AES256_GCM,data:CR+hMaXGGJzjOQW9EVF3jefHJsp4jtvMSII=,iv:hq+W0aCAGMqb+9Z4ZdG2k6IXo2h7B+3/E+LKHDfV6fY=,tag:yX5xuJcUrOFRMH0pvFTK2A==,type:str]
    AUTH_SECRET: ENC[AES256_GCM,data:mSDSBVILnBrdsuRtWIEL5Wk84WVLozFe6owRRdSI53ELibbzidaKnQCJG0M=,iv:rwbKm/KbJU7Awd5O6fXUA+keExVCgc6j9HSq9mHGYZM=,tag:cmw5bbs8tcYgfottlkLnnQ==,type:str]
    AUTHENTIK_ISSUER: ENC[AES256_GCM,data:Ze6hpE3EODxgSbMlF2kUMF40cw8QY7mnD13UAscNh0lfmYRbREk5guuaFwWixw==,iv:amU5PuY2XHufSC+ehIjzIOT5cjEb+Bvp2w97+HzRA/I=,tag:+9LatwJxHVsK9UfmuBsL4g==,type:str]
    AUTHENTIK_CLIENT_ID: ENC[AES256_GCM,data:kjlxG5I+izgkwVUqqpXh+3R8PaDN08EErFyDAt/SLMKSuRSioMqx6A==,iv:Z9LR7cADou03/5EeLME0UWdN7EbwNYMSn02wKTU9snE=,tag:rLBgKe3VtxarwT2Aq+bMcQ==,type:str]
    MONGODB_URI: ENC[AES256_GCM,data:eBfMZ4ojAU4D1HvS+FYgkgTtdWJOwHojAXmuVsteMvxs4QJaeGRYnUwWxcG7EnTGDAIYu+h5YaNdZdbEak1UyRrsxwSr+LJOHmBhqudaP+/+ReaQTu8V+7y5grAEV4OKdKgg9dBnSp54LFbN+1OF7x057cnQHijv,iv:I66ypj8Xn89bcyp8ucyQcrE9hK1FdZ+B1kwvpAbcJ0s=,tag:LkUIaDFSLAvu3990Zyxcrg==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:2o7xUKlsJONPGvmlhe+r1oGf6MZxKNaCRHbTQvVnjwZemRcueww6IPcTW3hAG+Hh+j7fIQBh5140v7EEYgoI2jykSXccIUq7/g==,iv:mSm2y9Y4MWeCyo1BwbkZg1SQ+kY8FbpzaFJUy8VKAdU=,tag:c/mnSihBV7wxKBx6WqZQtw==,type:str]
    PRIMARY_MODEL: ENC[AES256_GCM,data:4eCOuWMzdIWhB7UN2820uUw0Z8q4EdXVJ5D8,iv:xD8etrXneyMokanJwW3ThdSlKPNNG2mTJpZdAhugnC4=,tag:I4nicO+AoZRqLZZNVElhDg==,type:str]
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:xFfqGwC0A5IIy46K3dhnZAZPYCxFjiaH4l+ZzXF5j63W6QiGRwxkk2A6jEEgyXsLbsqSBFTUCWR4GDJy/46xKFOlAkpjYEFDqcVu9QzEnpkCTBFDMyVAAPuz5ARStD6LOD2rc49qBUAMzaJo,iv:3CJphQUk/OObhwr8itiQGKMr340zyfQ04xeOwfdFK20=,tag:K17KjzBc8jVnH0hKiYyzNA==,type:str]
    ANTHROPIC_THINKING_ENABLED: ENC[AES256_GCM,data:jH6wKQ==,iv:vt+SopBCQtpp9p89Wf1LODUNirCrN26MUj/NVW6NLkw=,tag:3Ts978tOf7EvDV4CmhovqQ==,type:str]
    ANTHROPIC_THINKING_BUDGET: ENC[AES256_GCM,data:pT5P4sw=,iv:bt6T9BKy/ulrpyuRB/3Y5phMlgUnpA1rBFTL2v3L438=,tag:vjkj6EIWVAMeqMOjZPMjPg==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:jw5CyRBcnyz0+Wr5C/jpsATNMWjSegXHg9weba5XnnGeW5iahwba6XzbheuLXwYd0O0UDdJBPUXGBsLl9TOVfqI14Cg+5ddmsbS9LtDeMFvmGJeTVqbAXyCPj2MnplpA7Wk2izVU2FYAPQ7tAJhH6BUHC7ebVy54G7ihOqHkesInUjDLzue0zG+bfVyCmg5R6+OeNe7rQX+Jvg8G5neTwc9VNuU=,iv:OtZNgQ99MZ/ynrFFSWQ8fT+OSnvO3lc9DI7sj+uGumo=,tag:Log65h3E5LGaNTSQ7j9DMg==,type:str]
    OPENAI_EMBEDDING_MODEL: ENC[AES256_GCM,data:Ju6pL5WWEIVzct4rM/eIOavhFlioGQ==,iv:DJrmRYSU3LzqHtLipWYwnxVjTdfLoV6ZqZjkB4OV9co=,tag:ymKbSaHqJRBnk34Lx8K0/g==,type:str]
    QDRANT_URL: ENC[AES256_GCM,data:p2U4miCYt0IGcxkySMDLzXDNuuqrO94YFzbHz3o8RIBu7tNocAoxX9IAEQ==,iv:RBMjSugDucS7CvskMCjOCHzWn5d/Mzyqi5IRmVkQUYE=,tag:vNJBO8WcpJam9VxmkWu5Yw==,type:str]
    QDRANT_API_KEY: ENC[AES256_GCM,data:k4EMNI+GnaPzPNTRdd1/8Rk6mH1SnxmH3kIOmbHd6Z+tzCBCqZEEnrSz569lSUjAVQ4AljZABr8J3ScmWvxAwQ==,iv:AY4iU8x8fWkzsv93ynfRbzExG3HDaP0x+7JlHgiSgis=,tag:viYu/RrXTCAIqOeoGwaWjQ==,type:str]
    BRAVE_SEARCH_API_KEY: ENC[AES256_GCM,data:lH4kl3oUNDTj6rnf9nJH5PD7xx5FBRz0gKl5aWNGzw==,iv:SNkJiHOulNR2O45YgaUgw9WpPyrF6MF/vCoPh4r0oOQ=,tag:guuF8rvWRjtQ8ie4uE7r/w==,type:str]
    VLLM_URL: ENC[AES256_GCM,data:YtE6k0loU6DbHxX5M1zUbKlsATdCRUtsr2Mm2O8LUxi769AUHbI+AvYccQ==,iv:Dg+a1Pmg20/yodwnAzKy90DKlq3dVfeYb55YI17ZYDA=,tag:wiXaYy0YeW1G4TDgAxiZtQ==,type:str]
    ENABLE_SHELL_TOOL: ENC[AES256_GCM,data:7IW7EQ==,iv:wbKoRkOoYq/UVaqhd8StybO99faKQaDvl9f0fYV+JM8=,tag:7oBr9JhWiUXg0yd2z2NiPw==,type:str]
    GITHUB_PAT: ENC[AES256_GCM,data:Wi+2GR18A2ZDWwQ1evBhu03aO4sVRNzOY1G+zCqnlNATp1nYXQY8E8KmMVHYfqcgvIfhFwAhPYk3RjR4NTanFO/7PXgOxk37M6PwspLTS9/dCeX7U22rG5HclVe2,iv:zHANf/D6zYqJtkgTE0XP4IfK1CZP2OGIHEMUdmzvg6k=,tag:kjSUfrx4KLqR6cQf598FDQ==,type:str]
    GITHUB_PROMPTS_REPO: ENC[AES256_GCM,data:KM7jH3DYdNt6/7BQTWoZnMY=,iv:nb+JPU4CUfrfw66QIRAkNBxmrKrwLRAfLKpazwqQaRw=,tag:F7pwhHhGPmS+auFBpXze3A==,type:str]
    GITHUB_SKILLS_REPO: ENC[AES256_GCM,data:LaOg0s6TXz88HG6qDIheqQ==,iv:o4CALaRA6v4uiNsWDIMWvjptEuqcnhscBv9piME+HL4=,tag:5gyHZ4wqZ8PRGg820tgWwQ==,type:str]
    OBJECT_STORAGE_ENDPOINT: ENC[AES256_GCM,data:jl1Qrt3l6s41f3nmEDyN4rIm5FqZ,iv:dXdOhfk72vMM1E9354r4vLRHQ4uugaW7Qw4s74gFLSw=,tag:1XsvxG4DNq9qKyflHvQ9mw==,type:str]
    OBJECT_STORAGE_BUCKET: ENC[AES256_GCM,data:CKI7tA==,iv:GPcGFHOsB+mI43Sgw79g/7Wsbs9/vGdWzsEKMpYA0MU=,tag:EddW5yvPqBl6fjwqKbs+rA==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:XL0JenYs9Y9t,iv:d6wtjQucx6ieB2PddwJ1dsyhWkZunGyZrOt3VLjTR5U=,tag:ddXvHjzC1ievyYWjK+o8gA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:0dAjJoDOF5tO,iv:5f3tGI21d+00GF705yFaE0PxBatvL0eEbmBcJOfCUjo=,tag:v9GBaRWRmUC7tjgZU5Pw4Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:x6+1HMD5c8Gb8DnzQsnsqnF9u9z42K7YuBNFrj1xiFZGYigO3MwoE7v0kws=,iv:vRr3U0W3cUoDhHIa/j8JkA/UPxLqtE/0kfjU0hJ3T7g=,tag:VdlL/7rTa8ayQ2H7MxqfuA==,type:str]
    WEBHOOK_API_KEY: ENC[AES256_GCM,data:e4/wWO+b4yntXjqVHj4+1aULbF2sKNTJTu4N5rav4THR54qvZVtbjg0qdg==,iv:na5yuVJzpWx3L7b9UzG/rSHJVFopJoW+rM/9dO2xS/k=,tag:0smFQejyXzHblwWR2/dCAQ==,type:str]
sops:
    age:
        - recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBb1NmalJH
            S3ZLRUVnK0U0TUJDLzk2Zk9YclJMeWp6U0I0bHdzN0NiZ0xsQgoxQSsxNTM5LzJ3
            UHJqUXNiTXcxOFdSRUxqL1hhaldoVFZlSk1FbW9GR2VRCi0tLSBBM0ZIYWxrMzRi
            cHE2US9BR3p0OXhERkt5cVJuVmJaNUdraExyaW9Mem5RCn2G0kVrsnjVs+uSCF2n
            bSI2ILNBBLNPuFYq2+jTAOcQmCagMSOnHpCzVs07KvEfpNj50ASFT6oY1p1d0P81
            kPU=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoazNsUDVMNVRrOUUremdU
            VzdFdlRvMnVVZHlleDhFMlJtTHY1QW5OSEJ3ClRsOHExR1Nwd2NJaFZsZXNuSHFj
            SXV4Q3lONWpGd0VrU2V0SE5JVU9rdVEKLS0tIGMzODlDcVRBL0I2MHU5REZZaWFM
            SzBRVzZ4MTBNMkZMNEVwSzRYN3R3Q0EK5bhsZ58mjSpjOcIbHuPTtUoUCTmVIcHs
            k8IfbDrVf764hH2ziXoBVzW2bVRiLStoH6fCtpZs5USlCXtX5Vi1/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T08:49:44Z"
    mac: ENC[AES256_GCM,data:lT/qLlv/LqRoVM+sd6goxEDLxvnzSq1zHGQ08OeeE4OMRV9Y+IAv+ShclkbXFKb513AxGy4OizjzJGtMCE3cXVpBY/8/lTcq6f0Y0PAKkt3B0NSiTBHtthgMwIoET2M2wNjtqtVi2fCglFkfxtNtzsInuJnZx8T3yq9LjMAt1Zs=,iv:wq3xuDcXxEWgtwd2OoHOES4XoxERV+IDmu6zgeNiNfA=,tag:7Q9if+G/cvSgB0LmRHd20A==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsZones)$
    version: 3.12.2
