apiVersion: v1
kind: Secret
metadata:
    name: sera-secret
    namespace: sera
type: Opaque
stringData:
    PORT: ENC[AES256_GCM,data:QCI90Q==,iv:JL8B9yhqtRLd2jKnqoo4BMNCSdDJbsY8LAlirHm1sVw=,tag:H9+64EJtZJI+3Z3GnpzuHA==,type:str]
    CORS_ORIGIN: ENC[AES256_GCM,data:CR+hMaXGGJzjOQW9EVF3jefHJsp4jtvMSII=,iv:hq+W0aCAGMqb+9Z4ZdG2k6IXo2h7B+3/E+LKHDfV6fY=,tag:yX5xuJcUrOFRMH0pvFTK2A==,type:str]
    AUTH_SECRET: ENC[AES256_GCM,data:mSDSBVILnBrdsuRtWIEL5Wk84WVLozFe6owRRdSI53ELibbzidaKnQCJG0M=,iv:rwbKm/KbJU7Awd5O6fXUA+keExVCgc6j9HSq9mHGYZM=,tag:cmw5bbs8tcYgfottlkLnnQ==,type:str]
    AUTHENTIK_ISSUER: ENC[AES256_GCM,data:Ze6hpE3EODxgSbMlF2kUMF40cw8QY7mnD13UAscNh0lfmYRbREk5guuaFwWixw==,iv:amU5PuY2XHufSC+ehIjzIOT5cjEb+Bvp2w97+HzRA/I=,tag:+9LatwJxHVsK9UfmuBsL4g==,type:str]
    AUTHENTIK_CLIENT_ID: ENC[AES256_GCM,data:kjlxG5I+izgkwVUqqpXh+3R8PaDN08EErFyDAt/SLMKSuRSioMqx6A==,iv:Z9LR7cADou03/5EeLME0UWdN7EbwNYMSn02wKTU9snE=,tag:rLBgKe3VtxarwT2Aq+bMcQ==,type:str]
    COPILOTKIT_RUNTIME_VERSION: ENC[AES256_GCM,data:4X1kcmwc,iv:a0vZHq89C3+zYd0UGzb/jKjz45vds8c2D1nX9qDcQwU=,tag:ECh1IK+BSHcnQ6JB+G+cuQ==,type:str]
    MONGODB_URI: ENC[AES256_GCM,data:IQzT/JCggl1AIBXoVVuAp3+KXxjcZorR4iUHBfWAMi/vGNNuvjDIaQhlDSAILDlkXrGMAt5hH9uom3dM+MJWROjciu/RqFl3x7+gKcfDcGC6EtaM8lzxQdn4baDjQI5YoDtF60T3WYhc2jA2qSX7wJYzdks3schs,iv:gygzdYbjdxz9gf5f3wORjiur92fjlb4ilxISzBIuhMY=,tag:mYHFxK7zwbTyEwNVc52NtA==,type:str]
    ANTHROPIC_MODEL: ENC[AES256_GCM,data:B6kuQIAMnBfbEEOxUIlNYAQ=,iv:uU0I/yLbF8E9zQOncsHMBart0KmVp6daSVEwg9uHi2Q=,tag:IEezzLc8V/asD+nEtzVTQg==,type:str]
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:xFfqGwC0A5IIy46K3dhnZAZPYCxFjiaH4l+ZzXF5j63W6QiGRwxkk2A6jEEgyXsLbsqSBFTUCWR4GDJy/46xKFOlAkpjYEFDqcVu9QzEnpkCTBFDMyVAAPuz5ARStD6LOD2rc49qBUAMzaJo,iv:3CJphQUk/OObhwr8itiQGKMr340zyfQ04xeOwfdFK20=,tag:K17KjzBc8jVnH0hKiYyzNA==,type:str]
    ANTHROPIC_THINKING_ENABLED: ENC[AES256_GCM,data:jH6wKQ==,iv:vt+SopBCQtpp9p89Wf1LODUNirCrN26MUj/NVW6NLkw=,tag:3Ts978tOf7EvDV4CmhovqQ==,type:str]
    ANTHROPIC_THINKING_BUDGET: ENC[AES256_GCM,data:pT5P4sw=,iv:bt6T9BKy/ulrpyuRB/3Y5phMlgUnpA1rBFTL2v3L438=,tag:vjkj6EIWVAMeqMOjZPMjPg==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:jw5CyRBcnyz0+Wr5C/jpsATNMWjSegXHg9weba5XnnGeW5iahwba6XzbheuLXwYd0O0UDdJBPUXGBsLl9TOVfqI14Cg+5ddmsbS9LtDeMFvmGJeTVqbAXyCPj2MnplpA7Wk2izVU2FYAPQ7tAJhH6BUHC7ebVy54G7ihOqHkesInUjDLzue0zG+bfVyCmg5R6+OeNe7rQX+Jvg8G5neTwc9VNuU=,iv:OtZNgQ99MZ/ynrFFSWQ8fT+OSnvO3lc9DI7sj+uGumo=,tag:Log65h3E5LGaNTSQ7j9DMg==,type:str]
    OPENAI_EMBEDDING_MODEL: ENC[AES256_GCM,data:Ju6pL5WWEIVzct4rM/eIOavhFlioGQ==,iv:DJrmRYSU3LzqHtLipWYwnxVjTdfLoV6ZqZjkB4OV9co=,tag:ymKbSaHqJRBnk34Lx8K0/g==,type:str]
    TEMPORAL_ADDRESS: ENC[AES256_GCM,data:wQW3uaMJ6GGOQdETsmZCgiuJcM5GvIrA/HXEJiXNpqKsDt5GzCNIrg==,iv:W7THxhH5RjcOz2dai9Pe6jcku3Nf5CxrOoCDR75Bq3g=,tag:W0hl48xvf2ThEqCxLc7RVQ==,type:str]
    TEMPORAL_TASK_QUEUE: ENC[AES256_GCM,data:dab6QQ==,iv:AchYNrXjOuMIjuBl14Bzfv33Cb2RZ14uWsdTXd6Z+OE=,tag:iI41VcCBW8hXeuPof+Wfpg==,type:str]
sops:
    age:
        - recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBb1NmalJH
            S3ZLRUVnK0U0TUJDLzk2Zk9YclJMeWp6U0I0bHdzN0NiZ0xsQgoxQSsxNTM5LzJ3
            UHJqUXNiTXcxOFdSRUxqL1hhaldoVFZlSk1FbW9GR2VRCi0tLSBBM0ZIYWxrMzRi
            cHE2US9BR3p0OXhERkt5cVJuVmJaNUdraExyaW9Mem5RCn2G0kVrsnjVs+uSCF2n
            bSI2ILNBBLNPuFYq2+jTAOcQmCagMSOnHpCzVs07KvEfpNj50ASFT6oY1p1d0P81
            kPU=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoazNsUDVMNVRrOUUremdU
            VzdFdlRvMnVVZHlleDhFMlJtTHY1QW5OSEJ3ClRsOHExR1Nwd2NJaFZsZXNuSHFj
            SXV4Q3lONWpGd0VrU2V0SE5JVU9rdVEKLS0tIGMzODlDcVRBL0I2MHU5REZZaWFM
            SzBRVzZ4MTBNMkZMNEVwSzRYN3R3Q0EK5bhsZ58mjSpjOcIbHuPTtUoUCTmVIcHs
            k8IfbDrVf764hH2ziXoBVzW2bVRiLStoH6fCtpZs5USlCXtX5Vi1/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-11T06:21:29Z"
    mac: ENC[AES256_GCM,data:9CaKsmtilbjVmb0mMTGKxHTiR6R1WWeCFdEHR5eiipwubLYtea9NY3F3lrd3VH9gPRVTunw23msPAf8m9g6ergC7kRWn/LbzMjM8WUzZ2T3rSRIMV6nedpR1B4yXUt7ZjxpeE162nDEG4+yn4jpoe4kz4ePY0yHmgGMjhqyxEe0=,iv:INbn4MXG9qDarf4RoHnfYL79Su7YWct+41qQNAgbrw4=,tag:GZ2ztA99nmW5liDAOOUJMg==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsZones)$
    version: 3.11.0
