apiVersion: v1
kind: Secret
metadata:
    name: mediaops-secret
    namespace: mediaops
type: Opaque
stringData:
    ARCHIVE_ROOT: ENC[AES256_GCM,data:8hdxvYQSg5KcBXU3bKvcZ150zvdRButDMUM=,iv:1e9fpfCQNQfmtpC2iOzQWJKbH7QN8nbo/OT6FOsltoE=,tag:KPJRWsaPMPi9zIsnqRU3iQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBdWphdzJZ
            QUwyOVJGY08ra1VqVThGczNwdnYyOVlMNWlxYldGTjgrRFhBVwozRnZWSzc2Z05m
            ZUN2Y2Q0VnByeUthK0NuS0F6VFZyVjcvUTIydndOZU5BCi0tLSBmcUJmTkY1ZEEw
            RHVPdHI1UE9FR0RvSnJ5dGRHb3lHbGJXTlJLL24zbHhFCvjqPbUX4591bHo4DRqW
            MKzMWEzgP2m3dAAQY604I/4RzbT9Dq1ipqeYljrE6W+rcZ42BU1q/Z99gfwcc/Sw
            Ono=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bnV4NTNYRzZrNCtCTElU
            dExtdW9DWksrcjZvUy9MRWFNdGc1RDFHNzIwCjJiTHUySThVN0U4WS9YUlFFdjhN
            bXVMKy9UKzNCUFNHcWxCckJTbUlYTE0KLS0tIEJFS1hGT01XTGY1OE9QbWxYWS9u
            ODN0bGZpM1BCdk9XUEhlbTltTDdvb2MKP3XUZMTzxmOmPBiaudTulpgYQqRcJ/Su
            Ps92jglX8KkmOeCw2mzV3t1ZYXptlChjJhmbIj1DvQJn66eu4qeI7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T03:31:04Z"
    mac: ENC[AES256_GCM,data:RslF3PFQxZFYLYyLd5CAb8rINitfZr1e6T1U5IQSEfy7ZZ1lVQVWt20RXhTSkuZcS4DwPLngckyE84/pCApEdDVhoLknXAx2jYHt8WJVRS+FZ+ebCY88FlmY0WSJlaI2RX2IzdQX9aypivf6zK6Rf73oBLYaSe0aRtGQGJIdE90=,iv:VsUjus0BqUUURZ4TOe0H8yFl1vfIx2IvwN/LJn8xKVA=,tag:wDRMp4PiwFtePefckSnHIg==,type:str]
    version: 3.13.3
