apiVersion: v1
kind: Service
metadata:
  name: comfyui-web
  namespace: comfyui
  annotations:
    lbipam.cilium.io/sharing-key: "lan-shared"
    lbipam.cilium.io/sharing-cross-namespace: "*"
    lbipam.cilium.io/ips: "192.168.1.120"
spec:
  type: LoadBalancer
  selector:
    app: comfyui
  ports:
    - name: http
      port: 8188
      protocol: TCP
