apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: makemkv
  namespace: makemkv
spec:
  serviceName: makemkv
  replicas: 4
  selector:
    matchLabels:
      app: makemkv
  template:
    metadata:
      labels:
        app: makemkv
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - fluxeon
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: makemkv
          image: jlesage/makemkv:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          ports:
            - name: web
              protocol: TCP
              containerPort: 5800
            - name: vnc
              protocol: TCP
              containerPort: 5900
          env:
            - name: TZ
              value: "America/Chicago"
            - name: USER_ID
              value: "0"
            - name: GROUP_ID
              value: "0"
            - name: KEEP_APP_RUNNING
              value: "1"
            - name: DISPLAY_WIDTH
              value: "1920"
            - name: DISPLAY_HEIGHT
              value: "1080"
            - name: VNC_PASSWORD
              value: ""
            - name: MAKEMKV_KEY
              valueFrom:
                secretKeyRef:
                  name: makemkv-key
                  key: key
            - name: AUTO_DISC_RIPPER
              value: "0"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: output
              mountPath: /output
            - name: dev
              mountPath: /dev
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "4000m"
          livenessProbe:
            httpGet:
              path: /
              port: 5800
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: 5800
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 3
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: makemkv-config
        - name: output
          persistentVolumeClaim:
            claimName: makemkv-output
        - name: dev
          hostPath:
            path: /dev
            type: Directory
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain

