apiVersion: v1
kind: Secret
metadata:
    name: truenas-chap-secret
    namespace: democratic-csi
type: Opaque
stringData:
    node-db.node.session.auth.authmethod: ENC[AES256_GCM,data:wZ/q2Q==,iv:bE6T1wlIGRKWB/KiocXXNkQYAiyh53WCY4eTSjh3K+8=,tag:OQ2Tbhj5uot6lKM/Vxoeew==,type:str]
    node-db.node.session.auth.username: ENC[AES256_GCM,data:llHO5dVaT447uw==,iv:dhaEEx2Xq0jpd1XG+Ch1FABvgEvMbWSt1ZydvGOffjc=,tag:B0QQNpWNTZmx/9jLjb9ZFQ==,type:str]
    node-db.node.session.auth.password: ENC[AES256_GCM,data:VeqyIhS308XmJccM1W0SPg==,iv:hZmGbB1PiyIDs7FdssOxnE82DyAmGOANaH+yruyqNJ8=,tag:e9KE5ajHhxkAIF3AhO8aIg==,type:str]
sops:
    age:
        - recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBdzl5Uk5X
            djBZejFnd3RRS1pWeHJiRklJRUVmaTMzS0ROcG1CcWZnVFM3awpSNXkrUG9Ockoy
            Ym9WWVB3V0F3bTg2eEE0WFloRmI4ckNkWFFkMUZseEpnCi0tLSBOQ0NHbXpmRHd2
            MGFtaEE0SWFySkV1Rmc1ellPbG94clpRZVFNUStjbHdrClDGlKUsgvIOkugjk4lD
            7mmt546bz6zEuqCbTHtEGFcWyYWvHGPHoA+POzzuFDxmtD6Pa4eagMzCC70hTEAk
            E4U=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17l8gylyteashptf89ql95e4wl80u4py5ahfzmz76v4y8ghst0qzqxg3npr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Y1RpUnZhdjd5cElUZjhV
            T1RCakZtSVZ0T0lETDY5cWV3a0g0MWswd1NjCkNveEdmRGpScjFnY2Ixc204VmpV
            UmV5UFc5QUpoRGlpUFFzdUpEZXpzeXMKLS0tIFdUYlg4eXYxOUlMVG1INW5haVBH
            Zkhva1pKc2Z2Y0R1Q1A0TFRPU2dCc28KY/hCMy0NEJk2I6gcmQ5rwFbhAtoi45+g
            5nHIN2S8R2o4VZ6oWEF34lSFJ95R8fAE+2GPYKFSgbUg6rGyIMUpSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-26T05:34:15Z"
    mac: ENC[AES256_GCM,data:F8T2RE8jmvLnbUko2IYzBDbeuoX8lG/I6KYXz6GQzk4KECTl1XcbG7e8k8SbGvALlrctU77Zqypt7Fp2koszi6flGHCru3GONgf8RXat9CiP6KwXlDpmRkcQ7o1TP5PG3MGRog2C/TQqAlOWfWj4SKDGQd+GTqAU/HLMWHPiJxg=,iv:sTTQrfofwk98UQ/1Y2ieIIlbmHkKTQWcfRqFprX6hTU=,tag:dpP9Q65P/Y565X9/T2PtZw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
