apiVersion: v1
kind: Secret
metadata:
    name: palworld-secret
    namespace: palworld
type: Opaque
stringData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:hw9d5octer/2RrXVO8JX+YmOXoiSxw8h,iv:v+oIttv5zR4PAkiLPicjv00fyFjmpafDg8GbCqO7rlc=,tag:ZJPJO/WUWbA0eK9ijbd44A==,type:str]
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:WdNvg6aU48setJjZJENmyAzeZdG3oXF4Hzb08T5dXnW+5IoSiyx9r9Y6hHHqEruHZCNw0XMfOSybLt/W22dOT3hImKtYMaOx08m/yV2vPKcwVEw0Lw0pb8kbeCZWPYl6CwCsWFsZubqa22mlZ8SP7gNsBsvlp5o1Zhq99A==,iv:FkI8Pq4d+oVfIV7AUnJkhghCZi7wIhCUItJJ8/yDHH4=,tag:lNmIdbFyX01Dpco98OO4KQ==,type:str]
    SERVER_ADDRESS: ENC[AES256_GCM,data:Uv8y2lxnVDChHdmiezs2TA03r2rlvMU=,iv:XQvkZNYsVWngSNY8QcRkH0zmP+DwbWSTzrCCbbw9wr8=,tag:lGaJh4/NaNw6IREZv8fDzw==,type:str]
    GAME_PASSWORD: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBcXNMbThT
            Mnl0QkRNS0ZVRDZnOFM5bUtwWDdhaVliV2xZZlVJaHV0NWhtQgpnRTZwSTdyRFY2
            VnlFRE9FaUE1NmNuU0dTTFJac3kva3M5NExocjl3dXpVCi0tLSBLbzhtZWhtcFp6
            Q3E3dTM1TjVlc0lpaitTU1FJbzRNNXFCRnJUN0ptNGEwCsRkAX2bbdStwhPgMjku
            vhvz/B7RmhTGGry8HPt5WMsfAD4gbxHjryJsTd13OmIY4rOWKlaDnn40PsOmo90a
            U4U=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVUxMYzdYWGpKOU9LNjg1
            MmdyZmtHQ3ZSa0VtalQwYWprWWV2VUIweG1vCjdxVmpDR3E0MXJYTVoxOERPNlMv
            NDRXekpKQjRseWhSVm50Q1ZUYTg1TWcKLS0tIGo5a1FuQW5HcHovNGtwbmpLRmxz
            TyttbWQycEdLbjBXc3dIMjlLV0FKWGMKY5jU8jc15OTXngcNqZW8QWMF0/4kBYk8
            TFJN3W8S1vaZD9qOgO4TNk9KmwAmBDZ8wwyRmhCjVde7cP7pR20KoQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T22:26:33Z"
    mac: ENC[AES256_GCM,data:FJyn9v+L5ADm2ML/NkSteoTk5M2uRKVbv0A0SIsU0IrCJ6r8wcfk5hVSVgOdjFWHEDiStihYOUKRplYavUZLsk0jWtEbYhRl8v4ZKygwe5+laIJ75sgoZ09Q0rraaoQfdWYEUsE4wQ8U5v41FMbeA0Zpi+HzAuB6Z8wDY27Tf98=,iv:A51PehiXT02Jx6puUsBq/T0tjTkJ2AgRPYeEJtGbRDw=,tag:pA86NbgVYJIoTEe6r3hlvA==,type:str]
    version: 3.13.3
