apiVersion: v1
kind: Secret
metadata:
    name: palworld-makoto-secret
    namespace: palworld
type: Opaque
stringData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:KiIpcO0TSvbi9JvQCw35jYV+roiI2DCvMiMcfSLRadU=,iv:konknWG+7wUKS3FkvtVyt/yWaSEKnkKOskshw50RHqs=,tag:xOorwWvSpvt8x4UZKcjytA==,type:str]
    GAME_PASSWORD: ENC[AES256_GCM,data:LtwOk3FI9WbZyYWjj/15my2u9aC1Zj+imwYvHJRv6rk=,iv:vdxM91lFFoAu75VtYLbwKIuu2n/Wbp/lS3nMq0F2tdU=,tag:1eekjwb092vORP1c8TNNew==,type:str]
    DISCORD_WEBHOOK_URL: ""
    SERVER_ADDRESS: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBK2dsKzRR
            eHA2alFlQkhQMlZxRjRMbXk5UDd1cjBGaDZkcVozMFNPSm5xUQovTUV4OTBndWds
            OGJqa2djUlBCVTdkY1lBTTJld2d3V1Y4YWpBZGdwT21vCi0tLSBINkZ4eVhVOEpI
            Q003ejVheHJmUXhPbDUzb2dmOFJyQzh5L3kxZ2c4Q2VrCpeNe/IztTbU1C3dLxWk
            3RpHfzde2YOHIIBRivDkE2Y42an67lYWBuTWLDeANCuBNb6D1/FkoQazpj4S62qy
            fJE=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcjhaZ2treEZpUlFQVjhh
            V2VYZTcwZEFHUzdSS0hKeUk4c0UyZUp3MzJvCmZuOUZYekpiV0lwa005UktYenE2
            ZWV1aUM2S0VnamVjdVFZOElRemExRjQKLS0tICsrZGNhR3FHZkIyN1RNbnZ1dkFo
            VzVKcmZaeUJIZzYrOXl2YUZUaC9wdGsKgbpc5a+cWaRFlnXgPKw9VeMZ+WFy0z/V
            mlcoTGoYsPl2d9NzbxC00CSW7s3UqOLoOf96u0arbRSUyvnDl9EnZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T03:48:17Z"
    mac: ENC[AES256_GCM,data:Eah+9MPj0C59/2kg3qD/Ddc1G+Sho2XyGwTFN9QIblsWdn57dSmFHNrc0xKMsksvNB3um4wTTpg/AC1AdmlA/Lc2FHcR/0sB8KKeSv4bVhVSBvPXuGW0dkIMlPZsDx0sysO7egXJSe6eJpcR/Dj5GwFbTpXjavScaX/ws0WA/GU=,iv:Iy5kwJ8SzgUuBhPWvliYdWsgqvp/7PPIa+Vb+b35a5o=,tag:PZmqsIx3iRqiBoVWYFNgrg==,type:str]
    version: 3.13.3
