apiVersion: v1
kind: Secret
metadata:
    name: palworld-makoto-secret
    namespace: palworld
type: Opaque
stringData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:O+P29QeT8EYoaZhsPWkNkvesj25kz/raris+0Cr0bNo=,iv:+odseO8a9e8TeW1VsIuQAsqZ4L9yc+Aa8avUidE+4Xg=,tag:RWrxwIEAJ5PBx9yM5kjTDg==,type:str]
    GAME_PASSWORD: ""
    DISCORD_WEBHOOK_URL: ""
    SERVER_ADDRESS: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBbXg0dURv
            MDZIUG1DMitDM1ZZcWhodklXUzVNVHYwUG0rYVdPUzZQWnczRgpzQkxKSkI4TStl
            V04xN3RwWlBNOWp5T3B4RGpuSWNQNkVENDdYbFMwL0tjCi0tLSBWWFVOeFZ6dmpy
            a0tmN1NtRnl4RVA3dkRnWE9NdWpPTVJjWXdVV2x3VW00Ch/engfxxevOyjM+IB2u
            AxHNobI3JsHGe321lg72ALGnD9CFjWWE1wVj+R36R3VRCJCLrwT2GxSSY9EiNWw1
            8Mk=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMkIwQTVScjM1bDJwOWkx
            b3FpeEU4NDFxUFdxNW5IU1V2OVNWM2xsT2dNCkROQWlmb3Q5NGdPY2MxbmJKK0FO
            N2dhWllOakZPeklicVpEZ3JJUGpiRTQKLS0tIGF2aEN3dml3bHErQlRxNGVid3hH
            ZzY3UkdnWlRqZ0JDUWVBR0JSdW00YUEKg/q+wV3seNCUUs1L37Re/HKEOY9/a8ef
            orVc9Dih1lzPCuA3BIod1CICZTbF7yl9cbAri2pg5N7KaahZ+FjFxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T04:08:35Z"
    mac: ENC[AES256_GCM,data:3TOjZ9VuMYn/qsO2PiFzLkX01cc9VJ2NqeZV54y0mfGDWRqXUu49eGA6AvykV2IZMBxzzKwFQykcf1mr7JtM1ivhEHG4Hyry6r4jp++gBv11V3303jXyzZ56zITRpsZwNEgd23MaXE2M7T4uYUXg2YNu/JB+/orMnPLRLFk4ejY=,iv:UHyc7hYF5ZjkAeHXeclCrKh85A8NteEcwFqle1ROUUE=,tag:qqrcM5zBxEf3TxC+Vf/hoQ==,type:str]
    version: 3.13.3
