apiVersion: v1
kind: Secret
metadata:
    name: palworld-makoto-secret
    namespace: palworld
type: Opaque
stringData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:xcor4KOodFBajp1HTFMJBqg4gNL9yuKuSEIMvp23cYQ=,iv:bUYZY+VibaZej+pvysgokyf1lXuA+egS8vL4nv1k3Yg=,tag:YNXonrgg5CAvC/5rUMTtxQ==,type:str]
    GAME_PASSWORD: ""
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:Zk8N8dzzeGjQFDY+CPxxciuGzpdM74Uj91XxAvefbm4gDOL9Z57FskfGYFKEHP6JEmmJsiISXzUmOGNrOnZlpA2jY7csxFJdmH7G0dF0D1RH7k5t8X26Zwt0rzvF6lae6ySRaPS761z1V5W5kZu8v2XuhNa3Eet4ikmHcw==,iv:DdZ3dg4HzmneTNKM0Sc2KOD2dptSqkFAmsnk4zaRBz8=,tag:KdPvT9JG+sWoFqZPvBq8Mg==,type:str]
    SERVER_ADDRESS: ENC[AES256_GCM,data:zd0JaTuxh4IPHPiebOzX956ipPYuY5Ummlp0P3UM,iv:zoIbDU8dNN2uUCgCay7noAuqgaJFuHuACmgcKnVOvMw=,tag:tOoMUelERs0yFCEXHQXExw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBNGZHMmFM
            WHlnOXFvcmdzZ0QxOEpmOXRmTWc4WkFaMlJMUTQ0dVhTSWJxTAoreE5LTnFqMWdY
            cXZoZTVxL1g1V0JuTFN1RTJqVHZpNzQzYkhpeWNhMjhvCi0tLSB4ZTlQZ0hVN3ND
            YzhOS291L1pSZ1BXRTJUUTFxOXdVTnFzQVFlb05iMElnCvXvbvkc9YJuYVzEdg/o
            zJwasXGkuJEXMqbHAwrWra4AnrZjxBSHtOZOYUYY/2zfJx6Ns9DNWyB3oPqf6aXo
            G8o=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKdkxUR1VjYXFCYjdqeWNS
            WkRJVzFuVHdQUm5rbUV1VkxZRVpOOEhNbXpzCjBML0p3Qm84ZktrRnpqbFhtN3Ni
            Tys5WEtYWnVEOVV1cFZwWnIvY0h5RWcKLS0tIGNhaXVYMzdCY3ljQW1RME16cmMz
            Szl2S2V2c2NrcUNmajVWZmJJNkgxbHMKWJw6vZbCLPafIrRLw+KXuMk8jMuuVqqt
            3wqCuEi3SJmJDAYhRAwXQi7gETq74rybtjtRcD91Y3nOXfA8kM5cFA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T04:29:36Z"
    mac: ENC[AES256_GCM,data:VpAHamr+1+XQPDxEvjZKFjly6iTYKcH4v4Ftp2TnJzpkhoAXVYj13KOr8giRU4x/UaRjokT0PpBVzFDuZ7p8LlUwjXczAt9N0tNIMzAXF6GaO74rwpStI+RmL9vR9NNFtqaCD9j48SlnvL9gZffXUa8Wf7cXgAEsoV8qiywShJg=,iv:F16CXibpnJek+C2HrxPjL5XM4naN7CnfiOF1OX7/xlw=,tag:9fOH5deOWGsA259Dz9DRGg==,type:str]
    version: 3.13.3
