apiVersion: v1
kind: Secret
metadata:
    name: palworld-secret
    namespace: palworld
type: Opaque
stringData:
    SERVER_PASSWORD: ENC[AES256_GCM,data:46ZhnPEk,iv:jaoDWmqAhpT82ONKEMARF5tKE70FDVHDS91V76FVkDM=,tag:tVrGhVLQl75PrT7EYXv/kQ==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:0egiAN/yY+NsAurYEBC1U08IWMUi380i,iv:BWqLAUVQJT7fjIcS7YwRlsaqC1EjoCmviCZt63/bXVY=,tag:zgAgvUn2ifd8A7iEUxBCDg==,type:str]
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:8ayDcY62Yd68vWlHVwd4ybWRpFiTqlQQ2FLsG1ZfS1HmwTHuBs7ncwzddmPb54N9AVsJDcs05sumdorLRbmh91/uz+AP3vE0i0piHLkFZpw4ZwB3OLMJ7jSuBvuk4AM2ulBDwZhebC+7W88ELf5gHMn0UlLM8XjnwQ==,iv:jlfDMwcEy3noHNVETrTh1yG35nKvquXX/wQVDq9j7lY=,tag:+Gi0ZC2gck0jWpDtwB7cnw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBekZvK0Q5
            UVBPWHBsVDN5UURRQXgxK1lFdU1pdW9mekxlWmozc0EycEZxRAplT2xHZDJXdnJr
            d242SjhBWmJKenFlOHZzVkhzZWNPdEUxMUtwVDE0T2JJCi0tLSAzZ0ZNaVB0K29t
            aDd2YUtDT0xXcVFxTUE3ME9vaC92NmxNRjNXUkRzWXdrCtJeERI+bVp1oKsrFHDm
            +XhZFSl+D3vYcm98WZw/Rm+U/ZwCyINNi+dQjutoPSqduS2VwPsc60FuJ38Ffa56
            a+0=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMWtpYnpCZUZuN3YwWTNw
            ZXVqMkRnUnJmS2Y4a3pNUFQxeGdVbldRZnc4CjFRbS9JTzNMVlF3cERYSENQVWxz
            SXNoTEorSjk2RXBPakJyN0ZQa2kxdmcKLS0tIHUvdzZPb3VxNWpVcDJvcXo3aitu
            WjAzY3F0Q1lTeklteDlNWXBqc08wY0UKW8IT2smBDJQbvBWMuS8u3NJi1Pz3yLft
            EOV+tkDM5cOpjUiY7P748r9QSecl69499aT//u0zYMtVkN+zk814cg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T00:45:34Z"
    mac: ENC[AES256_GCM,data:AI/vS6Biu4XS8SDwzf9ERFMrEttjIwvRqc/PvcynmEHsdVGfTf4NLoCvS+pYs9gnKfbh4PPUV00Mcryl1rdYeSpu2oBOK3erO9wZ5W59xdkYN0edM4CBu86IEU0kB5jwzrwpWHRSJnn/L+wRI+s/nbMwB8Cv8PZ7KrNVvjZahkE=,iv:qzmy18HTnkZ3LVjVXqZ57kO0SZM9eV9MwfwjmTWOuZA=,tag:lRuPtEweRqnzo+kK0SKH5Q==,type:str]
    version: 3.13.1
