apiVersion: v1
kind: Secret
metadata:
    name: palworld-secret
    namespace: palworld
type: Opaque
stringData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:Wjv7LKtyBIckVeX13LA3gW6fUpVAMXCu8ZIQzSofo1Y=,iv:QiYSVo6R7XEVhvUAmFA3LLAzqa11dkJyT6u7XxXWGb4=,tag:1HugZvoTpcODHiSH366mwA==,type:str]
    GAME_PASSWORD: ""
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:PwaI4icBGuvWFg88m1nLTHIYmIu6CDPAVhzXplMbyYpFL373mARcvo3yeqHMkiReKxZtJti7LiQpvQWncOVdYuJFj5iomUJA/s6UaW7ekvZBMvkDMeXXe8RwTCDOtykKRdUN+9pPW8BLu9cbUzwlJ1O6HV+iKTBrzGcstw==,iv:7z+okXKZvixDmBtAy3a8sZh36UaJkRSZH0yo3PUXmk0=,tag:6S0YVnJ7QGIAjeyd3hdvDQ==,type:str]
    SERVER_ADDRESS: ENC[AES256_GCM,data:3Tr8qWuQepADJCEJfqR0VzzuD6Knlz8=,iv:epdZ0ud/JAdtKCYX0I2y8WYmlaxItOajydyfRWDmabE=,tag:biFq5DIWj0uqT7i4GyXvow==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBaHFPU0pU
            ZUIzZk55NE0xRnZRd1l2V0FwUDFwMUsvUjlkY2FNUk02ZWxFQgpyOVRvRWxQUUJw
            YUVackJIcFhxMHZMTnlqdlZ4ZG1GaXRyZDV3RUJHQ2tvCi0tLSBzcWZEWjVWRmpC
            MEEzK2JJcHpNY3VCSkpEVUF0M25LWVg5L1JFLzdQamFRCvCpIJy4dvneWLPbSDzM
            CTwjAj5xlUXVSl5AWBH0jZZypEt2OmLr7tXkxEGdCFnZPN5Xvc66s+dPkEXJj50C
            gY4=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0S3BJZmdhMjJFMFJvRlJN
            WFlLWkJQZUpobXRuVnR1cndvMGt0dGVqWjNFCmdkU1Q0bWtwSjVaNVFZcW40YVlh
            amZpc09jaHN0ZnY2Q0RBRHlGSmZ6b28KLS0tIGR0eDIrOG9vTDRieDAwb0tSSytB
            NVBqdUYxV0pDQUlLN21PMWQyZjJZVjAK5q/EcvZkk0628YFT7Dx03mHUKF41VmWu
            pTrx7IdZvURVpjBF0lUS3YM+UNjMVe9SHhSA04cRKpKL6KAbj8KAxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T04:29:36Z"
    mac: ENC[AES256_GCM,data:ePLeL8f3ze1eWVlOk9ik7GBX6tGbGm/0MNEC9PwXlqIPfidSVSGamSdfwvZJdfnMbQ6GbXGCMTrs3YhuGM5S9KB5R2gd6iy2H+JwzW8euvtAiXNRIaiMwmbYNKYIITaVD7HAmilLBSv+GMKLmvHoUsvoce5tA5D3ls+14pHkw0A=,iv:Ocv2wQsrksa5Mua/0px2LFR+/8ZRnzPbgRqLxT1oeig=,tag:Ap5TxLlsYtKXfa0EodTAHw==,type:str]
    version: 3.13.3
