apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-agentmemory-0
  namespace: agentmemory
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: iscsi-persistent-fs6712x
  resources:
    requests:
      storage: 10Gi
