apiVersion: v1
kind: Secret
metadata:
    name: invokeai-secret
    namespace: invokeai
type: Opaque
stringData:
    CIVITAI_API_KEY: ENC[AES256_GCM,data:DPxEDYCVMA96H3io+d90Ps7VGkvXmHou06hB8S6Th2M=,iv:ljPej+nqch6UodKZ/wWahYaLnJzz6heeYeWWN2v3PPc=,tag:4T62TRjEjtaUoVpzWGVOgQ==,type:str]
sops:
    age:
        - recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBL2xhMC82
            bzE4dTR6c05LZzVveEVGU1V5SjBxcFVCV3VISmxKb3hXZXFQagprMGR0aWRvZDJo
            Q3lxSHhpcVVGKytkNmJGSmhCSDVQRStaM0h1VklUd1E0Ci0tLSBGSTN1Y0taWE1m
            dk9jZWdhWDhHTEIvaWpTTWtLd291L1BaZmxNdit1TnFzCojXhzL9DsK98Z0+9WTw
            GC4GyImtFZWnu4I9+sAOgIKACFqxngoYu4mwT9A6fmhHfi9JmWD2aEUuTG02EYG/
            +Z8=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzM3VJWWQ2emVYV01QVlBi
            QTI3QW5xeXJjejZtYjllOG9Ja1RaWjVoTGhzCkcvSTRSYi9ua0llZGxZVGp4RFc5
            ODFKczdBQmE2THAzc2JCSlR6VmtzYUUKLS0tIENiVmtFMVh1Zy9ES2dVV3I0SXlB
            MWwxODEwbkg5OE96cGttVHVwMnc2TUkK4rn9ZsRXw91dsgCfINslHBL9Nhk8D8xl
            IZMOh+DrNXbIhZ14cYJN8lHUlZyeWwO8gTg7xIM3CU23pesYy/KcPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T09:07:55Z"
    mac: ENC[AES256_GCM,data:R6YeKuTKMKs4Ku23wzWPSN1+EuMgYb4cmjo+nlwI1dnK+NRr+BIvilJ6CQh+UNjDEzZHS/7+TUk5eGPummWd7QhWFFELQV16U4KYZWDLFAoyN4loYdn1GCxrLge7HXVSAGhl711uJ6hqJ/kmkA0KmqKuUevGoi5n9ikdf8uMsJ8=,iv:VybaCGXvQItayTHCaXgovSKPqvahOar3yj8rU6MTOg8=,tag:8m6OlWKUuSZozE4Mywd7bQ==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsZones)$
    version: 3.12.0
