apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    API_TOKEN: ENC[AES256_GCM,data:LyFg+3eYK4m3BrYNhr90M4UP6l61reT8gfalMZOa7ms1o9isEuwfj2e5r1CBKa+njUTxuTc=,iv:m79OV7g2AY5z73FtYUqKNV7kwR1eYIXv+7o5czEsDSk=,tag:DXAoabn0x6JKSQ3cs3WK0w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBdFppK2I0
            a0p0VjFrMVRwNHo0MCs4dXcrRUNFWHo4a2dBSENLdHBzeHc0TgpGek55eXA4MDJG
            SHhDNng4OWovT0RPTnhlQ3ZRRlpNcmdpT1hzdnUyV2Q0Ci0tLSA1N1hFbzQrVnBK
            djZ6aXdTMGZHTlF5OXBhb0EvSEJRSmlDY1VxdVRuOWNBCnEv6U6JnY+yqz1tQokG
            dcbXDGnJ16LvQAsFWvSc0eMnpflIVz668SYq/ARuZFlnR70xEtflmP0j+kg6wTKB
            /XI=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicEFDeDF1anJQQnNPMWNm
            N0UzVklWdEczZUNIZmM5dUpOVjg1WFlCY1NBCnRJZ0NpcStKbUI2QXRsaUZWNm9N
            eTU1OVBUMU1kMW9jNXR2WjRXMlpxWmsKLS0tIEFBYW5QSGdQQ3dNRlpydno1VHhX
            SXQzRWVZZWQwQ001UUFXKy9nL3IxaFEK37Nu/L1rrBDRafD5XMLwZw3dyRsEIdCJ
            sF1BFk9rofMu6i5C0knNwX3vI4TqWK6GnDrgO51W8jWflSmyXACaRw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T03:29:01Z"
    mac: ENC[AES256_GCM,data:PLaoIHp11xrcH8w2VwDs2EOVvB4LyoXwXP7v0whXXr4h1vNEMFLgwFI0meqiNZRZYJA79d2dgFmLIT1p6XNSg7ss0qyGcPO+0lXx7F6t0ZQkJ3cDOit/xoYEoOWiMRT04mKB0FQo1UFr94zMAl1BDoWGDTfelJ8CViTB83XrxWA=,iv:asRPv+PfkDxrSzp4/pQVQBeLa1zKKzqCpd+FVTlxPKQ=,tag:tSub6olAuaitsKyhjEx/3g==,type:str]
    version: 3.13.1
