apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:XpM2jtqScbE3KdjRwkMQKh6//NvmVfjKwhtH+qyer08J7qb1UJY+Hw==,iv:1KfU1q/tcycx8QmguSUu1ZjLJ/IG66XGEWvKLbJULCk=,tag:AXdYOcRj8OJ91iZFlz8FbA==,type:str]
sops:
    age:
        - recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBMDBWUERz
            TW1UaTBjQUpRKzhIc2FaNkh6THRFT0tOYWxxQno3R2ZaaXZTQgpORnBDR1l2OXUw
            WHQ0SDBKb1l3TXN3aUJza0hBQzhadGQ2OFVxNGgxanJjCi0tLSB1R2plZjB6dEl4
            eE5KczYzWmIyK0RwQmFIenZFZHBGaHE1WFQ3bVpqVzVjCgDX4JH2puB92dyn3lAK
            JDNb6RlmPu0/w6vRdw+u7bSXtZtHh81tiXWDwU4Il0Sn7VUajVy7H8X//pHoARpD
            3pE=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcmw0S21sbG5nNzZSRjlm
            NHZLcEJBT1FKeFRlcTJQWE1IRzVPWHlha1JFClcvYmNNUFdoWHlUOWxhTWQ2K3Ix
            UGgzcWJGeDhoR2lKbm5ncHlhU3FTSWMKLS0tIEx6OEY5aTBHaFpJaG01NG02UHAw
            TXFJMVh0UlJBcVBsTlcxNTdUVFNrTW8Kn3FqlVwG3drkSl2xdmFCkvHd/Itwq0ie
            0w0ZONUDXKRd1pvhKk6U4efNQPkf47KWz4wBHm7BqCixKWhsSd87Ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-04T06:44:30Z"
    mac: ENC[AES256_GCM,data:SOLSTyzP8l+Op1+TlE0owzqfW0Y1eoFlNGamQMLpYFdd5HrJcsLoWUTnGEc7k9sZONHYBTWVaQ+NxnzNqj2CJnGW3uxdaOpT3863pmZv+yvSU77DZVQjEGYPKtK4uoWmRRJjJvM13xuK6XYMCACoOXjePFb2117RubhRcOqAmJQ=,iv:nptREKHveZof1yeMpAmAqJ4QAEpnodcxhHs//eAqqoQ=,tag:72ES5Cw4nLmb74w2EiySfQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
