apiVersion: v1
kind: Secret
metadata:
    name: mysql-root-secret
    namespace: mysql
type: Opaque
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:c/GdQQHZVnv0LWEpF8cIGLaTlTXuFcD/UEJyQaA=,iv:GlUWRJz2Z4X08MQyIhK4cpj7k+kq5JjWf83tryaonYY=,tag:v/IZyb45iH2v/7YjdgC7Qg==,type:str]
    MYSQL_ADMIN_USER: ENC[AES256_GCM,data:nosHyI2rxSgI,iv:gEsjR/ynJdBrHJjIJWmT/qWYlMnvWl2fxfj+NA2nw+8=,tag:zliFuwlw1SCfLfw03+f8hA==,type:str]
    MYSQL_ADMIN_PASSWORD: ENC[AES256_GCM,data:8z/e16418LSTTft+HarO8+wVRAKdRihjpGFInng=,iv:DH/jTTKxAQXo6QrzwZl+0BmZNbYfFMZhbQd4hNPednw=,tag:Ihc2QewKm3I8dd2qOa7I4g==,type:str]
    MYSQL_KESTRA_USER: ENC[AES256_GCM,data:1MEo1FRe,iv:O9SiTfrNv/t7gCpXASDdaAwNRmeBhZeQnWBXAcyICJs=,tag:/duH+y526smVMrptM8e73A==,type:str]
    MYSQL_KESTRA_PASSWORD: ENC[AES256_GCM,data:T2o5NWKbcqN9MnrgcyR/Wy8hShS9,iv:dk4nVK9Oxwjso4YpBOnYc+Vzkxa7hfDm3VGprDnxLHc=,tag:npJthfS67H9hQEzswVGHrg==,type:str]
    MYSQL_TEMPORAL_USER: ENC[AES256_GCM,data:EJVOFvRmi5k=,iv:Olx+gbvaLXtZ1tiRS2bAbLQxNLXO+TjsyUl6+I7E6Yw=,tag:vbqIU7NNP/jC5cMXHmWXZg==,type:str]
    MYSQL_TEMPORAL_PASSWORD: ENC[AES256_GCM,data:b0KH6L9Aq+ecpksNl3AlFOayC4I/,iv:jAg+1mNnuPtpoB2ZyIMaRZHOnwFQEVg/twvsiat6vCQ=,tag:YvuBxoKtf0j4O1Jm0vc6eA==,type:str]
sops:
    age:
        - recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBaE5sWHVh
            OGFqbHU3eDZ3OGlQY0U3MEltTUp1bUxLWjIrODRpcWZhTnFZaQpsNVFQWVVKcmVi
            ZWVyNzJFd0JLSVl3d1JENnIrdXhaQVhoRnV0OWhpUTI0Ci0tLSAwK2NkNml3YUtS
            N2pUTXIwTElqU1lYdkFMakNReERPNTJ6OWZUYlJiVlZvCpB3LFX23rBOU58ZHwx/
            pzuzkxsjc/tGLYZJK2iRwpcZX/9PMRbW4cnOXi2NjQMl4JAVTCSmpdCylILXFyeE
            54M=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhbFIzZkZ0WGl6emVvRHQ0
            YXZWeGNYOEZkdG9jQit5QmpSTk5VUjJjaTBNClZYbHMyWDJ0S0JpMVUzeUprN254
            dU12a1VOcDZ4MXZsbHJJYk9VKzUxNFEKLS0tIGRMMTJVZ1VMQ0NsNFk5REU4cEg0
            ZC8rRm5mNEVQdndTRDREQ0x1MmNxYVkKxB2iudnYLKCkWddqC10QNgYgkKBC/er2
            IsM6VQTm/JW8u8jm/WnVWlJb0n4BXGqqA6zuBEx3ECeO8b7q5SMTgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T10:51:17Z"
    mac: ENC[AES256_GCM,data:7GcIMPPTPKo/nSwwCWTI2uHeOyQRPU792ClTAbvbE+GLM0HeHTp5RMdXQbU6uYHOoJKQGCMw2GSkS+3C8w2kbM4ZoCsAhI7g3dpN8CikDyQ4a63mK8S2pIliCftrgSzCH13wZKxjX8xlSpcfJt2htkiQDoZ/dzlzVDoLdewHveI=,iv:v3+i7CQ2phh52O5PFPepdObV0vR8u58+1zZq8vnJndM=,tag:3y4GdcEl3jNer5+RJfIXmw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
