apiVersion: v1
kind: Secret
metadata:
    name: playit-secret
    namespace: playit
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:5v1FIOVbD/hB6e3lpsIWPX5ww+udbEEF/kchm20u2Lv6tvJKhLk3lSvH0WdqqV500FnsJhb/8Ywb9h2nt0Z/ug==,iv:hguC+hUW5IwBF7fuqY6xAvMwfSmLJzp3k0CRR+7gaWM=,tag:5DwvBJmTk6z4SreAdDNTWw==,type:str]
sops:
    age:
        - recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBbWRWb09t
            VnJaOTM4TCtISjdGeWtzQkgxZWp3V29oTWxuYUNKb2JHUGdIQQpONFhoQlhsV2sy
            bHRCQkdBYnc2VlkyVkdsN3I4RjgvYm5PRTI3VGdvbWc4Ci0tLSA3enh5Wm9QTUhZ
            UVVvdk8wb3Y5NHRvRTBqNEM3SDFXMFE1THFLL1JrZm40Clj5pyxLZGWqBr3kRsZz
            rty1XVXnXUIriMslsSAMKdaHKiHVkj6EOjccgCy8e21qbD/i6zjLelZztXRbUNZR
            yDo=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVThiY2lCY1NtZzdibVli
            MmhPdUZBRUlrYmNydmk5T1ZQZERqOUpNOHowCnorZUJ4RFBEK1QxSWV3QmE1eEVt
            UmoxNy9JSGl5S0F6aUViNzdzMld1b2sKLS0tIElSeTRrQzJzOENIQVNpV2VUMGFO
            WEM2ZXBZcmZiRGxGUnkzNkJHY1Zxb2cKTZsa7ue3RRFzTqZEiwgFzVlO8fbi0qP8
            Ea6zNSlUuR/0MuPiWtNhS9HE8TrjcxfpVKlenatIUvWSXROuKIDxig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T10:17:20Z"
    mac: ENC[AES256_GCM,data:lVNX8L1GCc05b9Ls7YnL58hu0mQQL6nVkyaabuJPcr/aK4da6RxtiK8EwnV2vkTYhAjZjemhtdHxxPKcrSlq4lQfR8UIGlH1YCE6b7s7xoPR3AS1ebpdkDSrARJ/2QP/YxMOzOP9sBoJesxxHPBufxVDEBUP7qrWwixrCiJkdrI=,iv:TRozmczf1Qnx2wZ4zAB2MazFxzxrFr9popcI956eRdM=,tag:gmWetyr/zmawuOt78GbBdQ==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsZones)$
    version: 3.12.1
