apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: minio
  namespace: minio
spec:
  endpointSelector:
    matchLabels:
      app: minio
  ingress:
    - fromEntities: [world, remote-node, health]
      toPorts:
        - ports:
            - { port: "9000", protocol: TCP }
            - { port: "9001", protocol: TCP }
    - fromEndpoints:
        - matchLabels:
            app: sera
            k8s:io.kubernetes.pod.namespace: sera
      toPorts:
        - ports: [{ port: "9000", protocol: TCP }]
