apiVersion: v1
kind: Namespace
metadata:
  name: playit
  labels:
    name: playit
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
