apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: playit
  namespace: playit
spec:
  serviceName: playit
  replicas: 1
  selector:
    matchLabels:
      app: playit
  template:
    metadata:
      labels:
        app: playit
    spec:
      automountServiceAccountToken: false
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - fluxeon
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: playit
          image: ghcr.io/playit-cloud/playit-agent:0.17
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: playit-secret
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
