apiVersion: v1
kind: Service
metadata:
  name: tailscale
  namespace: tailscale
spec:
  type: ClusterIP
  selector:
    app: tailscale
  ports:
    - name: wireguard
      port: 41641
      protocol: UDP
