apiVersion: v1
kind: Secret
metadata:
    name: seraex-secret
    namespace: seraex
type: Opaque
stringData:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:u9IhRbz0L0JsnVD8dSCC8ZK+QCLGBgp7Jb7+08vdF57yIyVfd6GxrKlK5ueFMWfIYg++5Py+EON4WSf2ky4w414+62d9rRtcXUl2+wFuh+/zXco3w8UF2kLhALG/sVAEzMn1mbbXuVpAkm+a,iv:wKEL1bE0YzTeCc5V7CCUCcxsi1hZCTxU0BWlomRVqBo=,tag:CwlycLHOP6nB0XFu0pDaOw==,type:str]
    ANTHROPIC_MODEL: ENC[AES256_GCM,data:0wtAb56TWxsRnbh7EmbagJCl1i9lAKo=,iv:b3370qBL0SE6kKec48v5aJ/3qMV2Nuu8aHIC99Q9+gY=,tag:hohvaVbGN6Q3kxGEORq6Lg==,type:str]
    TEMPORAL_ADDRESS: ENC[AES256_GCM,data:KpiNqU7svuHtHAFyUWmDHuBpHnkBCcK41FWo7WJdFNYM5P67GBRgUg==,iv:xcd1ZPYkiiMIkdCB5qHWVsT1R7Zy4FPZvTDmm8pYzlI=,tag:qD/HiJFpgP4Bzqm3atxnEg==,type:str]
    TEMPORAL_TASK_QUEUE: ENC[AES256_GCM,data:z2wV/g==,iv:jcMX2zn8gMg1gfcbCTlS9wF9LvI2j15Qm5X1EUEoYQE=,tag:QrzMt8Hj6jFn2hoslEGuuA==,type:str]
    MEDIA_INPUT_ROOT: ENC[AES256_GCM,data:HrTuutTKSIMpkqO2/DZ1YQ==,iv:07Q38Ztq6y9xqK82Vp2trUvvET+vFfjRyUzjJbq4n7M=,tag:3QdxsUhrv06bCkcVLVdT0w==,type:str]
    MEDIA_OUTPUT_ROOT: ENC[AES256_GCM,data:waL7LBzvwNGX3NgqzC96SuU=,iv:MOC69LCSm1t9uZKG9KgUWpTPWtkdXwZJopMlAOVJcl0=,tag:k6Y9cZrBRMmQOV0NcmOlVQ==,type:str]
    MEDIA_STAGING_ROOT: ENC[AES256_GCM,data:cyHVMaDCgo29a1YG0caI9hL/,iv:BQBoq6PRhX6KRvKosRWSs+DH/nDZtpUUw6MQlDyKIa0=,tag:n6m74chIdenXT3oizPY+Ww==,type:str]
sops:
    age:
        - recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBb3haZGVP
            enRKSVUwelFEUXRwV1BBcTJQKzg3U3hRRnB0ZFpuUzczQ0docApER1dlbWJRU011
            K2pCakJGbWJQZThueFI2alhWbFA5aGVObjMvSFZ3anRrCi0tLSB1UlVmL3JsMnZv
            Z0trdVpjenEvS1pZSWJPdXp3a1IxODZOVVJUSWcyODdjCk49JJLohY17Pd1dMX/W
            tSZoFD66z5Auyq/K6aJ7qxue3orh5+A7umXWUhUrzJ4yhSy65V9aNMO+oZYo2j4L
            c6M=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bkI3M0lIVUpiNFp5KzVw
            djZMaWNWMkpoWUFoaU1JbDBablcyZ3lQR0JjCk55Vnhxc1RZU25lTWtTUzdjanRz
            MExkQkYxT0d1blZ6RVhSUHE4aDVLRDQKLS0tIFYyZlFJNW9uVkttN2VRRVozVjJU
            N01Rc0F3Y29HWWtPKzFlK1Y3Q2xFRVEKJN3sKiPszr0ozMihpDOYUAKH/9QOf4xo
            Gnj4qVnNd9Pxn7xN1Nxy3xz6aexiwmshKvZT2gedC9XaKNDWbIrGKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-11T06:24:39Z"
    mac: ENC[AES256_GCM,data:SVy4Le7XXHM2tQFlSxE+Z8REQ8XYi33w0xbmZ/K0NGSRshTOykndRR0ymAr8bTKMk1rVgTWJvN+ikBMBtMAvG8NogtIUbU2CUlbbpSJvXFjb5g0xtQ9cJUcTShOdXqpgS7JS8rIKWEj8whtKbaRNFTFLRys4xT57nKjBhWPRbN4=,iv:Vvzc+qCaV3E1usurN/S314/0WIJvzgNT5rsZ0NpxsRg=,tag:T4d80IOrbw3qVQEa4cN1pw==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsZones)$
    version: 3.11.0
