apiVersion: v1
kind: Secret
metadata:
    name: ntfy-secret
    namespace: ntfy
type: Opaque
stringData:
    NTFY_BASE_URL: ENC[AES256_GCM,data:Yt7CSfu9zzQoeySzp8g86vT8tsgyTViuyu8gRben,iv:elGwgPyZeONmxqdVDqnj59NTeNX4kwhr9I66kKlzJtk=,tag:Yp/iMhUd+tNb9ITCVFfWNA==,type:str]
    NTFY_AUTH_DEFAULT_ACCESS: ENC[AES256_GCM,data:Gzgb5+aRBnI=,iv:MeoUUfs4eXWeUdJiowTzID+A427dyM7DrCk8m75G5Zc=,tag:D3kFp5cWVxQxs0jZiJRmjw==,type:str]
    NTFY_ADMIN_USER: ENC[AES256_GCM,data:hRmyF6EAS7R8,iv:JxMZf9FRSTkl3Tl5EzS4zSnV0mfhwoLVL35gQkM/y7U=,tag:pXAutyGY+IUSLZjzV7ICag==,type:str]
    NTFY_ADMIN_PASSWORD: ENC[AES256_GCM,data:au5H62yu1CIHAjgGY4tjmRBOsmSlo8mZHB6VmBjiC426FfTRJd8n/LpWrg==,iv:Sii73uMiwSShL/6W+JQX2t+p/ogiJlj6puJuthyWFfU=,tag:6lUmRQfC/svBArLY/PVUXA==,type:str]
sops:
    age:
        - recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBcjJiMUNE
            OTJsMGF6YktiRDNrR0pXelBnVmwvWDIrZ0pYckFTZ0xuVERYVAplM1hrQ2tYMUk4
            UnJsMWtCRXVudVh5dGdTMWliZzYxdG5BM1EvWHlSVGpZCi0tLSBzWkFacGp2dWFC
            VnZ4T0RDeWxjQ1JJRnJxQk1WaXdYdkloOGdLQTRhMC8wCoLGh1aZECnv4LfD91L5
            47Rs0boCYm/e2iYA5hGqgdR9eHhkPBOcIboOLusfd+Ga+c/3OQByZC0O/QCXaOBA
            wOs=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0REF1UHhsTTFmT1ZZNlkx
            Q20rMzhFVngvVGNqV05kZ2paRUphbUh2SG5rCllPbkN5VGFjcitPZkJMWEhEL3Q0
            Q3ZJQzE5WUwyTVhzU2YwSk1ndFJJZm8KLS0tIGFyS2xaZm96Nnh1a2Rsak1ReGZy
            eXdaMmRzZGFUZElRYUxRaC9ZMm9lVXcKYosNCXi7+uvTE8ZGh0fhI62SJJBgYyL7
            Q+0Io+v8ABFUyeZEHjpGTMkpole5T5db1Mn6l4L980BGHXCj3TOKBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T09:34:31Z"
    mac: ENC[AES256_GCM,data:G/R/5VDURkwdjER94pT7vkkFRihvTtKeCbNRENfoiJ/y5Pv2M3n2H6+hM2n0oxT0kBuKLvyNtFiFnqtp4BmJ/8EuMr50FncxgGI47aNZNRFLqvbLawEPRXBFvqFvJs8iQs6GXKC4OBp1Xd9X5HRlHp2h+pgLHXFtm/N/GZvxE9A=,iv:+ugQzaHhnXdyYZkqGWIqDQ8g1oeimpHd5xIIe3nhP0M=,tag:7HZQiHf57oQxhrbOuVCw6w==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsZones)$
    version: 3.12.2
