apiVersion: v1
kind: Secret
metadata:
    name: ntfy-auth-secret
    namespace: ntfy
type: Opaque
stringData:
    NTFY_AUTH_USERS: ENC[AES256_GCM,data:BLqxBmW01o0ZOw2+3lcMneMZr/uPHYO0FwBCi08WwPyj0vRXVDvk3tkE+lwTGWQ6ucigVMTRpsQT6SBeKltFOTGPaU4avu2LYKaRJclS,iv:3Xg+ZMHOJmsfgjoYCDbYb6h2beEbIycD79YTI7z5fXo=,tag:jcYZFFvala1GzY9ALNgu1g==,type:str]
    NTFY_AUTH_ACCESS: ENC[AES256_GCM,data:XKWl4zdzqjjFFEYe/zmz/Kf5qK/J4XfWmxKnLZqi,iv:96Wh8YDYchL+J+9f6wJbluieoZHAYDXWymBYdrxFZqI=,tag:UsSmUjiwDExJT6ScNrJX7w==,type:str]
    NTFY_AUTH_TOKENS: ENC[AES256_GCM,data:9Az0/JzhWPqUFHLDLGXjNYfxVSFXofhXuTwFBrV5ZjYMtzaIWpQ62Fm1oF5rqj4j1Y8yWsY4S1hz0g==,iv:FjylQnZeiH6lROnnN4CABgT4lulsef3DfZdlKJdZfZQ=,tag:0E/+M/x7jCrr87PJCZDcBA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBKzJKZkpi
            bkEzakY3NE91YnpJRGhjQ0ZWdkFuSzJlT0FCcjhlSFBhN202TwpjK25xSktRZWxq
            KzhMNTZaak9XcVNGUWdzSDE4SFlVU1FmWGNuV3F1dGx3Ci0tLSBCYU9UV0wyWTlj
            Yjl6VmFRdkQ5RWtGV0FDWmhSRnhSYlRyeGJrUzBxNGtNChFSZH1gDPgN9DG8xyag
            DIZXJB2y3UQfkhLJm7IyVlUnkd/V+yG7Tq6RUhY3+VzKk8D0rbO0evRP7GfILnAg
            inA=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5TmVPYjc5bGtjNCtBNGs0
            dW9ycE02Z3B3YUhxRzF3SzIyZUVsY1IvdEJFCnJrR1MwMS9pL1hEMFR3SGsxNmdN
            elZ0Y1FlMG9WRStLcWZXbXVFZTNPN2MKLS0tICszcy9DV3hOMVJveFdOSFFMZnlB
            VE1OczFDSHJSdnNkMlVpVVJIVE03NmMKVFTPDavZwa1laNKF9qOo/dutydGunHO+
            hY1EOiiIFVO2hyDVFpneVlMc4mV9Nv8kfbxHzhEI4h11m9JAPAMxCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T06:44:59Z"
    mac: ENC[AES256_GCM,data:VOhuTn6C9wx4bIh/nDY3LWW09fbTc1KwhuvhJHNYOCyswKOH+BZRUxIGhV91cH99N+93UYEGUXD3H0SaFRRvbxKazmJ/pfbsOMhvylkDSNxkIFVr15OwTwn0lJlVYfXx9RyzgapXDs4u3bgrCQmAt66UmSiC8ZmuNmcET6ttZ/o=,iv:DZWhd6rogODmpHTR6CmbyLjnqcxHLhQxZ2MfWQDYq88=,tag:EWlNDkDTGIPrH5/IexazoA==,type:str]
    version: 3.13.3
