apiVersion: v1
kind: Secret
metadata:
    name: ntfy-proxy-secret
    namespace: ntfy
type: Opaque
stringData:
    OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:ay7U8kDTlN1HFStNHQs4bCC2QFQ2e/g2tmm+jF89v2yVB1+fL4uq7w==,iv:aUtjICys3FXaLoCPcXsSoieqGqzZyClLPIayXSeErY0=,tag:RUq8SiN+pjrgLdrqCtjUHg==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:OzCMt4KjU82FJvYDzSeHy/0XmhYqEN0qZWTdbEmhjt+Gm7xkusMlFiZgyf7B2io0CxC/+xDemGVV4piElhKjw84bPHbOHhcv30+6vuWx2CGXyA8ct5FyJOC0YnDGlUHjORNvkXFeM/UyuH0DKjK7hpIFaev/YVZlJoM2jxbnqOA=,iv:F7U43nYg1muzkE5oxR/HrRDbHApZ0H2Hcyk7nlTSgcI=,tag:Usa4VarsgLXa6CXuwiOrUw==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:Ayek9qqTqqxudf5ktoIKAWmI7StZ2yuDLoq5eBNn7McwhTri30or5k4WQg==,iv:orLTXaQ6X49U+SG4/se7cnYCnR/YmOFZvcQMdZcOOQM=,tag:qRLKFgJrneRbg3Crq9Q6Cg==,type:str]
    OAUTH2_PROXY_OIDC_ISSUER_URL: ENC[AES256_GCM,data:tQSxPWy8t1jQ4bIBE3G0/mCsXiSIPrlBOR106HbPliZGMiQ/KwXYJt4xL7CtbA==,iv:OlDfusgc/jhhvZIpwlNd0e19xjXsUmrJW1P/8RXsNrQ=,tag:vmB5LEhp1/Hxq4srw4+tKg==,type:str]
sops:
    age:
        - recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBMjN0NThL
            K3lKUDFuK05xTVNzakhBY1JVeGhNMjR3UWhiVzhxeU5lSWt4NgoyZFRDTUVBRkda
            U0hMSlFOOE84amYwZk11WnpuNDk5S3lSa01VcFdnQ0J3Ci0tLSBuQlNQWitXTjZD
            bVlNQnFHeFJjcnIyeWhRRG1aZlFIM253TGM4a0Vxd0JNCny68aoAX0BbfoS1NuYK
            hT9ex3opBU5lIX6ze3GIeMC+PuUreezQDETICMjn5N8nKdpRewBVDpQU6rg7NCU4
            2s8=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArK1YvdlJudlY2L3RIK3oz
            eVoyY0FoUkRGTlhjQkwzdkNKRmlWWll0V0VvClFLQWQyYzFZaDdQOU9URGtTMTls
            bHNzanJjWkRjRUk0aG1hdW9YdktZUnMKLS0tIFNmVzFwNkpQMlpWckpESXpEVjB4
            Q3VUQytsNEphQTBkMlF5aTJCUTdjOEEKxDP0aVb5xNgCuKqqzuVTEgWWhnzGza5u
            OuJtTMdOstjcUL3NZmHo4REM+77kFrtDqwf5FCOSf28NhtPXnyxdAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T08:27:30Z"
    mac: ENC[AES256_GCM,data:NLG0r3EsLW6iVJrkp2feuBVGxCujeaoHTvTrwE6Tqsl0qwPsYfNab6gLDJjMZLSmmVtXKbl1VNOyNaBg6t1JUHYRVKPzicNNbQGigYzx/w6YYLpSwJwGEIgXn8vIadzNgQlnAtI/DGKXagUqmCibaPbmSPRphgAbN6ayU4TFEzU=,iv:sJg0fWy7Vj1NCvbPZWV7rDMTYMemZS6aixfOYTHTIV4=,tag:yvHrKVAaLvRISC2lGlvhKQ==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsZones)$
    version: 3.12.2
