apiVersion: v1
kind: Secret
metadata:
    name: belugabot-secret
    namespace: belugabot
stringData:
    CLAWDBOT_GATEWAY_TOKEN: ENC[AES256_GCM,data:iHQnzz5vVrL8TuqZayhKD+88RaTopvgvhR9ezFfprbslxwwt,iv:SvDilB78OD0LdiS/pKPhrGkpzW0cZmJ4xgPtDHwNMns=,tag:s6Miq5GfjzOetTr4B4kpAA==,type:str]
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:g2k/LS5G6RjDZ7nu7tjPMOJ0zUw82SVucAVQ7DcUJT1SAznmJJoaM2wyDe8NfI5oZMTwivVsD9+I+zcbrnTHxzr8+r70ltMAo/aCKw11Zd9d9SMpVwC7WbEeDlJmSg5qSN0PJBrMLPPz/kLf,iv:B8oASwqxu2wkT+cj2vD/BLMGB0qiwOzffnx0tOIBz24=,tag:JEMS7CwGWcMeRVNz8a8hnw==,type:str]
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:xEMbcttklQjTTvRVabUARpD0guLJjDngausB8MN6lvTglOGr+Z9O+OBej/IoXRw5R60k8qxHmYvpMjv9p96gsGS2s7wrOl4S,iv:dGfrBhp06esR5foSwGPfzvbOZ8VlJlL41PCbc8E84lU=,tag:UTHGiq7vKeD1fp/BWmXCEw==,type:str]
sops:
    age:
        - recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBanUvZ0xN
            QStML21qanozQUQ5aFYzaUQ3YWtFY1ZTVFZBYzhWQ29QY250bApWL2JjK3QvOFNT
            SEcxSFJndyt2eDNZUThrM1FTVFE4RW1RQi91RTljKzVFCi0tLSBOVkg3aksvaWRC
            bjFMcUtQdHg3bnM4T0dLa08wT1NRYjJmcTJHekhiVUtJCqh/SxtDiIIBGrmtzMDU
            EoSl2SxoJuqkTbzqVUP0g47kDYTGvtpGyu2H3NXREC0Ivnz9rLNHouWeKUIPTVBP
            oKA=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NnhiT0U1QmZKZThPZmZy
            eFBybDlMNXJiei83bzdCWVVaQ24zRWQ1d1JVCkZkVEpZcEpPYXcxSGdiYm9MZ04z
            Uk9JU1RlcmxYYytkUVdvUkVQeEo0QXMKLS0tIG1ZdDBOdFFuR2orWmNTK0pzbTd2
            V0RJWGZMaGtFZzlFVlk2UlFzV3lrVWcKi+ZPUKaryeCMsCZIRoljFfGuX4zvJ+Ph
            TRgageqGvmsJXf3uTlVcpYfk8dzn6x1MFcnBY+G+B+8ce9S5baePbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T03:29:02Z"
    mac: ENC[AES256_GCM,data:mxOso/++hrLD0wF1yQ9AvVK1vwennCJnRMYYm8m+emoXJisULbj6cWv7HId+ecmUeIVEqRVmzjzy2/t2mDPyZaHQ2trbTOcinCquheklcwptT6096HuPCEWZ4ucbovfcZhMb+URCGF36tH5XcemFpQScvHmwqZN82Npq6FjQevo=,iv:5kkYsbM3xx0sIDwJzgocYqKM4o+3wq3Q3smfScG0AvY=,tag:HbVZ7G51TgA7Zfm5ngaPBA==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsZones)$
    version: 3.11.0
