apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-downloads
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-downloads
  nfs:
    path: /volume1/data
    server: 192.168.1.6
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-downloads
  namespace: qbittorrent
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-downloads
  volumeName: qbittorrent-downloads
  resources:
    requests:
      storage: 1Mi

