apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-downloads
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-downloads
  nfs:
    server: 192.168.1.6
    path: /volume1/data

