apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: headscale
  namespace: headscale
spec:
  selector:
    matchLabels:
      app: headscale
  podMetricsEndpoints:
    - port: metrics
