apiVersion: v1
kind: Secret
metadata:
    name: agentmemory-qwen-secret
    namespace: agentmemory
type: Opaque
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:aJ1exNs=,iv:dU9aZSQpGVZzw3ZxH5tpzyZnTidkIOVrkibgbil1r+A=,tag:eVwc/vVAPzukS86ZCm6jcg==,type:str]
    AGENTMEMORY_SECRET: ENC[AES256_GCM,data:313KEO52X2qE+UtYZL/g4S6bbE/e+6u2CsTSguWXFNVIGuK8Y1+/3bjPFiQ=,iv:sQeVQTVTISzjTN0eXOXM4V8wuRYxDkbNLycJbHPTf1s=,tag:UV+JngncDv1kilHEPcg2qg==,type:str]
sops:
    age:
        - recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBelVRb1ox
            VW1UVjVTdERnUWl2Q2FJOC9ybllNamN6ZW5uYmFBNVRrRHZZTwpDSjRzWEhLRlFG
            NVdjeXlxUVhENHBCYk9uZzUzY0g4dTZJQnIybjhIMG9vCi0tLSBwVllYVE5ab2ZK
            RlQ2QjRxS2FHQmpXVUg2N3FHN0c0ekNWWHdBQXZUT0ZrCob91Ag6B3PACXr8LTea
            QmT5cB0AftlU078wATzYbsx68Y74Ecr8+t3Vz+V6y620jSwdqY1/PEAG2hQAQVVd
            5sk=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGOVVHdkZEMEU3MzZJYW80
            N3lWWnh2eFhYbkRyaEtzUithTENUb2plcWhVCjFRV2RMMGFCY3FQT2hxeU5xSE5Q
            dExXaUh6RVRuR0hmWk9OSFo3aG1wQ0UKLS0tIENBVmRKZUpwN2szSmh0c0VqZjdu
            c0FIc3FKSlMyWjQ4MGdERGtWSytVam8K9lYINXPckNesTiNb3puHbih0mS07XQXF
            kyumGqFiUQ/pKOdabowsGNRlCkefbde9Eq3LT5zD7mkc57ap17OCog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T00:42:01Z"
    mac: ENC[AES256_GCM,data:FPxg3sHPdB0g03XGuMXHUiOc2ML5gv3AlwTuOb4ImNHqedryfNnJfoWYkcIK5x+ry5u39V+d96/yW4+mgcDVx+65a9JkhMdEYf688h4ybRfV1FW9LN1QNhn/4fPmKHwmgO2gvTp1UkoDzhryeyf9xWG+CLSSVWaKVIC4VVfzo7s=,iv:PZqfshsVgrzlBgOyvkIZKXDmF//6FD9c2LlYP4koGVE=,tag:ibDqsYARxHn1g5iVIu3HpA==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsZones)$
    version: 3.12.2
