apiVersion: v1
kind: Secret
metadata:
    name: agentmemory-claude-secret
    namespace: agentmemory
type: Opaque
stringData:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:EKj/M/7RFo7ZC6fBOMVXDrt+sq+KSvZ1HHZX4j1mWzfUtEM7LpWyW5bj7V5qwlaJxSfX92x2eYbovoLhd1dH6UARH/YOfS/LplPLUxZ6H509vpAy9jCvCEhzLEws7LoswWJlFXYwLVNTPyeo,iv:F2nySKemqcGA5OTE+IK9LBdksU7sfpaT1J7tH5EA4BE=,tag:03a8FN4uXSnD+luOEJYlYw==,type:str]
    AGENTMEMORY_SECRET: ENC[AES256_GCM,data:EAv4ha+YKu9Y7C+4XTsJrWM/FP8SCol+DEvvfrXsQ3ZRqVc1PL2z2Gn1K/Q=,iv:Bz/YrJ7bhlulFM7jpFSTLxL+k+jEbjP7Y24w0z1sQak=,tag:ewFRb5cvnvawtjYsqZDrfQ==,type:str]
sops:
    age:
        - recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBcCswNHA4
            NmRmblcwYWMrVVVXV05vd2ZrdzluOVhzNWo3dHJKQTVIWXdGNQpPcHExS0RhRmZP
            UlNJKy9JSzN2S1lMbysySTFMSnFKY1czbW1jV1NLN2xBCi0tLSBiS1BOYWRmZW1s
            VHd0ZG04VmR3c3I4UEpQUkJwei8wd1h5SERTV3d3OXI4CvHTlS1GiKeIY+1h22w8
            z221FGjc9OUMjnGd1E8PZ6TfmsWTlcArjVgeCASgUgj6xq9msd0AInv970AZN79j
            6Ek=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUQ0UyUjNsQ0hlYXpCMzNu
            UzFWaElESW9KYVo1OTVYeFZQRVY0My9xRDBBCm0wMmJnUy9pSHQ4UENiSnNCTExI
            a1I3a3dBaHpGRjdpanVJUi9RVkRNV3MKLS0tIEtTZ051Wm9obWxzNllSVFRiRXhJ
            L3p4S2RLbGtObWZ6RVREa1BnRmg4WU0K31kYCBjmHMy+P59OaYVdHOgPfGKmoUi0
            ZNTNwPL1mGGgRfaTGTgvX3bcvZ1bHMw0N+53iIp7SvmrEabfi0P6Uw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T00:40:40Z"
    mac: ENC[AES256_GCM,data:2Xsu9X7c5H2CgZJCCiJQafcZL9EeJ9SvMWv7Mp9Az3wWb6uQmco00tbEm1F282h3hMC8rHC90Ka7BKrHB9DzCQoyMeOfDrGOSdHKwJHysdsqP+rPLXHL4yUQePjv8PILHdJZDYjX5vViEyL9VzUfja5LJmdt5CKSyOWDMnQjD44=,iv:5wwibpop0mayvjfmLalCDNQSghBa76pUQlMHaOAyLl0=,tag:M3b3OtcjiHAE+yYWtNHd1Q==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsZones)$
    version: 3.12.2
