apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:RYsTddw=,iv:lq3qSt0NaRxZRPvI7b2QPk2sTHKE970jE+ql19m3czY=,tag:HkRrV0KV+wlaN95NWmwovw==,type:str]
    admin-password: ENC[AES256_GCM,data:dOfiEAZhCfuZbuAGbenSGf9birVciA9SZEhAIV87DzY=,iv:QDqCmeIvTrpz0LRMhdRCoJckt5Drb6h2e+WFY4E5qOc=,tag:GYWg1z51SmDsmMSf91UqIQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBenpPRktC
            cVd2RzU5ZlJyN2NKUXhjZHlxQjhwdjJidlNzTWlsdjhJOUFXaQpxalhJajFNUUI3
            STV3MExLdmNEc3lhTElhYm1NN0ZaSWRHc3pwQzh2TTQ4Ci0tLSAvbGlMdFcyZlBk
            U2kzNnIxWGEzMWVmUWNoUEE4cHVoNXU4WS9Geit0NzNzCrsohU5Ktw5kitO2ARo9
            oXAJ37IEszimZ0F4VI4vbkQv7kLrYpfre2ugxcNGbIrFuDUhhKSC1nx1dUa2jxA1
            p/Q=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUktScFh3UmN4Q1FmOFlZ
            bHQ5YzM0c0RRN0hGVjUrdDREcnNFSjMyaXhZClBJdWthVTJQNEhaNGR1QVp2NGdR
            QzZ6aUtsZ1FXZVdLYlFyc2lEQlhZdTQKLS0tIDdYc2M4UzlkMXF2dnV5RzFiVTNB
            ajRtMFVLRDRRQmR2d3RzVU9RaVFtREEKBK6wNyTgNn9wXmy1DcjbnHzDWwTn0v8y
            8M8du1zjYPjpiT3xhWmpUVsb7+IE9b2+AsW+lFL7izUD3Mhuzhh9+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T20:10:03Z"
    mac: ENC[AES256_GCM,data:izjB/zxB7uCMdv9wDmj46yiL6ZMox0JNH/5JOELKnC8NPkFN2KaSkhj3p0hhZ6AqBG9Mn9XwMy4UL7Z+GusXwq9/aHFv0GSkHFqQDXoRIvXT7Kc+Ch5D8uJ0EUBia1V8xutxsZBR8bHYb8GCVJ9V3nRYCWDK+6jeI6Zjlham4uc=,iv:Lbhi8blTqG1jdNMOtfLVCNi9h+Jf5d/KGmmlYlWI3oo=,tag:2cgTEGqSUHPGUNyEQYD8Eg==,type:str]
    version: 3.13.3
