apiVersion: v1
kind: Secret
metadata:
    name: postgres-root-secret
    namespace: postgres
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:z1ILVrTmQQ==,iv:YxtdqPQ4nvNLnoasGY1WOtCNgA/IP7npZG/TyXHTyuk=,tag:yvyt26hlaVpTt3rvivejfA==,type:str]
    POSTGRES_ADMIN_USER: ENC[AES256_GCM,data:05sUtyrQOJc2,iv:ZiWWMya5jPW3XmM80GA2ksQoRGFefXgvmingUzqE6Xk=,tag:0nRGNjvP7hYEn5XFiGIQ+A==,type:str]
    POSTGRES_ADMIN_PASSWORD: ENC[AES256_GCM,data:4Vii5kcF4tSb/ilWPN9z3HKaI6LQqo+sxWL0si0=,iv:qzjfPygsVD0/CQ/2cHs3Hjt4TtV+P2WlDkHlDE+0uM0=,tag:my4TrbNF+NRb2NBAbc3HMg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:lQcxaCaWAlOD,iv:eD1VKetTR+bUgAlHRXt1jKz7cmr33GRXhWtUrQRpWps=,tag:HObBVmgBw/FC7ue4AhyJFg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:M0+JhZzYqVq0RuObOZrgHP9EwMV5mfCtZtrgWj8=,iv:UbfTR2KqXV1W9VexUNLcY96juxVKxwRj8eZWX6Ed720=,tag:9jCwEEMmSNC5NNT3dIarZg==,type:str]
    POSTGRES_AUTHENTIK_USER: ENC[AES256_GCM,data:wFx61Xp0Xw6J,iv:ajdCzc24veimbpcRN1C9a+xoDFeigvH5ZseqTSLElww=,tag:6eSWXrmrYNL8VoQDol+25Q==,type:str]
    POSTGRES_AUTHENTIK_PASSWORD: ENC[AES256_GCM,data:+ViCd2sNVu86ija4j851C+nPiIEw9L+LQ5V6wfVT2fMsBeraymfWxMLVAhM=,iv:CY7ipVA3xu3khQi3aUHDztJvSXzfqKaeaYUhknRvMcs=,tag:nbKwi5MUjTdym2c0gPLomA==,type:str]
sops:
    age:
        - recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBMGlsMkxI
            SGtHTGxuVXpCcGNFL1RQWEVEcE9iY3c5K0hPMXBxbFozU3dvTgpFcTI2NVNmZk50
            aUxBK3hjL0pDMVNqd09nSmFmQ0JxWFpRbjVnbWdxcEs0Ci0tLSBmWnFXZGR3bjFx
            L3hFOXdndW9aTlA2QzRVRHBxOVluZmZlcW1JY1pQTzIwCrqQAJtYVt2Mde7vU4Rd
            Tfrwy7C7yR1TTw5FvpsQbCPZKc8iTWzpu5n1U3SxKTkiRy5vcnpn/HNfEsXgkSws
            tF0=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBK1JPSWpUQm9YL0lxU2hx
            VG1WNC9NcGRmMm9saWpLb1ZiSExqTDdBREI4CmtjVnhTaTd1d2hKZkJUZXAxalpw
            TkVZZkoyZktyUTZGczdDMGpRMkdHamcKLS0tIFRYR0RpZkNUKzlaWEpxa04za0tB
            dnAyZVdsWEIyNURGallUSmVVcGcya0UKZrq9JnGBIN/dnrahraivy+LHPw4eoFVt
            AKJMhVjLufwgthrxYyWyGANjf1ck9fh77kAFbzbjRFtVza7C+MCKBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T00:00:31Z"
    mac: ENC[AES256_GCM,data:eK7wkR8uVkEGkoGCkeNPTM5I7160qaqIbN+LsrB06l1cEQop2SZUg5XeMKqJjSwP64Ek2nVsTG2x7lQ3ektIGpVRLfgzCim20jewphyFbPeLTnvD0XW3xHGg9IVPptUOxXJXgXVrPR0MS5e4+YcUjiIiHHyb/NoYKFd7pPy5kTU=,iv:7JxFfwYeO30Gd88P5HNzHcSmBcA0SlAUNFh6dLFoT7w=,tag:V42XsX4uB8m+kHO42hlSjg==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsZones)$
    version: 3.11.0
