apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:6EWs6HIzbviEalPKA835OTPH3sahLDOvQ0d5QyRUYwWCVulow/vpjTbcBbdzRw9tf0s=,iv:x7bLuCf6zXMw5uvJ48+KQxroFUX2C29kHfW5tNMFe1o=,tag:2zYgqCkcFkHqZBuPnqFTWQ==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:wVPXxvFk75bSDns9iUgB0Mv3kiQWuBm57pdqqrLfcz6Q1c6wWm4pbRzYHMc=,iv:KaIIr0jbsifPZTkCR5dTDX6l+cXWPF3gvCLN8jwa6Yw=,tag:AzXegRCKfl744xNsIrcvgg==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:Mm/sTeBpqqGh7qC2enhv6HYCCNowAtO1HRmeKU8=,iv:rTVAn2EmNys8EPQS+QzXBuoHV5+s9sNYu0Hwn9d6Wck=,tag:ayAMM2WEZMNG023k2CI1rA==,type:str]
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:x1vwyPxqXKolDIW6wd/6tv3K+Q8=,iv:9tcfsMhuZuANqRMCc7RclzOxYhJydGELgrmrDu2vgWM=,tag:3+SQF6mGgyme46cPtd4Xmw==,type:str]
    AUTHENTIK_REDIS__HOST: ENC[AES256_GCM,data:qcCtAXQzCYLFD/mMfk8BpWw4dDJeAb3Uf+tORVU=,iv:ZEUTvhSchMd4eiIk3bL6aefUTN9iyBtfcmq1TjTO4Pk=,tag:sXauC/ilHkCFJnb9V49nSg==,type:str]
    AUTHENTIK_REDIS__PORT: ENC[AES256_GCM,data:RpuYBA==,iv:3+2AGPOmS4PKswFe5lx2Qd6a/DCGdFaGBPNi762XC1Q=,tag:bm+gNFZquCswaVMy6rkWpA==,type:str]
    AUTHENTIK_REDIS__PASSWORD: ENC[AES256_GCM,data:W1vnMIAPYFp6AQP9bE0UI0ApoYZvde3uQpeadMc=,iv:5kQ1dK+LWCeIYp6cspvYKDYrMAdrccC71M/B+qXdcsM=,tag:j57EJlsF+7yEtp3ROQqciw==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:DBsKj8lKguWCwpP0D73d1aC40zHgy2hrcFNUL/LUNlH3UzM=,iv:a2dJbBjY1tXg7ORCyJg7Zl4zL0X0wlwKBDMgUeDXXJ0=,tag:3Kbfva+KKOPRj925BQjQ4g==,type:str]
    AUTHENTIK_POSTGRESQL__PORT: ENC[AES256_GCM,data:Tzxbhw==,iv:Wd50ziXnEWQpwXrc77lDvs3vUBrOFPFs/rzNzdu0zKQ=,tag:q08B2rLAB6GksEkTdfMvQQ==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:RrYXqdDS8Rax,iv:o9BU08sFVM93EekpC9TB6i0+skdOTujIXEFUEiP5zvs=,tag:+t12hHM0DojqHYjoWx+FwA==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:2IQzHrmx+7J5,iv:Ykm3mzX0ggMpz9muxXWsglvoTQX2OBdBl2qXtE/FIGA=,tag:8Rk2fW6ZBA4EuG/jPK2yoA==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:FjqCLfwEa0vocMZCpINTnR3rN8eKUDka4xlnt+56llakeW5B/VeEI/CtqC4=,iv:gMcwzvVPMD+b9pUVpYjgq71Jo4Os5gYvaiQhqJuBjNk=,tag:/Z8vu9/XBu2THR/cWm38vw==,type:str]
    AUTHENTIK_ERROR_REPORTING__ENABLED: ENC[AES256_GCM,data:v8NgYK4=,iv:mWQKiz7hcbfGnwE5/52ILkCS/uwXTKErL1n3iNUaTpc=,tag:ibjj6JOpOsk13JvEFGD2tg==,type:str]
    AUTHENTIK_DISABLE_STARTUP_ANALYTICS: ENC[AES256_GCM,data:B9x0lQ==,iv:Htp00hkogkRLsFy/VLKeLkcCwlSn/WiLtiA1xvmFF5I=,tag:+kgoRd1mFzdz7hHH9g0XjQ==,type:str]
    AUTHENTIK_AVATARS: ENC[AES256_GCM,data:pejH0IO5HS+SWHGU2+UFOP0=,iv:fENkUS5FUpesBUgNaRO6qDNpu5tMYWKkdRqWZFB6VlA=,tag:OCuzWGpYR3qOTHWIuCYndQ==,type:str]
sops:
    age:
        - recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBN3BUekh3
            MzkvakdoMnVqYmtBQ3BDVHFDVFNQcG1FTXEzZ3lTeGx0WkF3VQpDbVMrckJwK1ZM
            WWpWVWp3aGRrNGNhN1ZPR1lKa3k2K1ZXS1dOL0ZWZXNFCi0tLSA1bHZjMFNHQ05L
            aGJTUlNnTm1sejU5MjZrYzAxeXdqV0hDV1FZY1N2cUN3CkjmD67DKhdqT71tputp
            6mFcVG3STbaxvCPhJkY4NSIQRKr/jMa0WN2SSc4Jtwq+8Yv2nuYFTkZX0sI4aKCK
            OQ8=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Sjc2c2pSenFFSU1VY1hm
            MUU0Um9PT3BSd0dOdXZaYmR5QzU3TXNYUmdRCm81TU04QWg0c2NyKzlIWDNWWmhq
            cy9nSWpEWm43c3R0Um0vdlNnL2M1ZncKLS0tIEYraU9JVDVHQWJyRm1BRUpQa09h
            NlNINjZrSVpvbmg5WVgzYmVpcUZRSUkKSHSQ5vWkqHho2sU/qFjgJL442SHr7jqI
            VTbIKYwL/FOJB3hpBZYKoRUByF9L0bmU2y5awQRHnvHePTfhlZp3ww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-25T03:39:31Z"
    mac: ENC[AES256_GCM,data:tnoSUbgRLMzrlxC+MmRKxfi8jM4pLpjCq5xg92kvceN6xCAHAb6GdbNKJFBZBo/wDWbfXoJgen8AvUWWgS+08NOG/qDU0BoKdg7yOQhVmqKvF6I88YvkgTFe7hQYaIGKTsweUTFkkjBg/Jhk2vArv1FkPnVUJNui65y4yupq+Dk=,iv:5bvJP8IGGJLwXxhzXiWl/dDapIovrZ7neIeQ7u13NpA=,tag:+bIe2zVyne0hUg4QhoxCfg==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsZones)$
    version: 3.11.0
