apiVersion: v1
kind: Secret
metadata:
    name: authentik-ldap-outpost
    namespace: authentik
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:ePgmpeqbBON59UHSOvb0JDknQ6GW0hhusA1+x4YmYn4dsV59cXQ8qIGTl1KPoAuduuit6YkruuZp4iLh,iv:qMmpeKsVOUgorwTNPcEDkSjBeL+s3WvtSZ+eBbdlazY=,tag:OkSqzlKwziLcgXod3KSbxA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBOHhjaUlw
            MXhXOHFQYjlBS2dSRlhZZW9kckRpdzBha2NBSkh2SFRQNGdTSwpyaENaOWpyQWpM
            am5jb2czb09YanVqOTdiakhQVStTUHFBSzZoTWxaUmJNCi0tLSAvMkhpM1RGc3BZ
            Mm5YQzI5TVZmWDY5QmowSVo0K25YWlM2OUtxdVR6VVo0Cih4SQUpk8CmMMzZw39m
            WOo20blyPzJ9K12Zz+zS6HYEQJlVqmCmkTc6cXCUEjSAsOhc8L+yZcaddx1SGEa2
            Ogg=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUktnYks5QUkrTi9qZEgz
            V2UxZVdUbDFQdE5pZTEvWWtSenQ2ck1rNGtFCmdrM1ZDVkZMOHdZTGV4a2hzZGVX
            eUdlS2RYNktubTFjcFBHNUVQbzladWcKLS0tIEc0SW5pbkJlNWczTGE3NlpsR2Nv
            SXVhQkYrQnBXc29Yc3Uzd0o3VWJGbzQKLsYgH+TKJTCTJptXEjC9WyAprZvFZhbY
            VYDbcUtrvJZHLdeH3elUIuswyrTEAarh//rnOscpSNe+Mx6rsRlIPw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T22:30:36Z"
    mac: ENC[AES256_GCM,data:Si+i0GmcsUe2zs0+8rYeGfZoqlJ9yLEmvDqor8qtHIPn6wo609cd30e1D5xdmpyyPlrmLQ1Nq4pzLL326ooQA5LiymkUZsSPPnOdHJZbx+a2+z9y7+Sc5z5xDBP5rjnfK9LAvTWizhPuO5WAXKv3bJ/LycURcYtL8mfFgA9FDtI=,iv:OD3Kzo71mxf2tgrlfL6boA42UnQfEijl5vFsXkdNrQ4=,tag:dC/OCJFbgmfLbvTPPbeRBQ==,type:str]
    version: 3.13.1
