apiVersion: v1
kind: Secret
metadata:
    name: corekeeper-makoto-secret
    namespace: corekeeper
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ""
    SERVER_ADDRESS: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBclRWM2Yx
            WGw1SmNnTlVqdmRTZS9LTFJPUWdQZ3F4b3JRK0dKOWVta01iWgp5MGgwZjZ4SCtK
            Ti8zc0Q5L25KWEVMc05nMm5uUnYxbGJGb21zR0tnRlE4Ci0tLSBic1E1RkNXSWRy
            QUVISGYzUFE4YUV2N05HRXJ2YitTelFsTHQ5SDlQMnJjCvOz2tOe4xZKT5mtkx7I
            cI/8a/00JgKJljFqyCmCiWdboIYpwYdVvclE2nZuh7tpvtAwu20BqqioRPBCjaaS
            oKc=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSYjVQZ0JHbkYrMnA1b1NJ
            N1RkcU9PNTU2TjJHZm9EVUl1VlNPNHhNRWljCkxmbTk2ck1oZ2RXTG95ZFVDT3pJ
            WXRkR3J1NnlTQzF3Y2hOY095a0piRXMKLS0tIEc2ZTB0WERsWno0V2pWRlkzZTJ4
            b0haN3NyRDA3MDhtNnJSRUYzQU9aR1UKby0kNdh/r5NGzDM5wNs8jDaLb5kUPQqk
            XbfZquVKB1fo0dUN56xrVZ7t4CZk/POFG2RhMPdxnWsAvA7fZUW5VQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T04:08:35Z"
    mac: ENC[AES256_GCM,data:0aCL0z8pgxebCQUpUFG7SajHu4C9D5pH1mqeW76GDrGovLKhT3Wm7DA8sagis1Gd0M1G9nr3pkN2/oRs1yBvWJKZ7RbvbQKg5eS6LSAfHwz1P4yusHzph3ukv9Nw0xAReDVmQIev1KB6OMnPR4BTpbHBzmqayjWba+trUe00d50=,iv:L8TtBKF6Atga9UJpBbsvfImAYdNcVtCSk7mJjAIcnyo=,tag:cJnDZ67UXitnOjZgyEFl/A==,type:str]
    version: 3.13.3
