apiVersion: v1
kind: Secret
metadata:
    name: corekeeper-secret
    namespace: corekeeper
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:NNxbKP3jSF5dqnmcU3eK596eRJNLEvWgmUHh+J8627WyMkC+2mwtTx07SyK+rdPStP5fEFy28Nvk37WgSgMXtWe0/90DCDoxZHf2e7Z744hx/u5co5vtL6M1727ZgA9UMdGiJ5as0JNWWEClKU0k8ww0EAYWeqAT7rG8qA==,iv:440UlI8UCnjNCmG+vnqeSZ2YrEVrFcjlx2q9z3lqwB8=,tag:Rh7nPDTlriNiBcgbMlkd0w==,type:str]
    SERVER_ADDRESS: ENC[AES256_GCM,data:n3sdk4otYYaxrmFCVBIENmPlYmBxRgB7ZD8=,iv:FstT5wPFFwJQ+z15EtV1OhlgHkmkyHW9FzH6Fgr05Gw=,tag:u11SPSc36+nfz3O8ydKF2Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBazZvNkgw
            ZlUxWm5HM0U1QU5uVWRaVTBvUUQ0V3hhK3A3ZUYvUm5MTWpOKwpBL21EQkQvY1RJ
            TVRleC96NWppMXgxK0FPSE9lejZXcE85aXFVSDgyQjJvCi0tLSA0WFdPSVgyVTRk
            ancvdVF0WnNWUVRJRlNHb1dFV1JrcnhGRGxXakdFdnQwCtRKr1W2Bym4TCjf4oE4
            S7CO6zvpOq9KUnwcyE+shu7AoFC8ZLviF+ksC76/Yk0msFydRpESI+J+wPAJ1sKt
            dEI=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqemFyNzYzRVBETEI4UlN0
            V1pHeFlMeGlsdk14WnJwM3lydksvc05xUnl3Cmxmd0NYUS93TWNtOUFZT2dhMnA1
            T2VrV0JWM1lxK1d5d01KcEoyS0xOc1UKLS0tIDlSdjdINXU3QWhqZnVIOHV1SHkr
            bW9Fam9Va0p4RTNEZUtmQmpXTkxxRWcKBBWqdRXSWy1nlvNQoxPmLyAroucTWs9j
            4oMPtAJWs85PJ37BBvW8Iw3/EMQliwFMP9r82uqnEzd98t7zE/ulRA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T00:21:14Z"
    mac: ENC[AES256_GCM,data:B7UUeiRj4g8F7nr8XEjZnl8ac2ULgVaDQLojXbmT9rRc7E5PY405RmrRJcORIkAfLGL0XJKnzfgx4yuxuN9T21/kpuTsjwkL/DGzOZ2HACAZ6OivaxHYUJ9+mifLNviqs4bpceAPOUG7FS2N3KGEzlOXKVrCHzDTiFsgRZTeqZw=,iv:MXz66z8Aq6YBpUTtkWH/n7Lzn6uTGltNSZFa8zLROQY=,tag:9B9w2GKsy/kCMgqUFQyMlQ==,type:str]
    version: 3.13.3
