apiVersion: v1
kind: Secret
metadata:
    name: corekeeper-secret
    namespace: corekeeper
type: Opaque
stringData:
    GAME_PASSWORD: ENC[AES256_GCM,data:d9Ofvai7,iv:OmPEfseEYRa216in7h4BJXOdOillXW8O9mucOmYbnCw=,tag:JD1zhNHh1dhhRqkn+Sd0sw==,type:str]
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:eF8nbl5DBtDYOW1r9AZjFHFDB54JfL4Nw7IBY2tYcV8UQNkhG8r4ffpRAbckQqyRlfYp25Ym4gHeanos2XyG4/hFZxXvD21Zl5dVMQx1ggaFj1jy5crebLO4G7GJiROJ4QIgrZo+hkz883uKEhlKg6j8LJgqIXrZj33aXQ==,iv:hkl8kazL7BXwadqHNQ/Vz2Njo1EiKDwxBOUNWAlJHWM=,tag:Nj74s2LWk/E/fKTFob5ESw==,type:str]
    SERVER_ADDRESS: ENC[AES256_GCM,data:dIzsG+8DkvfF2tjbCMHmxFoLd2r5J/aZ60s=,iv:n+ojAgU3o2EyU1dWTPoJm9mMx4XrOYKt1ArNSvgB5QM=,tag:gmqNxNrZhBRmf8K6nJSKwA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBOVUwWmJU
            VEJ1c2t4eCs0NFdrelJPL2EzNFdZbVRiU203cXRzQlhXQjd1ZwppaWphUnpkQTZE
            eDVBdHZKRm5jc1ZJbHBjZS9XUVUyM0hyNVZRQ01hRjBvCi0tLSBEWjIwYU5rcXpj
            QlJNZ3YyQ0Y0a09CSHZSUmUvTDVuaEZzdUNjRWNrNVV3ClueeT1TTOL3Eyo/nRvt
            AFWuRSeykyCW1cOKaPX9yVtEvfqYvUkyUiHPA2hXKaNfa58VU7aKxGb1X629lKv7
            C1A=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjQXQxMG1OVFh0MnNhYnhx
            S1ZPZWV2eXJpUk5lbVgzcXMyZTBSdWk1NUcwCnNWMDdFZnR5eWcyd1dONWgrc3cr
            S2pQSko0V2pPTTBxV3p1eDROWFNXVlEKLS0tIGttSEFZU0cwWUxnMnUvRGdocndk
            N05vdWRVQXFWeGpsL2FCZnlUQ2FmR00KpbJeEOinQdvA9ShnrSbfOUdnKXNcU7OQ
            x5DFZBAP34oJvN0zJlRsIM36vYQZJ2RJEjhvfetGo2D+R0IiUBg1pg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T18:39:35Z"
    mac: ENC[AES256_GCM,data:13fp0jtNjkOSQitjiYlS5TnfZIPPxF3fXqDKizFc4zUiX95B7IdXVxu4Zm8Z114jNGG179XWewy7aU+4jqTcvIqu0YGEdc+kKV0KVfmT+exWS7sWEhl8GSHUBkXKol3RaQsQzbByYROnOSBov+KqRhKXhgBziYQFis1cuqrHwNw=,iv:hXRCuMsOdWs0rpwJY3twBhVq7bK3CzwSWnblCJnLNF8=,tag:QDFjsu6MTUiaqPqeXroW1A==,type:str]
    version: 3.13.3
