apiVersion: v1
kind: Secret
metadata:
    name: corekeeper-secret
    namespace: corekeeper
type: Opaque
stringData:
    GAME_PASSWORD: ""
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:S382Vne+Mu1U/teqdedajSTVaUMOfKc5uqGF/7inSrGCaP0UEbcXgRjjnCX99kWAx2Z+SKdTZH+EKlEoSOPNgAb2ln2+xL7WZ5FdQQGGV0Au/1H3nAPtoocu4Zk2i1Qy8pOr4B4LVSRF3pGynbh00dbXl+o+3h2MDWzBZQ==,iv:JlEat8sIyVqyn3SkwRIGpP9EWuq7DCuJ8+CuFPn8eEg=,tag:BGbicP246Cq46DQLsh5nQA==,type:str]
    SERVER_ADDRESS: ENC[AES256_GCM,data:GThbDvxIb+6gVWs/Vtr/65AiMuGyXDwtdyk=,iv:dQZgo5agqid8kaHUmR0byiTuNPB4oW6eOWKzmkvVj5Y=,tag:zN+LJeJEUJ8WEkxIPJi+yQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBc3RETjAw
            MHlmQzZtSmhTeGMyaEZYbld2NFNEMDIxS0Rkc213U2pobS9xOApiaHhCWkZLYUZD
            bElEcnA0WWpoWm95ZC9DSFdQeDI1eGhGQ2FaSi9Vd3BnCi0tLSBZYVd4TnRPV3gv
            VVczd1BIbE5zZW1pS0RvVDZFVW9HUXZ3dzdjakl2YVB3CsBmjI71eolzJFYTKVOM
            pi+YyPmdX4b/tScF+4dA7yGYwi0+eSg2oEzzxjXsGj74yPGtp6uZCY4Vx0M8wrBU
            fio=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzY0JVQy9pTmxDWnRacDkw
            MWk0L25pRUc5RUgrWWF2UVNyL1lPcm0wSDNNCktLK1pwcUwvd29yeHlUV0NFNk5L
            ek9zb1JlQkROTk9ha3k3YnRGWlNIZVEKLS0tIHhodS9oNFVCcVVxWnR6MVlkMC9F
            S3Q4SkQzb3BBSVRtRks5Vm5zTmJpMzQKUcp0dyS0c9H/CaCPxLK//2F/WQD+r1tB
            Hgr4SBb7pwLDAwLW6NO4d1OBAs+WHD5EI8tZy4zTGezynTdtk15yqQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T17:00:21Z"
    mac: ENC[AES256_GCM,data:8b2HekdBEFM8O6q5J1e4OPvCmtpOPONcvCT5tHxiuC2/5EyyLudu76peMMucVr+okMsKh34rD2NJqDhUYTqrn+3v6f5U1Mi2zr0PT0X9NCpg6+gtoBqPDQmS7BzmDj2oUQnHdvfV/5Mzm7F/RlDnf+4HeHgrzoEYjtyLKwjHKUQ=,iv:MvOxQMtbFmsMIbHQwt1wOmBPd29Fr4C2s8cJpyBnod8=,tag:3N83vja3bewzBwwN1kMwOw==,type:str]
    version: 3.13.3
