apiVersion: v1
kind: Secret
metadata:
    name: corekeeper-makoto-secret
    namespace: corekeeper
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:3qg/oXTFRrB4yvTQSpYpP/Jpyr0P7yByrWH4jFbY5io8n5z5G5PBuLx2//zpoFihfEiItB5kP0xAdnZPXrc8r2TpE5+8HRvn9d05of4m3nhVr1G65oEwE+0Zd1oGoy2wp174MV/8wtBJxcgTII9MLfgmMO3JH70nUeLTKg==,iv:9UeliT8hGfnCgrc+TbGUVgUs/mbr3s769tD1fPuZBaE=,tag:yAt/D2xr/Tl0g6Fx+MvrFQ==,type:str]
    SERVER_ADDRESS: ENC[AES256_GCM,data:KWQ9JOi0oPMCcgDQWKUBK58ziyDFxefi116ZK5Snuk4=,iv:JN554dt27Tf6xIQ2Dc9IWb6nxIB90HyDivSOWNm9WXQ=,tag:S6097zlT45ll7C1b9MjYaA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBOFN1b01O
            akhhd2U3dFJiaEV3K3NRRUJtQjlidFgxRHFYNHpBN0xFek9kNQpJS3hnUkg3Zmdr
            VG1KU2VmRzRucXpWdU9PWXRiVlRGK0V5MjE4bC9pN2FVCi0tLSBXOHp0MnEwdWhG
            QVQvNG5HaVgvRW5YS01CcjJUZUQ2N1BkZjlLUEpRcmtZCrc8dDoVJitFm5Kj4J+f
            BArtrH2/Qc2rxCO8dVq+aM9YmvDIXTe3yNXoTdoXCsC3dfH77/w3qcGkW5IMT4Oh
            lXw=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bVFnTGZCc2JkTlZEMks4
            WnBZNURNME1vaktMOE85MkNCRmM3eFpjb2tJClZObVFoaE84bjUvUDRwZ29pM2hF
            UlhZL05GUFdQZVpQTXlvbDdoL0YxSTAKLS0tIGJ3MmZEbkdJVEpZK0tnTlNwTEd5
            akVzamRMR3ErcHQ2NitpMUFrWEZGZUkK0X6QRguh3kuKDmM59B1t5fqMe1/sUINO
            5na3Fv93fhbyfayPKbWvSgZHQf0FReK+SUY/g5MMmJCeH3BCbi43Xw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T04:22:54Z"
    mac: ENC[AES256_GCM,data:XGVphpP39YVfswd6h6stmo5yVHy31m6wmdb0DyFf32wrbJ/hj9h5fUcnWpiXDooAD0O9GQuBoHtBZjwja22rSt0plBba0yx/La76cyWUJ3tBYHrTtKmPtPlLEBdRDhuiH1Hntk8szxwFyokPUiWmbKdVZCi4uir9xObuJtKY+xA=,iv:pmZGHBFiAixy5ojiqcICRXHeT/n2Iwn4WcF7iFr/4mw=,tag:7joMYP1hTqmQBksoa0vD9Q==,type:str]
    version: 3.13.3
