apiVersion: v1
kind: Secret
metadata:
    name: corekeeper-makoto-secret
    namespace: corekeeper
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ""
    SERVER_ADDRESS: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBaGFSMTdx
            SDNQdjAvbk15UU5oc2RBNWtKOVlSMjN5NmprTEhSK21qUGROKwpHQjVoa3FuTFQx
            RXh6ejFRWHpldW54OUVCbmloWDhnS3V4NzA1c0ptWVM0Ci0tLSBacklVZjRXUVU2
            MHNSRzVFSFZ0VjBWWUdqL0JkMlNwcVNVcUFwVWJFSzhRCoYaKuipcrM4ufFqas5x
            x+GCRdGnIHVnhz0vCNwcCh758378i/PtSZLuTlhLGwa8tmiAf06B6cT/y+pyZtSs
            Deo=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMkYzSERwNkhRaUFUVlJC
            UHJ5a2k1VTM4OUlHMERoYWsybC9GYy82dHhJCjVtak1CNkNPNWl0Skk2TUxETWU5
            STJwem1MS3lvY1QvTFZONTNlUDdkN00KLS0tIGZLMGVTSGVmTzNWTDdwdm1CUmlG
            MUpkNXU4S251SkFDOW96bFVobkZGM00KcKcKsaJz93r6xGsJ/mKxE9B114UCAfgx
            FjYHU2dvsprPaYJUkjdQWAKRV4irtKTEDCbBGH72a79MUtl5i//XxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T03:48:17Z"
    mac: ENC[AES256_GCM,data:rCui+jfgMpddjawJ2pmXl1vTavBuAQK2fZUDGccgff/ZOm79GjtkGvvuPpRqsVzcCg6B6eCo3vqVLUb9zHeXX2jM0g7gQUUZCAQRUCZj7eedvCWpQGDXz9iYJW6KtP+41FRU13MUgcMXh3v3PVVSuJzMvmj80yx0OR/c+dUCXkM=,iv:b15hxT8eOFhGbQoThP321syhebS3AnGUEdk4CGkfzmE=,tag:INfipAdNfK/9E4l0TivvZw==,type:str]
    version: 3.13.3
