apiVersion: v1
kind: Secret
metadata:
    name: mongodb-keyfile-secret
    namespace: mongodb
type: Opaque
stringData:
    keyfile: ENC[AES256_GCM,data:jfRnIF+yMzA7JGxQjvSDcjuaI0Bs2uEKT2zjqcIh/YnqNVPMQxHEtpJ234amku6WOAd99gSka4gnha9tcZYwOQ==,iv:wYJunJGplJ+AaESKeOW6pw/819XlIwLboDkU7nrDh3g=,tag:/QXAtyGqYphWYoxYJlebNQ==,type:str]
sops:
    age:
        - recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBdmg4NkhT
            c2lyOWNGejdMcXFDZ0FSREdKVThvNEJSWDBYekJKc0JCL0R6UQpMalgrRlM3dmNv
            UTQxQmtxNDBGRnFvVWtoMytVTFI0czBXQ2FZVGtiK2tnCi0tLSBjVGJNMzIvZkNR
            Y2NsTmMzZHRJem92ZUV0czV1STdVTTQyRmpLWFR4RkdRCrkMx1/Zg7Gp/D/THR7X
            q+1g+LDpFrrzx4F/008lCkuohS1PAs84N5EtvjE0UXRclThro4SUvjlT1h3pGRzV
            740=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17l8gylyteashptf89ql95e4wl80u4py5ahfzmz76v4y8ghst0qzqxg3npr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZGRtOHZUVWpVdEFhWWpQ
            SWJKV1BVd2xNY1lpelE0K0N5Y0ZMUkJwNTI0CkVZMGxYanNDNzN6RkZkTmU5eEhB
            ZTNwL3IvdWQ2TWFja0h4cFpyL3Fvd2cKLS0tIDducEJTdVhsMDg2RTlWekkyWjJF
            elB3TXpDQUJFRjJTTlEybzJ2N09pWXcKlpVZJhcOdAPBeEXJkEwlKv3AS1nBF1+y
            qFKSYm9YsaDPlP8Sbu5XYBXK8xmC7k71n17vrd0dfrBadkm6zRJRZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-29T03:47:18Z"
    mac: ENC[AES256_GCM,data:CYpnJGeT5eqOQrszrdTBTNJcD3zL4VvIC0qSjJ12lqHGf3lPfb4ijnzkUd9RgX0UmoA1//Y9HnYDJXuyvw23v+m+Qv9RfjLDBE/9d69Ps/TIg26Pvebeejub7j6em0b72TFz+JWFC0ADPpEAubr/C3wO5z+XfhJRhMm06gMjYNQ=,iv:2fcdKOoLZyb//pDBsIJbJVRnA4WVd5xN4q10+p3pVSE=,tag:Cg8REqTU+DsQkDpNNlfX+A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
