apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: mongodb
spec:
  selector:
    app: mongodb
  type: LoadBalancer
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
