apiVersion: v1
kind: Service
metadata:
  name: invokeai-web
  namespace: invokeai
spec:
  type: LoadBalancer
  selector:
    app: invokeai
  ports:
    - name: http
      port: 9090
      protocol: TCP
