apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: invokeai
  namespace: invokeai
spec:
  serviceName: invokeai-web
  replicas: 1
  selector:
    matchLabels:
      app: invokeai
  template:
    metadata:
      labels:
        app: invokeai
    spec:
      runtimeClassName: nvidia
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - bytheon
      containers:
        - name: invokeai
          image: ghcr.io/invoke-ai/invokeai:latest
          imagePullPolicy: Always
          command: ["/opt/venv/bin/invokeai-web"]
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          env:
            - name: TZ
              value: "America/Chicago"
            - name: INVOKEAI_ROOT
              value: "/invokeai"
            - name: CIVITAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: invokeai-secret
                  key: CIVITAI_API_KEY
          volumeMounts:
            - name: data
              mountPath: /invokeai
          resources:
            requests:
              cpu: "1000m"
              memory: "8Gi"
              nvidia.com/gpu: "1"
            limits:
              cpu: "4000m"
              memory: "32Gi"
              nvidia.com/gpu: "1"
          livenessProbe:
            httpGet:
              path: /
              port: 9090
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: 9090
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 5
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: iscsi-persistent-fs6712x
        resources:
          requests:
            storage: 500Gi
