apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sera-media
  namespace: sera
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-sera-media
  volumeName: sera-media-dxp6800
  resources:
    requests:
      storage: 1Mi
