apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-secret
    namespace: seaweedfs
type: Opaque
stringData:
    s3.json: ENC[AES256_GCM,data:2+WQ6NEqJ7t10IiadOM3UmW/gmuU7z6+wuSkk2u79LAOCeLBNadg+J9YWCBVO1TbHJdTUqodCvagoVHjLVbY3+2Icjy4RruQ9ltKdXZlVewSRc/8uXVQ2ACa5wyYk02GISK/TycRwjJkQb6cp9uELqLMPIFUah1DMjkfCHs9Z662LJn9ic/C218He1buJcUEpmuwYibzfBiqvOsrZdm+GHCQ3+Wvkv+xqrcmCJIRrzc+bQoVGLTyrS+EkHq7K1Jq2iQN/+5ODzCTqkuTbazRwdpAK9zEgfbK3MbzEDCMBTn6on/r0e/+Op1Ae5M1eZ0fL2wucsb3THdpxGKij0YgNtA6Vv4LfGXoDjeiId6kIogJR/3MzI2qHiJy9ZagvJOpLg==,iv:7ZpfgAlsatFItDLs33EBxV8sIjx+EMYslW494NxWEwI=,tag:UtylOBv3O8L5tVZNfiGBLQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBeGNTY3NG
            RnVvUlhsQTh0MGZsVUhxZGs1TVZBTVIrYUl0SjVVV3Vvc2kraAowcE00cHlwb012
            cDhyZjV1dDQzaFdUWjIvYmFoUGZwSnJuWTdjQmNQeHJVCi0tLSBQcDZYbHZPaE5q
            Y1MxTDJ2U2xBRUxnbXBOZFR1MDc3bVQzWHNBRmxsSU1BCne4QA7gLR45da2qqSNb
            IHaCxIC3277A0eI0ldRHALGU2k5WZBbp2+YiPvdSB+e+j4k0ZsR0f0QGgMn81Z3n
            6DA=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqb2VYMFhIdzVnZ1pGRVB6
            eHBPaFJ5RnczYS9tOU1VUkNBWFBpTTZ5b2lrCmlvSHBUQkFxQjI0Q2VmSER5OFRN
            VjVWTjBMRzdZbE9VeEVmejBDRnVJU0kKLS0tIHFoSmdCTWtTbWJvNDh6eTlpZWwr
            V2t2Q01YaStOUW1BSkxBa21Xb0ZZTjgKbOqd3PImMbYGKvWJ3pvc2Lb1b9/e39+g
            J+IHhLlIClVRMLidabHHpHju0JuuikynOTKYfvaE8k0cNGfQazSrZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T14:42:14Z"
    mac: ENC[AES256_GCM,data:qOa257aWvUU1vzqlKVF44L3KwTUtMlDif9eE87jVKd26y+/FbPzn1oMPMHGMaWJ+oPQgTvIaM0dAsxxcVr8Imwhs5jZz6iQpEBrGI7bz5b7ECIjQXfEq4efBmrTuytNkHk1ycB7r3FF9zwronMgzonCNtBJPM6ylmP1HORKN4jE=,iv:s0i47uWlVyzYkBVDskunv9UyapKSQ7MiJD0GaLK7Jkk=,tag:PKaM5KG0Ih5TXuyiIf2YIg==,type:str]
    version: 3.13.3
