apiVersion: v1
kind: Secret
metadata:
    name: dragonwilds-secret
    namespace: dragonwilds
type: Opaque
stringData:
    OWNER_ID: ENC[AES256_GCM,data:T+PPyoTWvaW3W8WYndDiV+dngqq9OuqwrqEYYvCwDvk=,iv:VxN+sAHVmmtZFTXnXDt2tWDXM56tQ83/iALOYhV41aw=,tag:KNEBULAIQxm+sYNrtTPB7A==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:hzFZEaqmbpKlOOFpuqgsOrPeSAX/63Fa,iv:SeLQschak6tLyOWs0xVtIao05VwKCv9uyS/wDvYCVfU=,tag:8GPFU6T5vG+HuweejxPOBw==,type:str]
    GAME_PASSWORD: ""
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:ZUZEuQgjCVqa5siaqJ/boCn+ncZfodwEmgH7Rf31R2+rnYasdRqZLLSP9zoYLMCgPWFlfu47elSfWCCE9PX2AudEgOLccEz4P4z/VGJHB6PSeMwHjOCxAEwgFFTuzrP+/6Plv29rQNpKfcrS+12KphB7T2oAoEarZrCqog==,iv:A+UlWROmMH6neZIaR+qdwYJetyasfdwNW/YTo7c6GKw=,tag:p90pFFF21gfBt8I8WlpYKg==,type:str]
    SERVER_ADDRESS: ENC[AES256_GCM,data:V/iq9o/yIPJG/0wgUmJtfho=,iv:IO0aNzKSkDWVRd94I5CotN/ogTmo2yDXmvF6iHW3XX8=,tag:HdCfbSanYEDIyY6sTfwldA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBenZwMkQw
            SDYrYWR6Y0lpL2MwZUNTQ2IreTJWM3d0Q0FuTkRPTzlEMW5qTwpnZCt2bGtCSjha
            OGh6QWs2aVlvbkRuUU0yc1EzWXl4V25VSmFpR1lORzlzCi0tLSBjNFE4a1RzcVZN
            U2Vza3RMM1NvZGo4b2FrZEpETmJRSDRxbW5CWHFxcW4wCskSYrMe4/U2zTbV86b8
            f19D4PG9j+nl3tWX4EL+uw8bGlPSNUhX2ARZh75uHir0Pg8vxdAQEJGiuclj2/BS
            6dc=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKYVhkaGRxM1QzbmoxSmVX
            SWxINXVpamNJZ2lSM1EvNkdTcHo5bGJIcVh3CldKTSt2MlVHRmRWZWM3cE0wVkc2
            cXJqU21VcXV6VUJQSGlabWRWL2RpK2cKLS0tIG9WZ1dmcEFSMTluZHFWeW56eVVU
            Z05XSHlzbEVzWmQzZ2hSaDdUZmQ3L00Kff4TvJ05o8P8Cg/1jxtOrHPb3lkGfndl
            DDiNj5ATfCr6xiyuaB8+XctdqGtbN9F9W+0LDQcJICJeF1vjEy8LpA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T11:09:58Z"
    mac: ENC[AES256_GCM,data:CZItpkLf5VHmII11uLSh3OudBrvE+6YpAZs0Wy6nyTgLsYKvvMxMpv8mURL5xwkTQkKKIIfafmzmiH20I50EaAlKSqgGm/ByUS9Rmo03mf0z7COvugluQhHO6swUofkloJ/rNTFIuhhoUw7HmxQ3vTFBlXuT/oFTRNFj/8cVoek=,iv:s6F9SodIyKdp2gGkyU1Nmbq6kWLWYvwr1SZ2Xsa9TNQ=,tag:iQlZHPwrSmiaOZqMMcplHw==,type:str]
    version: 3.13.3
