apiVersion: v1
kind: Secret
metadata:
    name: dragonwilds-makoto-secret
    namespace: dragonwilds
type: Opaque
stringData:
    OWNER_ID: ENC[AES256_GCM,data:OYo4B5Ayo0/QcZNKVEQkwQ4+shLWTK6RfRgwmSI3mk4=,iv:2SuYnJyb/gtuSg3z8/PePMUpiEqx72voaB4yjHdf82Q=,tag:zga3B1TT3u5wRikQxJ7Cgg==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:8ktN9BBBHBLSoXjkLYb3duPbPU/Ajojy,iv:Q2qYmmGs4z9A3WtZqHQOH+NO2Pm7ErHq7yOX3EGTC1M=,tag:hjTzvmut/kI5zcFzNhRi7g==,type:str]
    GAME_PASSWORD: ""
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:tOvYimbfN7xEvzOGU9HZLpnijnHQareDnUmeFy/DdccuDEc46nPmTH9Ch6sM+ChkMTfN6sp9HphoRkEIN/dtsD7UqMuXA/FsNrH+Z8Vp37dDIqjegRfVVonHq0nYafar+3CDfxEAcFDlEXcHUH2rD5lCagO5xAtqP1k13g==,iv:U8Zw1B08rXQtkMoqCAdITOOsikbBTLB1+1KVPwAhtJQ=,tag:oVgtWFSieMj0wOAlq/cevw==,type:str]
    SERVER_ADDRESS: ENC[AES256_GCM,data:hVQWee675t8Yq5ornakbFD0HZWBzlQ0G3vtbkRKpNh+h,iv:ZKbOCm1d4wj7yFrs/5yQ2WPAEsIj7YTRFssE393EMd4=,tag:BKaOhp9ydfwOeRcKu1oqvA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBL2liVzlp
            SE4xOXEvekRxQ3huZ3NhZ0krUS9ESG0vbkpBc1hETngrTGVFQgpQSy8xY29yc1hx
            YXJPMmhTZUFLM1gzamt2d1JEbzVFcFhCdG52OUU5TFcwCi0tLSBXaGc1U0NLb2Mr
            K0V0NWVyRU94aU9vV3RvLzc1bHFYVVFRemRiN05DM1ZFChJJpDwLLu0/kqJpcsWu
            /ZFvRglEGH/4coQcRwX+deMpOIZMKGTpmRMRZlYkCKHzVD5nuHQtwR5meOimoKod
            ksw=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTFpjRHkzSGhGaGV3R3lQ
            NVVmbUFyZDZ6dWdkODZjS1ZMT3M1MG9qR2s4CllHK0dzSkpjZlpDc1p2ZHZ5OFU4
            OTVRZTF3SkhScUhiUW9OVHdWOGNqdVkKLS0tIGZwQUtwQ2dnaFE0N0lCdzExUG4x
            OHo3SjFoWDFBZTQ0WDVFZWZyRHZ3a2sKiN6jcnKGXtLZ4xt0LOKvjw95NVkZn5np
            0ppMwnG2ohXfJgbdIH1nIw2RZKhJSJntCZoc3R0nlMVAz0RqrKuZXw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T11:28:29Z"
    mac: ENC[AES256_GCM,data:b0/Z+y1NFx3Bq1Y0vzzkdzp0LAlLAa+32X6+Oj6XE1fY9IqO8eLIy3OdR6hicrw8qOte91OH/UZ1EFN4umphxeN1+RzTjhMHjJEDufyCYw+i/ogVbx01azbW4Uyp/n3VMiA8qAz+WtUyVP0T+OWhXlAtBj/XsI0wDjLIU6ZR+bI=,iv:rhqlcAIgz+WbrUxpTLD0SXuYKRi1rhiVz7Uvx1kHSGI=,tag:vOs7RJXcF90SiWf1beGzYw==,type:str]
    version: 3.13.3
