apiVersion: v1
kind: Secret
metadata:
    name: dragonwilds-secret
    namespace: dragonwilds
type: Opaque
stringData:
    OWNER_ID: ENC[AES256_GCM,data:JsdKiRnpPU5yA/FRExkJZI15mw7sPKoLvXVUEVmCXG8=,iv:LToM67qfgfH1AX2Hs/TsXUVt6WDXMlc49gFoYAmQfJw=,tag:HCPlrOQ89XhTHELKq+a4Zg==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:i/k9k+/0s/yb4Iduu4p7vTkeZDioNpIx,iv:3sXP/6KN5NLqshwFS9ukHA8leo8pogCzLgeWKoIDibQ=,tag:OrCqz9BpamIBtvYQdZ29Pg==,type:str]
    GAME_PASSWORD: ""
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:ARbpEZ9eRxHtCm020pedbDNsCZbgzfPdcyYlAuXK5gI7rYuV+WDUAwul2FFk6WFaREpiROcFPf33U4/C3a+IplwatpFm5wfN7zRh2vRJJtlPKjAXimjTo/cqyxqixcpsFMNP/vUdL9Pe1vLP2WJekqMZu9aFZ3JsimGNcg==,iv:/HHj0k+nunCrogv6OWugTdtZSeYeBY0xDG441TOmyTs=,tag:Ze1NF3Ahyw+JLW0w0fbITg==,type:str]
    SERVER_ADDRESS: ENC[AES256_GCM,data:5hM+ikTCAS6/uip78Syu+XS14YcJKfdK9ycZ,iv:YELgpq6bLipSaUL1y7XgFwPapwb+0eRGsHM8SXtjAWQ=,tag:QAY7che/kgtaDOmskgfN3Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBb243V1Q3
            bGlPQk92ZnMxWEg1ZEMwZUVDYXJubmFzRnQ0bmR4aDN4c0QwUgo3eFp1a0d6djl3
            bFBDdm9QZ1ROaDVlRXIwTEQ0RnkvaHRDWjN6b1ZtcUNVCi0tLSBRdXR5RDloTm0y
            amhPeVhYWVVmLzRvS2VmYlh0dmJIOUdYeTQ5VWZLM3owCrzp8/YOzW8T5l3cbi60
            Qv6I82WPDAeC2rnIos9FyruRrxqKkgrWexjNt9wC3OTaGDJ+dIh8cdhR3OTB5LR1
            tME=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRL0gvWnRRVldmckZocHNW
            Mm9wcC9GNzNuOXRtT0w2Wk96NVdWM0k2TDNJCjAva0pnYU83RFpZUkZkSysreFBv
            OXVrM0Jtd2xyMlg5ZExnNEFFdlpTaVkKLS0tIDhRbkRZYWd2MGIrS3ZydnNzNXRC
            c2cyS1NVVkJRczMrUG5sdFo0STh1QnMKJSoaWS2U/91UFuu1ABjz31g2PQslgf7i
            ud60rf1B5kivg3uRDC0KoN+8A3rec5DgOiXzMowWCmp40iajRDTdjg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T10:23:53Z"
    mac: ENC[AES256_GCM,data:JmifTMoUbmPAeKdvpqmzc6AnXE0Q4WN3yiI5EscrxVKaMUCJYgggI9978VT8OCR0PixEbGYT05z2Y7tNyNL1FvTEA8HQn1w1beppUcvkz24WfuZSvKc6lJQmHW1UvX+fcVEQY6PrUy4Wp5jsY50gZrXkuyNEHyy/SZfBOTs5Z2Y=,iv:gdk1rj1HWFkjbz0V5F/9+81lfQqCR67hNKB5pUGGTDI=,tag:nQ2viDdYBeffuB61lH46xQ==,type:str]
    version: 3.13.3
