apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-configmap
  namespace: mysql
data:
  10-create-admin.sh: |
    #! /bin/sh
    # Runs only on first boot when datadir is empty.
    set -e
    mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<SQL
      CREATE USER IF NOT EXISTS '${MYSQL_ADMIN_USER}'@'%' IDENTIFIED BY '${MYSQL_ADMIN_PASSWORD}';
      GRANT ALL PRIVILEGES ON *.* TO '${MYSQL_ADMIN_USER}'@'%' WITH GRANT OPTION;
      FLUSH PRIVILEGES;
    SQL
