apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: mysql
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 9
      containers:
        - name: mysql
          image: mysql:8.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: data
              mountPath: /var/lib
              subPath: mysql
            - name: mysql-init-configmap
              mountPath: /etc/mysql/conf.d/custom.cnf
              subPath: custom.cnf
            - name: mysql-init-configmap
              mountPath: /docker-entrypoint-initdb.d/10-create-admin.sh
              subPath: 10-create-admin.sh
            - name: mysql-init-configmap
              mountPath: /docker-entrypoint-initdb.d/20-create-kestra.sh
              subPath: 20-create-kestra.sh
            - name: mysql-init-configmap
              mountPath: /docker-entrypoint-initdb.d/30-create-temporal.sh
              subPath: 30-create-temporal.sh
          envFrom:
            - secretRef:
                name: mysql-root-secret
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 6
            timeoutSeconds: 3
      volumes:
        - name: mysql-init-configmap
          configMap:
            name: mysql-init-configmap
            defaultMode: 0644
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - voideon
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: iscsi-persistent-fs6712x
        resources:
          requests:
            storage: 5Gi
