apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: mysql
  namespace: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  podMetricsEndpoints:
    - port: metrics
