apiVersion: v1
kind: ConfigMap
metadata:
  name: node-local-dns
  namespace: kube-system
data:
  Corefile: |
    cluster.local in-addr.arpa ip6.arpa:53 {
        errors
        cache {
            success 9984 30
            denial 9984 5
        }
        reload
        loop
        bind {$NODE_LOCAL_DNS_IP}
        forward . {$KUBE_DNS_SERVICE_HOST} {
            force_tcp
        }
        prometheus :9253
        health :8080
        ready :8181
    }
    .:53 {
        errors
        cache 30
        reload
        loop
        bind {$NODE_LOCAL_DNS_IP}
        forward . {$KUBE_DNS_SERVICE_HOST} {
            force_tcp
        }
        prometheus :9253
    }
