apiVersion: v1
kind: Secret
metadata:
    name: factorio-secret
    namespace: factorio
type: Opaque
stringData:
    RCON_PASSWORD: ENC[AES256_GCM,data:H0ZmpKSs3Mo/XgEwBCPGlArAALxroxK58I+tATZwHp8=,iv:d/hIqMWgsHZ7HHQtLNUWc91EeYTxJCF9R5t3ryO0Xi8=,tag:m7IO6GLe52D1+6c7kM9Wew==,type:str]
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:LT3z151weMoFqZpRBnjGlSZ0q3JrgxZtvezOdmTvuFz4JJ98DRapBRfGE3CAldiW2hfuTozL28DrUyaGgieRoiT7guTGWZwLNZodlJ8bWDbw0DJlH3ApDhHKwXw0kH4BHDQNITbd9L5YhZgLK1EWJksH0DLeYv3oEH8ZoQ==,iv:gv/v49xv49evDw1gD/d8la/ZnJ77ehB3oHpe9VfqaH4=,tag:xDZeNWeHses1vPnPyczs1w==,type:str]
    SERVER_ADDRESS: ENC[AES256_GCM,data:sJP/NiCpmTKxfkbI8Oud+iKayDUV8ds=,iv:3NLwnM0vkyoha9ARP7HSSqYuIzmicoeyJeZKMLB1J0k=,tag:e8iBMwaVnNAaIW7S25sJ7w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBeFlibHlG
            SFJ4TmJtOVRWaFN5b0JjVEV1eWN5K2VheU5oSTljQnlyUDBDSApFaFJ3OE1lVUVJ
            OEVYNFZsamdOdEJTTFJiQXNZN2cyb1BPc2ZIRm05djNvCi0tLSAyTkdzUFdMUUg2
            NTFEWVBoZEcvOEZlQ1Ryek00cS8zbGtCRDQ3Z0dsM1FVCgWrm44zFDO8jZFoDZGo
            JycAD7mjrCRsXqy33b7PCvVwy7bG9laouS0gQHxkLEqeOSlBGBFsijJXao12KSCI
            Npw=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRklCTzFCMU81ZUFVVEVR
            RDR4MzhnNXY0MjBqQ2hFNVM0S2xsRDg5c0ZVClc4M2Q4a01XV3gyVnIvMmZWR094
            SkRoKzdNcVZ1V1piOUJab0tta0ZiYXcKLS0tIG9jZ0xQd2Z4UmUrSTBKL0UvQyt2
            bEpMVmFVTGdnMHVkK0l3NmlrdmtnNk0KEgTuRAs8OqKPpuO5zThzJYJTgfC8zLOu
            E/u+RMS4B33Kzev3SVybrM2Gtn4tgPnJ23N3/XyQVhqL8LQmuVxuqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T04:29:36Z"
    mac: ENC[AES256_GCM,data:LJYhuPstGPIls5xk0I+SpRKJzbey1TXkquVxX3Ux8bv5mzF3xtLVoLIKHZ6ApQM1qx1uJTakVK8nB8Iu/2oTj/bgIm0llX+dnQiohWvfleVqWpNIJX8fSSy3gLkxKGuLMSGyB72PmEMtpI+cwFHaqLGB+aF9t3UETvByMW+sS1M=,iv:3lKZ2GW94VnzXVKSon7bnaSPJoSzA6OwRYCU9gtHkTQ=,tag:msBSiuwAqe8X/RJJdveRtA==,type:str]
    version: 3.13.3
