apiVersion: v1
kind: Secret
metadata:
    name: factorio-makoto-secret
    namespace: factorio
type: Opaque
stringData:
    RCON_PASSWORD: ENC[AES256_GCM,data:X+7EwfS5iRLsRIRbLSIKm5QJk1MZzTnDPHONaBWnruo=,iv:AmDNy1gy98je9JnPAfE/EvtOmp93u1B9L+xjo0XAudk=,tag:7SN5TukEo2Y1scLRisEVhA==,type:str]
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:09kPO36UcrbdE/AwCtn7Dm7zyTDMeCfunWP++SMXovNHO9zkCkGl/cek/1xyEQ22mI+ig/w0lDDBXFF8iATnNLk+V2kEo7454ni1O6VmIGXlPEhEJJSHp4xa42iSo4CEEppOmQnV+KQoVO+YChRPeQHGWXoZQc2sSuACGg==,iv:GweVkc0NkvZcvqWRoGWGbPVLDllQwbwGZkivtqcDfTI=,tag:Xcm+LYcFDLu8aN6J2LlOag==,type:str]
    SERVER_ADDRESS: ENC[AES256_GCM,data:tlLTizbGnE5sghdERmwOeT5ptCjfY8niO0IUwzE=,iv:RDoMdZsM/31MZBXcc7oXZQ8DQ4Wx6mgq+STjND86FTU=,tag:clKr70jZAlzoIOtFsPjCKA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBcm5DUC9u
            Y3NveUZZM29QbmFPYTd6eVVjWVU3UDEvaXpiNGNPcXZyVDFnMwpPSUhOTENiWENq
            OTZNRkJ1bTBoNEVpVHNCUzExTkx4NHB5eEpSR2pvOEJNCi0tLSBYcTdMRnduVVRC
            RGVZS1B6bmNPYkdKRzZRNE4vbXdjb0R0NXY0TGIreU5RCp1kpg8sFq7MJDya8P9u
            SqM+mTI5NLcVzEPSosdT7/PDAHuYpCacB0Squ2HrpMyEEMyvnE91yE/xANnFhiKa
            qs0=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TGJzdnNhZXZwdG9RQlZ3
            Wk96aHZnclpNSG53RllGcndlN3BWc3NLbzBzCkZkeW1EajhhU0N2d1k2eWJpSWJH
            NzkwQy9uWUtLa3RJdHgzVmM3MFplNjQKLS0tIFFCN0k0SUdZODhYdG41SENoczg2
            WGxBc0pxT2M4N3ptZGRnUnlrL3hRZEEKBI5UZOnR/nvU1QQFcRPHtOQouT7NX0zh
            4V44U/sY7IzXfBSqGaMgB2Qen0Xbpux7Q3drn1tQZIWt+1jQ17BZrQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T04:29:36Z"
    mac: ENC[AES256_GCM,data:xPkivawEI2v475UH08MSaJzQ06/Z6jNerecJgunBrxVFXX4W8DKNgfECWuAL3jVuPhuEUQDruZ/f8lVKDv5OhYwb2YG/Y0iETYQUqJ2KD1FzmOU+TMoD2TA0IHazP8qJNt2SVatLwOzJGaNZbccCqrGidwhJApvwba2xn4v2mGI=,iv:pKGyUu9bi02UE9pD7KoQjLEwRKsnVa/OqYmqFbjzjng=,tag:qncMkZj1+fRByCXuqCJ5WA==,type:str]
    version: 3.13.3
