apiVersion: v1
kind: Secret
metadata:
    name: factorio-secret
    namespace: factorio
type: Opaque
stringData:
    RCON_PASSWORD: ENC[AES256_GCM,data:SKdbIZINjJRWeq0AYpCui+RnvgqEtyZacNCu5VJd3uc=,iv:Tc8Huax+ClwAN6+Lrh8rQy7yn8figIkV724NWaAvJfU=,tag:uxypKD43SnXlZ/0FY1YfnQ==,type:str]
    USERNAME: ENC[AES256_GCM,data:F4HdO1eRHiMw,iv:w3DtfbSoYSVjJKFYOfwrF+UNpVhFtGEANEnBM3jQ1Ok=,tag:YPZfc1i0DqdRSqbc8mx7oQ==,type:str]
    TOKEN: ENC[AES256_GCM,data:kyagEctxAKEtpmclaB0DOEE+DJxnWz91xhY/TYdi,iv:UT3G7aGoTsBjNgbf51NogqFzxEjcDBAvbn6NmUmmcOc=,tag:9bOubTotp5spRdWfmVUE8w==,type:str]
sops:
    age:
        - recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBNitCamtS
            cUZ0d0xLU0F5YU10Q3FhRGVJN0dRbFVMUkkzd2NrSzNvZ3gyMwpjNHVJSW1ONEdZ
            L0ZVdm9ZK3Y5SDNRWDNRalZQRkhEVFBSSlBOTXpxN2ZrCi0tLSA1d0ZqZURzcmRZ
            L2M0NWZ3QndNdEUzYlFKY3ljYzhhMnh4d2I2TCtld0VnCottwQ4hhdK7VZVxU8QO
            3glgplytbGr33SRSgfafdAEusr8A045t7Etw/wrz/p1as83gOyzMuyw4eKc3klhl
            93M=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTjJCZWZZdWpFdmNSZENW
            V0hpcGdQaTdYU3IrUWdWK0NzRHVNeUdiaUJVCkhJYTFpbVh1azV2czlLeWdDMzdZ
            RVdXc2xkVHNHNkR2cXlUS0hFajBCeWcKLS0tIFFTSnRmYXBjVVBvbHN4UjNoQWVV
            OGhVSGZtQVZBVk43RmowUTR3YVlYdTAKDJk4GyXE4VsuJQDmljW5EcYCPEp5voD1
            GFhBJ6wyhYWOLIUbUQhCjoNkrcXzH/iQeAP2Y/REod+0tR9txWZlFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T09:28:28Z"
    mac: ENC[AES256_GCM,data:AcG2aPQfzfWNhTSHDh3ZKM3nDypjM0TGAo8nRay4BcgGYD0b7yxqvVqeON9TGJuNcxT5KfZraY9mmwCc5aH00HuiNbx9amy2XEWx+SSYaUma6NrH0zN+golX3FVh90djWm8Uq4Q8KjI+B43aLlI6gsjVIeZtJO48hnod+14ATW4=,iv:Mcz1dShvm1A1MZ1FxQuOWpaFc4uiGr86PAIJ1Kl4Yxk=,tag:kz2yO/LHYVRSXBbC7xLwtw==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsZones)$
    version: 3.12.1
