apiVersion: v1
kind: Secret
metadata:
    name: factorio-challenge-secret
    namespace: factorio
type: Opaque
stringData:
    RCON_PASSWORD: ENC[AES256_GCM,data:dGzlrenOnw9iAngcuRt4nVNEiWYXVuXC+cWWt4vpaco=,iv:ndpzyF6qIZlD9r5OImSvDOyzGn3wYox5pQAJIvMUWXU=,tag:HaY/wJl6Ca3s49TQZ2Q47w==,type:str]
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:PNbyYQsB2C/WrgBooZKx4+n43pYaaJ4dJpJSnPJF9siCAdiatL1u/WkxP6tIDDmc7EYBmSn7+aaBA7ikakvzhb7cbzzMBxjgLvYlUH6ihLzyiIHzDmMR7YtILPX78xqeW7p/YPiLyfMK65k+U2OVNIIgMf/sMpi1HVJmJg==,iv:rThX00hI+Xynmp4snx9S1xWF0GOInNVcFI//uOG8kQg=,tag:3PbaDhpB/yZEAsD+7Uqsuw==,type:str]
    SERVER_ADDRESS: ENC[AES256_GCM,data:VPtVLJRieWuJ5ouUlsmSPKXvz+tNMlnqZlqf26kZl0Yn6w==,iv:LPcw3KHHIeUuu7yOQ3w2LXBRzXuS5rexTr3hr2i88/w=,tag:AV7+WiwSQ2U5fjHFPkqe7A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBeFFQMjVq
            ZnVxcE9mTS9LVGdIY051RERJVVJlVmM0SlpKeFhMbnUvMk9reAo3QzIyeVBJcFBN
            bHN3QU03Nm9PTnE5Zk5RNHp1eXh6ODNCdW5ra0R3Y1QwCi0tLSBDN0Z0M2gyendp
            blVOY2NPaU4zYitNRU9KOVVwT1ZCbmVvS0tQQVh2bVZvCs1oeleXVCAzTg4+J/vS
            2RmfDB0CV/gfKvCzDwHpryoVcDrNs3Ahh9ElrZAakQC8K2BeJ8dfhJsugDLBC/Zh
            DR4=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbVdxMmNnWGlmaWRLdTFv
            WTRENlJURkxkbHk5TDM5cjRRWVozWUdzSkE0CkxjYnJhWnAwOGMrOTR2ejdscm94
            VWg0bzhQSzFOTTFZTks3T09HR2x4ekkKLS0tIEVBYjk1SENkcmJrODBqUU5Wc003
            UE1QT3pzNnRnKzhxS3FIb3Y4cnEyNGcKiPt0xQXErAvuxT4OXTQA9CUpLXdjSYp+
            fqCeODP/hK24cp6v4m52X6/QRclU85WpAF1PjJYv+gH9q4S8DTqcjw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T22:28:21Z"
    mac: ENC[AES256_GCM,data:pYOK6axyWD0lBuYQuEhrhs1sNlZdlqLx5aaqB4p8THgpetM7PoVAiRG+nXaduI32bLoxbjN9QUsDvC1MiXKakaRZoGsLSYWtnLHEhyvrKQ/Oo6AWMvpcQpIVAzSKPuJl0morUdMjqLVzd2iDGMgrndO8POeEKQu1xA2hgWZAJiY=,iv:PjUXjfOngMA/xDxk3WkR16MHPcHWoHuFWNcD4btDFWY=,tag:1Lgay/2q69O1CHpSxRGH7g==,type:str]
    version: 3.13.3
