apiVersion: v1
kind: Secret
metadata:
    name: factorio-makoto-secret
    namespace: factorio
type: Opaque
stringData:
    RCON_PASSWORD: ENC[AES256_GCM,data:5dJfMHko+U80ConkNDTbPnUNojCB+7sYj2PLr+o/oe8=,iv:MkS/X26q/D204pBLKLlSkLssbVwgyxpe4/8uy+wku0M=,tag:9ZPvr6x23qNDdoS5xOjNvA==,type:str]
    DISCORD_WEBHOOK_URL: ""
    SERVER_ADDRESS: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBNVA5Mzhl
            MVMrMzdvTkdVbjhnZ1EwUUFyYTB2YUppZmVJZGltc0F3bXNvUgpIeTV3c244b01o
            eTNZUWdNSHVtOVY5R3VkKzIrOHlkb2M4WXErTk5yZk5VCi0tLSBYdkhhN2pucy9s
            N2tQQVQ3R2hOeVZTdGttQTFTSUgwRzRhdjRqQ0pvWVc4Cij9XYjyx6FRtlpMhr2B
            P0SlauGhpP/0AkbH+Xiqf33AedC6HsEQOwPnAWBtF2M1bEv0ii///XlNYmGvOU97
            bDA=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZ28rT25QajFNbHJrTEJC
            U0JLRHdjc29RM1gvSHRmVENMREVDNUhVNW5zClBxK0hFR05yYVVLQnVjZUp3dVBW
            Rk9Kd2RyNlhGSnVTdVJqREdzRXJQdGsKLS0tIE9sWHJrL1JJUzhmTC91ZGpXeEZH
            TUgwVkNEU3c3NVJqbEVXSVhtQlZGYUEKqAtBH1uppwVvTEYN5+QrY8QOPHanl6Yr
            36a1iQLSwYxdeiROWkSPXTk2/YhESQhhowpY2j+fd42IgnnARxvNoA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T04:08:35Z"
    mac: ENC[AES256_GCM,data:xnZ1jJNT/nAAPvUnvMM9Y3Tz2MGuuoNwXkFOu/HP9v1y33UpJ0B0fIQhwZQ6FEpi1PCns6k5tOQVUTN7l/j77H1Z9oZS1KFa58licioAme6iNF78y/RrdVu4j9qCy+DOmIzhwM0nuSSQdWVtRV5/9nXqrrWNz77Hto+De7NyLqY=,iv:BOTxQxr7IpewW6pKW9Z6o62iJMzTRQElTRkrPHSD+GE=,tag:r0SbS7zS6Z/QMb7YI2i6pg==,type:str]
    version: 3.13.3
