apiVersion: v1
kind: Secret
metadata:
    name: factorio-makoto-secret
    namespace: factorio
type: Opaque
stringData:
    RCON_PASSWORD: ENC[AES256_GCM,data:mspcjsitKPeJhMDCqwhUWS4wrX9H0eyb6U7Nbt43VPY=,iv:QFFjiYfE8XWowteVuqA+/2p4IsjmH6k0HfoyA4ux1RM=,tag:rVzPy7Ou1Mw5sitl6N5yBg==,type:str]
    DISCORD_WEBHOOK_URL: ""
    SERVER_ADDRESS: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBaVdhWHIv
            VEJ3b3Azbzd4Q3FFa0F0SWZsNDBFWTgrVFlhRVZIaU1nS3VLUgpmTEFkYTZvdTE4
            a0ZNbTZwOGNzbDZLeXlWb2pmMGVmWWJxRmxEZGQyQWtZCi0tLSBaYkFYRG5tNEha
            KzQyMmphbFRxVDFIL1NzR1VOUytUb3l3ZHlVSG9OaXpJCr4n3B8pft2NI7dx+mel
            i9kJdBKZ86mp/8RacKTJu9h3B8v2Ub/DSMKqyS+VqMQKOugXkhfLOOcw/X6bV+YZ
            yQg=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvUWliTnVnZERkekVJUWhV
            NGZmdDNaVlRvUXZNbWtySmpkODVCMFVwMzFBCk12VXlsay9JcDRJK1ZndlUzZGVY
            MmpSQlBXWGpFVGl2OWNkcVN2MDd2SE0KLS0tIFJHQkNya1hsVktsMUNUUlRFcExR
            dWl0dWx5NlVyTGRnTjhhY2UvR1l0NVEKjRYsMgsT3xEJrfIdMnSCOsCAIAcjLI28
            BomlyRSx4GOpLCplcgx8a5th70AQMRjvU7qhwF51w8CebFa0r1aqCA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T03:48:17Z"
    mac: ENC[AES256_GCM,data:0UNmJg1H/aFdX1OSk4q+DYqtWGdmMsp9vwmfl1ptTjEabRa4QaVyFW4W1yvTS1zkhVSwFn+fZpU0jC5xxoyvJJCRVvuFbi6AKPbzNGUb30KQKe/TIMgtJDTwBRiTFZh52/MMG9bDKUZPaTaxWDWWUpy3w20cuDKKBlfir31AvD0=,iv:TQD4XnqlehxTvgMqqMOYe5yEodMU/vi08k/WT+pECJE=,tag:eOIDcUQhx5YLkQgGo0+MBA==,type:str]
    version: 3.13.3
