apiVersion: v1
kind: Secret
metadata:
    name: factorio-secret
    namespace: factorio
type: Opaque
stringData:
    RCON_PASSWORD: ENC[AES256_GCM,data:OBWp/ovDarwIX1NSL9sAGNbUqK4CJpN9/UjlD/negBE=,iv:zskjcJa62eCqfDQgl2CLFWa7GQHcUG7UT+IZd7/B2aQ=,tag:Jowh3Suer5LS9IuKUI4xCA==,type:str]
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:yfKRyeeJZjZCRfpMhDhVWBXLZk0BAyRKrIUeLA8ZIncCb1a4LRDBCcMUfCCzgz4qROGvW/C6VM2hCFqZS26fG+agrjk29LDS8f2AQ6J6ePbCtYx1UWjmKfOG6UrQvdy/T53L/cHDHRGUmBe7wzKyYLZ3oUPgLleFDVylYg==,iv:B0o5HufzqiXHkZkxtErdQSQckNDX5U+/q5sWAkckhQk=,tag:NtkOO2m8lCEhNiP1H6XAEQ==,type:str]
    SERVER_ADDRESS: ENC[AES256_GCM,data:bZim9t8XORUUU2rDar2MiJd8AXWCObs=,iv:TVO7VLBr26b7nA6bzOkJcoiss8o4Xls7lplE0G5qi18=,tag:YvMvHpdI/04PAKA4xVPsLw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBMWF3cXFI
            L2hiVEJKMmpvbHNteTlNNzZ4V2VzSnlockRZR3dOY2taR25FWgp4VmZDK3p5TDlt
            ZlVuREZUMzZBWisyaHlTdENacXlmMXBrc3p1M1U0aStNCi0tLSBlZFdPc3RKR0xX
            WEJ5a09BSlFZWGlwRVdvTDNHeHlwU2k3TG00Q3ZOWFNFCqQFETvKZg1F9IYNayXn
            AjyHsHgxY+NnmwAuCkUuPWpzbdtW6pY2Wx6p9vY5oDNKZBO29pV2aBOqhn6VX16j
            tBI=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXU0VtcTNrb0R5a2xGUFRt
            KzRiakI2ckJaOHJSQkc2OWk1SnR3R21jTmhRCmpqN2F3Z0xwdDRVVTRkdmlxVHdU
            c0ZabXFUek9zdVd3YjVSR01ZQkloTUkKLS0tIGtVcElmYUw3cVpoWEwyREJJTXMw
            WVBzTUVhRWNXN2Zsbjg0YWRJWG5CWUkKV4mtWhKMmtNyMbJINR4TaUOHrqnX26zJ
            JJgNskOGVAKpuO9lN4rwC5ZjIr84UIEEwZVKOFtsxVtM6+gP/YyWDg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T00:21:14Z"
    mac: ENC[AES256_GCM,data:GLgE0Zwx7Ehx314aGd27/vFVVMy1HnX0wx/QyudkMeFgNEZzr/2jxdlzN64aPNEbK33OTzZkKsZDCoq6Zi9sOMWOVRxNJADRUB1VUIp1TdFRiKWTOfmOj1H+1cpUKfGMCOSu8JaSElIkqiReQuFiIZ69PaRxTUACAaqk87GsItQ=,iv:u4oyf1AhqyQMfsmP6uaqbb9FqIcL1FSh6Ko0PYNLhgw=,tag:q7iT0zYoemln8MhteS0iFA==,type:str]
    version: 3.13.3
