apiVersion: v1
kind: Secret
metadata:
    name: protonvpn
    namespace: qbittorrent
type: Opaque
stringData:
    wireguard-private-key: ENC[AES256_GCM,data:06U5lisWSpCWzrn3k09LggasrjEmMp78k/KYiwcrI3U7cDxySf6LudBH3Ns=,iv:97N7YuXaNnKT9Bh9YP1GP1MUhvKMp3weJ19Mrfo7yBQ=,tag:sSG0QzAq+gRiRUhqEy/3cg==,type:str]
    wireguard-addresses: ENC[AES256_GCM,data:YuNg6rtyWDZmZ58=,iv:sfOzHIsi4HCq5qORUpvCRvOnz9CFi03EzzJcC6lg/b4=,tag:/lDknE4w7YPfjZwXZrdF1g==,type:str]
    username: ENC[AES256_GCM,data:PJ9BE1rPpbOx,iv:6FdYkExPAIrycA2KlmQLmkKkP5GJGIHEQip3IeFe4mU=,tag:XafJIKe8OgbdUh6wmM/DHQ==,type:str]
    password: ENC[AES256_GCM,data:3aK7IZAiOrybbB6kutJmbQoKHmJMWC412MYQ9x4=,iv:mkGHHF3nPt4y5XvUvUSKJ+LvX7g72HC6ZDVWPIsKed8=,tag:0tMUFrFFAFV5d/gLjyVibw==,type:str]
    server-public-key: ENC[AES256_GCM,data:xSrQyxiBF/dmTfNQSWFpvv5n5gWUg3RBbgE9Kjeth073unM4w//BTadUIVU=,iv:C7A3oEu9FZhyMzjf0/mQb/E4w7QIPhpSLiwxqVe7nEA=,tag:gsX8LjBkLf0fJuzuD2gbVA==,type:str]
    endpoint: ENC[AES256_GCM,data:g4R6audkeCU0ymXKRvI=,iv:+TLN2NVmYgyOgTTdBpntNKGUUywlT6Qa7/M/JfbbZ5E=,tag:UquxaOfkEfIf7lbZk/XsNg==,type:str]
sops:
    age:
        - recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBeU1NVmZ3
            WCt0emFaZEhmZ3oxT1BqeWVvU1BzRHIzRHkwVlNrR2hVd2lmNApyN2RqZjEyTlk2
            ei9FTmZ5VXdFbVlkYXNPK3dQNHBNV1FxYmVQZGpqVmhRCi0tLSBjRnlKUEVramxR
            Q0ZrUEhiRlZxRkF5bTdqNHNsVnYreU0rdSs1TXVqWEljCjyWay4Vc5BlZEI07RO2
            uck8Vrd6xrd52Sj55GDW1gBa9BAG48aFo0ITXEwqkqzXHyzaPJ4PQalvjq6mPiid
            qnY=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNQnpReUV1c3Y1Sm50aVlD
            L0VPYjZMS3Z4TWc3SjZVaFB0bm5YdmF1ZkFjClJDbDVNRnplbklyZzQvdytLczB5
            REdUcXRyWFdnditVS3luTVVGMlpESjQKLS0tIE9wTE1TS0cxTURyS1ZtMWpPa21C
            RlFKa1ltbW51cG1mOTY4UkhZOTJPWWsKmA5n9IMjH+68AXjOxsATfNbOQopYmEti
            LsBOsVToCqCWQdh0gfgWSQ4K9yGOiiDq5q6JQvm6azpxtWKfV9Tcsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T13:04:33Z"
    mac: ENC[AES256_GCM,data:ui1xvaxGCH4WdfU1g5Lw1/9XSUAPLXBLq/YAOg3OIQw8A3BP8FYUfvQHJfxmXegLvU7bBQlL6yeJmJ/ZLUEZZ6kaUE5NJP+aA9Tp0eyacy+e6U644PHCf36o39AutzcHkNVrcvcq6I/mnRn4x+tQM94+oAF0IsnrvzExnr8brpM=,iv:dI66S5ZaQpi9Oo0CU64+tNpkGMPrU8dEPwKH1rQTip0=,tag:lS/yyxlOqiDowDOau8rQTA==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsZones)$
    version: 3.11.0
