apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - factorio
  - gotify
  - invokeai
  - makemkv
  - minecraft
  - ollama
  - openclaw
  - plex
  - qbittorrent
  - sera
  - seraex
  - seraui
  - tautulli