apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kestra
  namespace: kestra
spec:
  serviceName: kestra
  replicas: 1
  selector:
    matchLabels:
      app: kestra
  template:
    metadata:
      labels:
        app: kestra
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: kestra
          image: kestra/kestra:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -c
            - /app/kestra server standalone
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: data
              mountPath: /app/storage
          envFrom:
            - secretRef:
                name: kestra-secret
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 3
            timeoutSeconds: 5
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - voideon
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: iscsi-persistent-fs6712x
        resources:
          requests:
            storage: 5Gi