# Micrometer exposes /prometheus on the management port.
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: kestra
  namespace: kestra
spec:
  selector:
    matchLabels:
      app: kestra
  podMetricsEndpoints:
    - port: management
      path: /prometheus
