apiVersion: v1
kind: Secret
metadata:
    name: headscale-oidc
    namespace: headscale
type: Opaque
stringData:
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:I5tfqLosKzaARgjYEsCmsHbemvnVQI1e/hFIez1hq9tOg+hoIqyjI7fOj34VDJAeFVHl3UCEUN7K8t+PumJgyQrp6AizOzAl2YeX2YbpVdU2xYKuJd+CKN1rXHoTQhsp84p3xNsgwpxFTyxNq56mT20XCb2pl/qeN/eDiM+Ij6E=,iv:hpUHelksj2mGpCAujf/TRxCiourDp8juWuY4x0Cbn4E=,tag:nv33XfzEzIjXusmfloGpWQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBdUp6bHFC
            RDdzaVJwQnN0aks0TUcwNlJQbnhIVnNpaUh3TlNrd0RtWEkzeAo1SkpoV0ZQUjVh
            cDN5MmxraHRFajkzakIwd1ExMityYmJ3b0luamVVTkx3Ci0tLSBUbWRPejczKzd1
            ZTE4SU8zL2RPbm5WMnRwTzhXdHVrSkhvV09ZWlpjTmJrCjQh7DP8AMK9L1s0qtpV
            1WtIjKq52g+ijiz0SL3ZyCxQSyR1rARnFmAjmYjH+iMrzOMhGqI18Qv99uTLhnP0
            6J8=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNnRVT1RIVTFzTVVxaGZy
            a3VaWlFkWGpLWkNnUDI3TURBUlpIbFh2Rm04CmF1dkx0WHkxZnBwaFUvYTVya0dK
            SHgrUzRJTkZ5RUZobHFvaWJzTmpKOUEKLS0tIC96OEV5ZHc4LzJSeHJXcW9IWjVj
            TklJTzVlQ3pSWG90Nk1iZ2hWbmpYOTQK6wF1aOfc5bNBuaq/IFv5QF7LtAamNgxd
            jHERkwwiXgVaP3+y4SpfHZMJQ9hr4Rzq/HlkH/AjGHy0e8N0N9NtEA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T22:13:53Z"
    mac: ENC[AES256_GCM,data:wux0GZePCoJatVDmHhmigAsPWoA0BXNjsiIf6WmUdS0QnX0n8jcPdYdhMUGsblXvRWjqYEjzhFKidXeCZJTt7qunkfsHNfHCczVW5kUsffC8S2eW816tAKQ5ENMFK1mZdtPexL2zB7Et20dSUtCXU0AmV7wxB2tzzky1nkR566M=,iv:Em+NBBubrj8i+mz8qI6eqYPGGbxZS3BmxaXSHAW359M=,tag:OoO1cOAsyV5PRUn+dNeaGw==,type:str]
    version: 3.13.1
