apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: redis
  namespace: redis
spec:
  selector:
    matchLabels:
      app: redis
  podMetricsEndpoints:
    - port: metrics
