apiVersion: v1
kind: Secret
metadata:
    name: qdrant-secret
    namespace: qdrant
type: Opaque
stringData:
    API_KEY: ENC[AES256_GCM,data:mU4VhnsjQNzUrnaAVdNgR69ipPQigD2Izfj3WXPskmbdanij878pOWn/exxyB7vlsU55NcuWTW7WcPQ/UzSUZA==,iv:SdaD+cn8ydr/pIz9F3jUXstwPFtxWW/waFj5E+qDvGk=,tag:6i9+VR8icjUFCXG70rRdxw==,type:str]
sops:
    age:
        - recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBNnVyOFlV
            SFMzZk5oMmZQc3h5Tkl1ck15R2NIbFFqVUIrQmJ1NUZ1cnlFbQo0RHRhNW5oUGU2
            V3VYQmlNOGJFQWEzMExmSHB6dkNLQ3pDZzBHanpSdHc0Ci0tLSB0T0llOUUzMzFD
            MUg0SGphQzJjZVhmOXNlclpRTGwzU2gweWVCWGlPM3BZCt41ztOkckpyP2FAZY7T
            uUD19dHIq1R3L1hgoSLqdPeT5Tz4xsjS6Kb0sRoSySyTYaZUyuV8K1CChSw4RcQI
            ozk=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMNWc5c0JZMFNYUlJjeE0w
            WkZndGdVMy8zWGY1ZWlUVHlQdzNCV3psWFM0CjJucGE1NHQ4aVhkYWZmRGR4ODNy
            bzVocTRCUXArQkplR0lPS0hVeXlrNGcKLS0tIEEzQUxmY2plazRHcXJnOE1Qcjdt
            WmJtc2xWc2YvZ0tvVU10Z0YwNjRnd0kKvg1xxlaSsCnTKEh3hGYQZcnVn5MuO1+C
            Pg2RGpBgLmIKYYxd7sl7k/c171lQiHo1KUdS6vsnam938ovpvveeUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T06:38:06Z"
    mac: ENC[AES256_GCM,data:Rba5GBhrLqNVH6FW5+RD1geZi9rrjtN2AgZHqH2aUKAJxMRF+n8qd3H5b/vPgnFMrfDYrYgVMd+MQs3lYU9Owi/4v1/z3fds8vLSuJ7lFV9xKI1XuBLy13fHLGE3RGa520SZuuVSjpM/xTedX5GYRK98uobw66Qb+nNop58YNs8=,iv:9BdhQwfC7Zu/CsUS9PeMTRYb/JSjUFCOhlXaaDCpjpo=,tag:T1uQM3Eucen8n0KO6b8osw==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsZones)$
    version: 3.12.1
