apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: minecraft
  namespace: minecraft
spec:
  endpointSelector:
    matchLabels:
      app: minecraft
  ingress:
    - fromEntities: [world, remote-node, health]
      toPorts:
        - ports: [{ port: "25565", protocol: TCP }]
  egress:
    - toEntities: [world]
      toPorts:
        - ports: [{ port: "443", protocol: TCP }]
