apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflare
resources:
  - namespace.yaml
  - secrets
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ciliumnetworkpolicy.yaml
