apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: cloudflared
  namespace: cloudflare
spec:
  selector:
    matchLabels:
      app: cloudflare
  podMetricsEndpoints:
    - port: metrics
