apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediaops-media
  namespace: mediaops
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-mediaops-media
  volumeName: mediaops-media-dxp6800
  resources:
    requests:
      storage: 1Mi
