apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediaops-media
  namespace: mediaops
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-mediaops-media
  volumeName: mediaops-media-dxp6800
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediaops-media-dxp4800
  namespace: mediaops
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-mediaops-media-dxp4800
  volumeName: mediaops-media-dxp4800
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediaops-asustor
  namespace: mediaops
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-mediaops-asustor
  volumeName: mediaops-asustor
  resources:
    requests:
      storage: 1Mi
