apiVersion: v1
kind: Secret
metadata:
    name: terraria-makoto-secret
    namespace: terraria
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ""
    SERVER_ADDRESS: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBb2cwczlh
            WVJPclk3bWNIOTJTUjNYUDh2NjdRU1lzcmNCNCtKbFlxa1l1ZQo0WlhpN01JOEIz
            eEJ3WTJpbG12dTMwTzlGemcyZmxhOUZocHVHWVo2aHhrCi0tLSBCSVU0czJJa1A4
            bXdVYWU3UCttR0MxckM2S3h2VFFBUjJjRW1EMm4vSkRZCoWOo1gMeAJxlFpkpr58
            ZFeUpzqlThYJE5D7NvB5Q794eUPdtR3LU1a2mAUYhqUi6+uGqqaTbXKzxauS8N9H
            Y3g=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwKzhUamh6czdWU0lpMXp1
            WG9ubVo5MG9NNU93cG4xUjVJNFhNRU51QlIwCmcvYU5jdWV5SG5McGFML0dvZkZ5
            bHM1T2JqMTZlQlphYW9xV09tNTdYL2sKLS0tIGFVdDJLUVZDOXJ6b3FMZ3grZ1BX
            YlI4NUZHNGxIb1ZYL0Z0bllVdk5OTk0KmRoPF4TDo/aburFvRJhmG16OEA5xsm2i
            ew5D6D8U+QwXq6oQssG66nymXQSI7H02wvIbgGk7/Gazo1Go83WNWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T04:08:35Z"
    mac: ENC[AES256_GCM,data:NN4N2cnzt5EfLIjD89WcOYsisPqYDm504qquZKncEsun/YS46aQx0JDsEY7IqdHAlyTXnVcwGv8kki/lg/RjI3KT9zf4VstLKOYiLxodLvlCO+9pzTnt2CU6yVh3z1aXzFfGQARP0i+p9GdHbTYIGw6PgOM096RX4se1ExAJLtE=,iv:ZC++9TxUU7wdEVWCa3hNho9e8kFDnOQV+5Yg1e7APgc=,tag:dMHfwkQfmhwuU4IiZx5Cew==,type:str]
    version: 3.13.3
