apiVersion: v1
kind: Secret
metadata:
    name: terraria-secret
    namespace: terraria
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:y+/5JsXgBpsMifX/k9hY1tootMDMgOAz5fTaBL4SChcUG1efh1e4mCSs1hzcNEAR8hkH1M6MU/NkLWJlIcHYnqlolDIeYFCKYW2B4xr8C1yS2rpL+jOmFJvIFUcYNh1W4xbflcXwjPOT5mtoJoO1DP8bXM8SOze25Z6bdw==,iv:PYC1QAEpHYsGAMuBZfkERj0hmUYBIfIbj2JXxBkiTHE=,tag:TOPNPeyoJ38/lM5aXAAsGg==,type:str]
    SERVER_ADDRESS: ENC[AES256_GCM,data:CBaq2/4wd3ADcSW3rxFht9aidNr17S5V,iv:c1EBkF36igg+enNi1ZMauwUJRjTXU+W9a0Bwa+/QeDc=,tag:UfBIGzDqREdTlEZyWr/QUA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBaTVDRXBW
            RkZWc0tNT0ZaUnVHcklCQS9JVksvQTBqcDluNUcxWEhvdk9HdworSXpJSXk2bmNH
            QS9lamxwSEpmUGRXY1RMWkx3Tkt0UDFWWDBETjBmc2FrCi0tLSBqdC84elp4WDZW
            OU4yT1c0ZlBtczFkNVZnekNlRExmR0Y2SlphdmdiNDc4Cuz8gBGFBEabGkMqdjEf
            UfYUEcgr4n5BBzGo/laeM3qE6QFKj04NfaATRRejcf10KgG6q3M/8YoOncpKcqwc
            YoQ=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLRkZPZ0NQZ0NGYVhOYWxB
            QlhDNm1tcGlwQ01pY09OL3FtTmhuQlVBckFjCmlYSUdHZ1N1MWdrRkZGcVJPb29k
            cnBzSTJqSDRQSElxcjNobGoxYjJWQ1kKLS0tIHJ0NjFlTEp5Q2JyOHg4SXRZSk1w
            clc1TFhLdXlGUU9jQ3lnVUhNSTRlRnMKZTLy8hxOa+tU8OkCwtXYkGQiMc6NiCic
            0h6yX1Q3s703BRtBrGXkCTdPIdcQ5oEmQR/gGrFZCyEJNmIsESc+rw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T00:21:14Z"
    mac: ENC[AES256_GCM,data:VeO/E8XTvCpzWuHltXQPLpu8GmBDpdGJyrY6vVjHr7b9YElIs91RubqftQDjb2yzs8uQa7SQ88Fl62gb+RGnWA2Dq36BF/9Ode7OweN97mCvkHnbxCelLG4yROWiO+wGv821MBQQXYYFYVNEYhT+kOxAYuEAnSUcEXrEFCQYU4M=,iv:yo+quD0KRkjateVt2+Fc+KoGCZRDZAKk7wgdK0OMWDU=,tag:pKeoAncNLRjWIhGW38pC6A==,type:str]
    version: 3.13.3
