apiVersion: v1
kind: Secret
metadata:
    name: terraria-makoto-secret
    namespace: terraria
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ""
    SERVER_ADDRESS: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBbkU4R25l
            QjIxZGZTZ1B6djJQdnNGUElWWW1kOUNYTW8yaGVFZitjWDBPNApBSUw1dDVTdXZn
            ZGYvVFFFU01Tdm5peXU3cGRhVVdHNElrQ0xGVnFKb2ZRCi0tLSBtVGdFUnkxcjRP
            dFBGSERHM1JrcjJwZzhTNG9MTU9CMDBtcnFpRkRmSTdzCu4RTpRsMA9I3+xr6sAj
            5FbrqWkcqq+rAPCYJS2KQ5IqfHYPIYNHwrsF1YhK8/dW03mq96tFnNU0QO8MsUoN
            QUc=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bEVQUUpVdEVPL3h6RDEy
            RExMRzZtbkJXY2Qrc1p2Zk1GdVczZ1B5dWxRCldmK1JRVGJkMm9xUUZVd2k4c1M0
            UjNFcnk4Zm5yaVFVN3lHV01NaXYvdUUKLS0tIHd4SnVicERnSi9ZRXhqcVdHYXhQ
            ZkVVeko1MVRkYXIxYXl0MTFRQ29hRFEKUa4SS5Uge4XzQSjx6dqLZeUXGEzUrsCF
            cgoc/K6KLoT9bVXjpkFHdkAb0/x9zkEV/BWFeB/177TmUtXhWESuNQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T03:48:17Z"
    mac: ENC[AES256_GCM,data:G6XiqtLnUrPhcbfKF5Iqci7yQvDc6aIibLGRAiD18K34OTTSi5CBuYBWthSj4GuL+y+Pwouwlky7IV5yOoGeZQd8D4eOFnbCO2Bx2FuZgR9JeAqfKJ2N5jrUmx93YtUA9BiLSSFqBLtMtuDrYBK3lBMLHFloyeZ72a0vp/SpLA0=,iv:kuMyy9ONW0DW4jGtU7cGzPBSdmitIoFLCG5naYOFpJA=,tag:KCmN9l2xd4LW41qyoSJ8KA==,type:str]
    version: 3.13.3
