apiVersion: v1
kind: Secret
metadata:
    name: terraria-makoto-secret
    namespace: terraria
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:8XVC3sawFtvQx0WLkEF6gfGSSxCjGvn8a6syPRVrsOJB8Okdttb4k4VvRciANYFgIP1QQCjCNQVaf2QDVJn1ErH4kolYtJP0axzgPwtb/1hkQ1LYmcEaUSKQT5f45nov1FDRbp86RYM97W/BNaiokV8ZiXRIV/jbXpWm9w==,iv:k+CA5l5o2PBH+S8EsNX35eecvJUNK8u0hwFUhP7NT7k=,tag:Tc8M7fluCv8EtHd2Jp/8uQ==,type:str]
    SERVER_ADDRESS: ENC[AES256_GCM,data:OYToF3mi8r8E/JugXLfCKR8ZF3fhtTL3a1vPV6uf,iv:8ZUyGVf2em6fTVgEMsa7K3F9jbntoyAR7BC9/sGzd/s=,tag:lyugDBIRL2zvZjjk7Ps3sA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBazhtNmFW
            T2plcUZnYzFGNjlXeUNXaHlRdGJ6WWF0MGJBQ2VuSHdxdXRoUgpVczdjb2pXWVJI
            WWsvTzJXTWVzSTdmR3lIeGJLWVdiNEIvOFU2ZmhuYzFBCi0tLSBqMm1FSER6S0Ft
            OGlSalBBNXFaYkVzbjJKYzlWUTVhY2ovaVZrQ3JHdGlRCvZNOHodWB/H3Oglz2AT
            wJPd/saMl8rZ/oaQgiFWJlzl/MmjvEIe4kTLsUf2kUq/nFu4g8Gyfm1UbVQX0oJo
            Nes=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLam4rTHJ5cUtvL05TY0Uz
            OFQvZWszcjVNZ040aGpwaTBYTXZJRUpCeVJjCmQwcWlCMXBSTzVabkt1cVNETUQw
            ckZpWE9HcGgyeVR4YzhRcUprTkc4RUEKLS0tIEwwQ3UvT0MyaE1KYzlmTllmRy9O
            VGl6eDM4ZmFXR2REL2gwOUJOclRuaWMKWZwLf0MyZM4knmJ8ET5OQAMm5yN/chHH
            LM4S0uDR47dcShWrF7EtjKpeKTFdTWYfZmk8mjdD7/g+LwmmGpETYg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T04:22:54Z"
    mac: ENC[AES256_GCM,data:L44xe4TZMwP7OxNMIncPoaTwHWLqaomf1QX23WkPi2LC05K9DxPLVqb/VPaDv+INfIm3pzThOFg/WoK/HaRgRYkUJOPzj/QCvzBxd454hRvWgaXUjfY7oCCESIutCWZvc4AqOrhksJplTe35xvMbvk/fYh7MeacaDHeXKxqFF1c=,iv:9g2Ap1q8El8jLLT+70TVLItgZzHBj9qNfEKQpSXepAA=,tag:fI4Y9vUb1ST+hljZm4N4TQ==,type:str]
    version: 3.13.3
